// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: chatto/core/evt/v1/asset_events.proto

package evtv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AssetCreatedEvent records durable content identity for one uploaded or
// generated binary. Emitted at the moment the binary lands in storage, NOT
// at message-post time — the asset is its own aggregate, and messages
// reference it via MessageBody.asset_ids.
//
// Owner context is carried as flat optional fields:
//
//   - room_id is set for room-scoped assets (uploaded into a room context)
//   - user_id is set for user-scoped assets (e.g. avatars) or, for
//     room-scoped uploads, the uploader's ID
//   - parent_asset_id + derivative_role are set for derivatives (e.g. video
//     thumbnail / variant); inherits room scope from the parent
//
// AssetDerivativeRole enumerates the kinds of derivative an asset can be.
// Only meaningful when an AssetCreatedEvent carries a parent_asset_id.
type AssetDerivativeRole int32

const (
	// Not a derivative (the asset is an original upload), or unknown role.
	AssetDerivativeRole_ASSET_DERIVATIVE_ROLE_UNSPECIFIED AssetDerivativeRole = 0
	// A still-image thumbnail generated from the parent asset.
	AssetDerivativeRole_ASSET_DERIVATIVE_ROLE_THUMBNAIL AssetDerivativeRole = 1
	// A transcoded video rendition (e.g. a 480p variant) of the parent.
	AssetDerivativeRole_ASSET_DERIVATIVE_ROLE_VIDEO_VARIANT AssetDerivativeRole = 2
	// One bounded HLS media segment generated for a parent video rendition.
	AssetDerivativeRole_ASSET_DERIVATIVE_ROLE_HLS_MEDIA_SEGMENT AssetDerivativeRole = 3
)

// Enum value maps for AssetDerivativeRole.
var (
	AssetDerivativeRole_name = map[int32]string{
		0: "ASSET_DERIVATIVE_ROLE_UNSPECIFIED",
		1: "ASSET_DERIVATIVE_ROLE_THUMBNAIL",
		2: "ASSET_DERIVATIVE_ROLE_VIDEO_VARIANT",
		3: "ASSET_DERIVATIVE_ROLE_HLS_MEDIA_SEGMENT",
	}
	AssetDerivativeRole_value = map[string]int32{
		"ASSET_DERIVATIVE_ROLE_UNSPECIFIED":       0,
		"ASSET_DERIVATIVE_ROLE_THUMBNAIL":         1,
		"ASSET_DERIVATIVE_ROLE_VIDEO_VARIANT":     2,
		"ASSET_DERIVATIVE_ROLE_HLS_MEDIA_SEGMENT": 3,
	}
)

func (x AssetDerivativeRole) Enum() *AssetDerivativeRole {
	p := new(AssetDerivativeRole)
	*p = x
	return p
}

func (x AssetDerivativeRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetDerivativeRole) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_core_evt_v1_asset_events_proto_enumTypes[0].Descriptor()
}

func (AssetDerivativeRole) Type() protoreflect.EnumType {
	return &file_chatto_core_evt_v1_asset_events_proto_enumTypes[0]
}

func (x AssetDerivativeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetDerivativeRole.Descriptor instead.
func (AssetDerivativeRole) EnumDescriptor() ([]byte, []int) {
	return file_chatto_core_evt_v1_asset_events_proto_rawDescGZIP(), []int{0}
}

type AssetProcessingFailureCode int32

const (
	AssetProcessingFailureCode_ASSET_PROCESSING_FAILURE_CODE_UNSPECIFIED       AssetProcessingFailureCode = 0
	AssetProcessingFailureCode_ASSET_PROCESSING_FAILURE_CODE_PROCESSING_FAILED AssetProcessingFailureCode = 1
	AssetProcessingFailureCode_ASSET_PROCESSING_FAILURE_CODE_SOURCE_MISSING    AssetProcessingFailureCode = 2
)

// Enum value maps for AssetProcessingFailureCode.
var (
	AssetProcessingFailureCode_name = map[int32]string{
		0: "ASSET_PROCESSING_FAILURE_CODE_UNSPECIFIED",
		1: "ASSET_PROCESSING_FAILURE_CODE_PROCESSING_FAILED",
		2: "ASSET_PROCESSING_FAILURE_CODE_SOURCE_MISSING",
	}
	AssetProcessingFailureCode_value = map[string]int32{
		"ASSET_PROCESSING_FAILURE_CODE_UNSPECIFIED":       0,
		"ASSET_PROCESSING_FAILURE_CODE_PROCESSING_FAILED": 1,
		"ASSET_PROCESSING_FAILURE_CODE_SOURCE_MISSING":    2,
	}
)

func (x AssetProcessingFailureCode) Enum() *AssetProcessingFailureCode {
	p := new(AssetProcessingFailureCode)
	*p = x
	return p
}

func (x AssetProcessingFailureCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetProcessingFailureCode) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_core_evt_v1_asset_events_proto_enumTypes[1].Descriptor()
}

func (AssetProcessingFailureCode) Type() protoreflect.EnumType {
	return &file_chatto_core_evt_v1_asset_events_proto_enumTypes[1]
}

func (x AssetProcessingFailureCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetProcessingFailureCode.Descriptor instead.
func (AssetProcessingFailureCode) EnumDescriptor() ([]byte, []int) {
	return file_chatto_core_evt_v1_asset_events_proto_rawDescGZIP(), []int{1}
}

// AssetCreatedEvent carries no message linkage: it is emitted at upload
// time, before any message exists. AssetAttachedEvent later records the
// exclusive message attachment; MessageBodyEvent.asset_ids remains a replay
// fallback for histories written before explicit attachment events existed.
type AssetCreatedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The asset record (content identity + storage).
	Asset *AssetRecord `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	// Whether the original uploaded binary was available when the event was
	// written. New uploads are always true; legacy migrated source assets may
	// be false because older pipelines deleted originals after transcoding.
	OriginalBinaryAvailable bool `protobuf:"varint,2,opt,name=original_binary_available,json=originalBinaryAvailable,proto3" json:"original_binary_available,omitempty"`
	// Room scope. Set for room-scoped uploads and their derivatives.
	RoomId string `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// ID of the parent asset when this asset is a derivative.
	// Set together with derivative_role for thumbnails / video variants.
	ParentAssetId string `protobuf:"bytes,5,opt,name=parent_asset_id,json=parentAssetId,proto3" json:"parent_asset_id,omitempty"`
	// Derivative role (thumbnail, video variant, …).
	// Only meaningful when parent_asset_id is set.
	DerivativeRole AssetDerivativeRole `protobuf:"varint,6,opt,name=derivative_role,json=derivativeRole,proto3,enum=chatto.core.evt.v1.AssetDerivativeRole" json:"derivative_role,omitempty"`
	// ID of the user that owns or uploaded this asset. Always set on new
	// events: the uploader for room-scoped uploads, the avatar owner for
	// avatar assets. Empty only for worker-generated derivatives.
	UserId string `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// SHA-256 digest of the original uploaded binary, lowercase hexadecimal.
	// Empty for legacy assets and generated derivatives.
	Sha256 string `protobuf:"bytes,8,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// Time after which an unattached room-scoped upload may be deleted. Ignored
	// once AssetAttachedEvent binds the asset to a message.
	PendingExpiresAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=pending_expires_at,json=pendingExpiresAt,proto3" json:"pending_expires_at,omitempty"`
	// Whether this asset should be routed through attachment video processing
	// after a message attaches it. Set for videos and animated GIFs.
	NeedsVideoProcessing bool `protobuf:"varint,10,opt,name=needs_video_processing,json=needsVideoProcessing,proto3" json:"needs_video_processing,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AssetCreatedEvent) Reset() {
	*x = AssetCreatedEvent{}
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetCreatedEvent) ProtoMessage() {}

func (x *AssetCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetCreatedEvent.ProtoReflect.Descriptor instead.
func (*AssetCreatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_evt_v1_asset_events_proto_rawDescGZIP(), []int{0}
}

func (x *AssetCreatedEvent) GetAsset() *AssetRecord {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *AssetCreatedEvent) GetOriginalBinaryAvailable() bool {
	if x != nil {
		return x.OriginalBinaryAvailable
	}
	return false
}

func (x *AssetCreatedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AssetCreatedEvent) GetParentAssetId() string {
	if x != nil {
		return x.ParentAssetId
	}
	return ""
}

func (x *AssetCreatedEvent) GetDerivativeRole() AssetDerivativeRole {
	if x != nil {
		return x.DerivativeRole
	}
	return AssetDerivativeRole_ASSET_DERIVATIVE_ROLE_UNSPECIFIED
}

func (x *AssetCreatedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssetCreatedEvent) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *AssetCreatedEvent) GetPendingExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PendingExpiresAt
	}
	return nil
}

func (x *AssetCreatedEvent) GetNeedsVideoProcessing() bool {
	if x != nil {
		return x.NeedsVideoProcessing
	}
	return false
}

// AssetDeletedEvent terminates the asset lifecycle. Subscribers drop the
// asset from any local projection; storage cleanup is separate.
type AssetDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetDeletedEvent) Reset() {
	*x = AssetDeletedEvent{}
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetDeletedEvent) ProtoMessage() {}

func (x *AssetDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetDeletedEvent.ProtoReflect.Descriptor instead.
func (*AssetDeletedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_evt_v1_asset_events_proto_rawDescGZIP(), []int{1}
}

func (x *AssetDeletedEvent) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

// AssetAttachedEvent records that one pending uploaded asset became an
// attachment of the exact message that first references it. The attachment
// commits atomically with the message and is fenced against the complete asset
// aggregate.
type AssetAttachedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Asset ID being attached.
	AssetId string `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// Room containing both the upload and owning message.
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Event ID of the one message that owns the asset.
	MessageEventId string `protobuf:"bytes,3,opt,name=message_event_id,json=messageEventId,proto3" json:"message_event_id,omitempty"`
	// User ID of the uploader and message author.
	UserId string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Frozen audience and lifetimes for an opt-in view-once attachment.
	Burn          *AssetBurnState `protobuf:"bytes,5,opt,name=burn,proto3" json:"burn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetAttachedEvent) Reset() {
	*x = AssetAttachedEvent{}
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetAttachedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetAttachedEvent) ProtoMessage() {}

func (x *AssetAttachedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetAttachedEvent.ProtoReflect.Descriptor instead.
func (*AssetAttachedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_evt_v1_asset_events_proto_rawDescGZIP(), []int{2}
}

func (x *AssetAttachedEvent) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetAttachedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AssetAttachedEvent) GetMessageEventId() string {
	if x != nil {
		return x.MessageEventId
	}
	return ""
}

func (x *AssetAttachedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssetAttachedEvent) GetBurn() *AssetBurnState {
	if x != nil {
		return x.Burn
	}
	return nil
}

// AssetBurnState is the durable access history of one view-once attachment.
// Lifetimes are captured at send time; configuration changes do not reset them.
type AssetBurnState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AssetId            string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	RoomId             string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	MessageEventId     string                 `protobuf:"bytes,3,opt,name=message_event_id,json=messageEventId,proto3" json:"message_event_id,omitempty"`
	UserId             string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RecipientIds       []string               `protobuf:"bytes,5,rep,name=recipient_ids,json=recipientIds,proto3" json:"recipient_ids,omitempty"`
	UnopenedExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=unopened_expires_at,json=unopenedExpiresAt,proto3" json:"unopened_expires_at,omitempty"`
	ViewDurationMs     int64                  `protobuf:"varint,7,opt,name=view_duration_ms,json=viewDurationMs,proto3" json:"view_duration_ms,omitempty"`
	RecoveryDurationMs int64                  `protobuf:"varint,8,opt,name=recovery_duration_ms,json=recoveryDurationMs,proto3" json:"recovery_duration_ms,omitempty"`
	Views              []*AssetBurnView       `protobuf:"bytes,9,rep,name=views,proto3" json:"views,omitempty"`
	RequesterIds       []string               `protobuf:"bytes,10,rep,name=requester_ids,json=requesterIds,proto3" json:"requester_ids,omitempty"`
	Permanent          bool                   `protobuf:"varint,11,opt,name=permanent,proto3" json:"permanent,omitempty"`
	PermanentEventId   string                 `protobuf:"bytes,12,opt,name=permanent_event_id,json=permanentEventId,proto3" json:"permanent_event_id,omitempty"`
	UndoExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=undo_expires_at,json=undoExpiresAt,proto3" json:"undo_expires_at,omitempty"`
	// Successful first-use explanation, retained across undo and deletion.
	PermanenceAcknowledged bool `protobuf:"varint,14,opt,name=permanence_acknowledged,json=permanenceAcknowledged,proto3" json:"permanence_acknowledged,omitempty"`
	// Resolve the verified processed video duration when claiming a session.
	UseVideoDuration bool `protobuf:"varint,15,opt,name=use_video_duration,json=useVideoDuration,proto3" json:"use_video_duration,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AssetBurnState) Reset() {
	*x = AssetBurnState{}
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetBurnState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetBurnState) ProtoMessage() {}

func (x *AssetBurnState) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetBurnState.ProtoReflect.Descriptor instead.
func (*AssetBurnState) Descriptor() ([]byte, []int) {
	return file_chatto_core_evt_v1_asset_events_proto_rawDescGZIP(), []int{3}
}

func (x *AssetBurnState) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetBurnState) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AssetBurnState) GetMessageEventId() string {
	if x != nil {
		return x.MessageEventId
	}
	return ""
}

func (x *AssetBurnState) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssetBurnState) GetRecipientIds() []string {
	if x != nil {
		return x.RecipientIds
	}
	return nil
}

func (x *AssetBurnState) GetUnopenedExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UnopenedExpiresAt
	}
	return nil
}

func (x *AssetBurnState) GetViewDurationMs() int64 {
	if x != nil {
		return x.ViewDurationMs
	}
	return 0
}

func (x *AssetBurnState) GetRecoveryDurationMs() int64 {
	if x != nil {
		return x.RecoveryDurationMs
	}
	return 0
}

func (x *AssetBurnState) GetViews() []*AssetBurnView {
	if x != nil {
		return x.Views
	}
	return nil
}

func (x *AssetBurnState) GetRequesterIds() []string {
	if x != nil {
		return x.RequesterIds
	}
	return nil
}

func (x *AssetBurnState) GetPermanent() bool {
	if x != nil {
		return x.Permanent
	}
	return false
}

func (x *AssetBurnState) GetPermanentEventId() string {
	if x != nil {
		return x.PermanentEventId
	}
	return ""
}

func (x *AssetBurnState) GetUndoExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UndoExpiresAt
	}
	return nil
}

func (x *AssetBurnState) GetPermanenceAcknowledged() bool {
	if x != nil {
		return x.PermanenceAcknowledged
	}
	return false
}

func (x *AssetBurnState) GetUseVideoDuration() bool {
	if x != nil {
		return x.UseVideoDuration
	}
	return false
}

// AssetBurnView reserves a single logical viewing session for one recipient.
type AssetBurnView struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// SHA-256 verifier for the caller-generated viewing-session capability.
	SessionHash   string                 `protobuf:"bytes,2,opt,name=session_hash,json=sessionHash,proto3" json:"session_hash,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ClosedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetBurnView) Reset() {
	*x = AssetBurnView{}
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetBurnView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetBurnView) ProtoMessage() {}

func (x *AssetBurnView) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetBurnView.ProtoReflect.Descriptor instead.
func (*AssetBurnView) Descriptor() ([]byte, []int) {
	return file_chatto_core_evt_v1_asset_events_proto_rawDescGZIP(), []int{4}
}

func (x *AssetBurnView) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssetBurnView) GetSessionHash() string {
	if x != nil {
		return x.SessionHash
	}
	return ""
}

func (x *AssetBurnView) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AssetBurnView) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

// AssetBurnUpdatedEvent records a view, request, conversion, or undo under the
// complete asset aggregate's OCC boundary. It never contains file bytes or a
// raw viewing-session capability.
type AssetBurnUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *AssetBurnState        `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetBurnUpdatedEvent) Reset() {
	*x = AssetBurnUpdatedEvent{}
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetBurnUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetBurnUpdatedEvent) ProtoMessage() {}

func (x *AssetBurnUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetBurnUpdatedEvent.ProtoReflect.Descriptor instead.
func (*AssetBurnUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_evt_v1_asset_events_proto_rawDescGZIP(), []int{5}
}

func (x *AssetBurnUpdatedEvent) GetState() *AssetBurnState {
	if x != nil {
		return x.State
	}
	return nil
}

// AssetProcessingStartedEvent signals that derivative processing has been
// enqueued for an asset. It is the PENDING marker the frontend uses to
// render a "processing…" placeholder until succeeded/failed lands.
type AssetProcessingStartedEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AssetId string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// Event id of the owning message, stamped at publish time by the code that
	// schedules processing (which already knows it). Carried on the event so
	// subscribers don't have to look ownership up from the projection — that
	// lookup would race the owning MessagePostedEvent's own projection. Empty
	// only for one-shot migration events, which are never delivered live.
	MessageEventId string `protobuf:"bytes,2,opt,name=message_event_id,json=messageEventId,proto3" json:"message_event_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssetProcessingStartedEvent) Reset() {
	*x = AssetProcessingStartedEvent{}
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetProcessingStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetProcessingStartedEvent) ProtoMessage() {}

func (x *AssetProcessingStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetProcessingStartedEvent.ProtoReflect.Descriptor instead.
func (*AssetProcessingStartedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_evt_v1_asset_events_proto_rawDescGZIP(), []int{6}
}

func (x *AssetProcessingStartedEvent) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetProcessingStartedEvent) GetMessageEventId() string {
	if x != nil {
		return x.MessageEventId
	}
	return ""
}

// AssetProcessingSucceededEvent records a durable, displayable processing
// outcome. Only video-shaped processing exists today; if additional kinds
// are added in the future they will become new fields on this message.
type AssetProcessingSucceededEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AssetId string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// Video/GIF derivative manifest. Set for video and animated-GIF assets.
	Video *AssetProcessedVideo `protobuf:"bytes,2,opt,name=video,proto3" json:"video,omitempty"`
	// Event id of the owning message, stamped at publish time (see
	// AssetProcessingStartedEvent.message_event_id). Empty only for one-shot
	// migration events.
	MessageEventId string `protobuf:"bytes,3,opt,name=message_event_id,json=messageEventId,proto3" json:"message_event_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssetProcessingSucceededEvent) Reset() {
	*x = AssetProcessingSucceededEvent{}
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetProcessingSucceededEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetProcessingSucceededEvent) ProtoMessage() {}

func (x *AssetProcessingSucceededEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetProcessingSucceededEvent.ProtoReflect.Descriptor instead.
func (*AssetProcessingSucceededEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_evt_v1_asset_events_proto_rawDescGZIP(), []int{7}
}

func (x *AssetProcessingSucceededEvent) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetProcessingSucceededEvent) GetVideo() *AssetProcessedVideo {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *AssetProcessingSucceededEvent) GetMessageEventId() string {
	if x != nil {
		return x.MessageEventId
	}
	return ""
}

// AssetProcessingFailedEvent records a durable failed/unavailable outcome.
// A later AssetProcessingSucceededEvent for the same asset supersedes it.
type AssetProcessingFailedEvent struct {
	state       protoimpl.MessageState     `protogen:"open.v1"`
	AssetId     string                     `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	FailureCode AssetProcessingFailureCode `protobuf:"varint,2,opt,name=failure_code,json=failureCode,proto3,enum=chatto.core.evt.v1.AssetProcessingFailureCode" json:"failure_code,omitempty"`
	// Event id of the owning message, stamped at publish time (see
	// AssetProcessingStartedEvent.message_event_id). Empty only for one-shot
	// migration events.
	MessageEventId string `protobuf:"bytes,3,opt,name=message_event_id,json=messageEventId,proto3" json:"message_event_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssetProcessingFailedEvent) Reset() {
	*x = AssetProcessingFailedEvent{}
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetProcessingFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetProcessingFailedEvent) ProtoMessage() {}

func (x *AssetProcessingFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetProcessingFailedEvent.ProtoReflect.Descriptor instead.
func (*AssetProcessingFailedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_evt_v1_asset_events_proto_rawDescGZIP(), []int{8}
}

func (x *AssetProcessingFailedEvent) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetProcessingFailedEvent) GetFailureCode() AssetProcessingFailureCode {
	if x != nil {
		return x.FailureCode
	}
	return AssetProcessingFailureCode_ASSET_PROCESSING_FAILURE_CODE_UNSPECIFIED
}

func (x *AssetProcessingFailedEvent) GetMessageEventId() string {
	if x != nil {
		return x.MessageEventId
	}
	return ""
}

// AssetProcessedVideo is the per-asset video manifest carried by
// AssetProcessingSucceededEvent. Derivative assets (thumbnail + variants)
// are referenced by id and have their own AssetCreatedEvent records.
type AssetProcessedVideo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DurationMs       int64                  `protobuf:"varint,1,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Width            int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height           int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	ThumbnailAssetId string                 `protobuf:"bytes,4,opt,name=thumbnail_asset_id,json=thumbnailAssetId,proto3" json:"thumbnail_asset_id,omitempty"`
	Variants         []*AssetVideoVariant   `protobuf:"bytes,5,rep,name=variants,proto3" json:"variants,omitempty"`
	// HLS adaptive-streaming manifest. Absent on historical MP4-only results.
	Hls           *AssetProcessedHLS `protobuf:"bytes,6,opt,name=hls,proto3" json:"hls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetProcessedVideo) Reset() {
	*x = AssetProcessedVideo{}
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetProcessedVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetProcessedVideo) ProtoMessage() {}

func (x *AssetProcessedVideo) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetProcessedVideo.ProtoReflect.Descriptor instead.
func (*AssetProcessedVideo) Descriptor() ([]byte, []int) {
	return file_chatto_core_evt_v1_asset_events_proto_rawDescGZIP(), []int{9}
}

func (x *AssetProcessedVideo) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *AssetProcessedVideo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *AssetProcessedVideo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *AssetProcessedVideo) GetThumbnailAssetId() string {
	if x != nil {
		return x.ThumbnailAssetId
	}
	return ""
}

func (x *AssetProcessedVideo) GetVariants() []*AssetVideoVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *AssetProcessedVideo) GetHls() *AssetProcessedHLS {
	if x != nil {
		return x.Hls
	}
	return nil
}

type AssetVideoVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quality       string                 `protobuf:"bytes,1,opt,name=quality,proto3" json:"quality,omitempty"` // e.g., "720p", "480p"
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetVideoVariant) Reset() {
	*x = AssetVideoVariant{}
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetVideoVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetVideoVariant) ProtoMessage() {}

func (x *AssetVideoVariant) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetVideoVariant.ProtoReflect.Descriptor instead.
func (*AssetVideoVariant) Descriptor() ([]byte, []int) {
	return file_chatto_core_evt_v1_asset_events_proto_rawDescGZIP(), []int{10}
}

func (x *AssetVideoVariant) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *AssetVideoVariant) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

// AssetProcessedHLS contains enough durable metadata to render HLS playlists
// on demand. Only media segments are stored as derivative assets; clients
// receive an authorised master-playlist URL rather than these relationships.
type AssetProcessedHLS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Renditions    []*AssetHLSRendition   `protobuf:"bytes,1,rep,name=renditions,proto3" json:"renditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetProcessedHLS) Reset() {
	*x = AssetProcessedHLS{}
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetProcessedHLS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetProcessedHLS) ProtoMessage() {}

func (x *AssetProcessedHLS) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetProcessedHLS.ProtoReflect.Descriptor instead.
func (*AssetProcessedHLS) Descriptor() ([]byte, []int) {
	return file_chatto_core_evt_v1_asset_events_proto_rawDescGZIP(), []int{11}
}

func (x *AssetProcessedHLS) GetRenditions() []*AssetHLSRendition {
	if x != nil {
		return x.Renditions
	}
	return nil
}

type AssetHLSRendition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Bandwidth     int64                  `protobuf:"varint,4,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	Segments      []*AssetHLSSegment     `protobuf:"bytes,5,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetHLSRendition) Reset() {
	*x = AssetHLSRendition{}
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetHLSRendition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetHLSRendition) ProtoMessage() {}

func (x *AssetHLSRendition) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetHLSRendition.ProtoReflect.Descriptor instead.
func (*AssetHLSRendition) Descriptor() ([]byte, []int) {
	return file_chatto_core_evt_v1_asset_events_proto_rawDescGZIP(), []int{12}
}

func (x *AssetHLSRendition) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *AssetHLSRendition) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *AssetHLSRendition) GetBandwidth() int64 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *AssetHLSRendition) GetSegments() []*AssetHLSSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type AssetHLSSegment struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AssetId string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// Exact EXTINF duration, rounded to milliseconds during packaging.
	DurationMs    int64 `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetHLSSegment) Reset() {
	*x = AssetHLSSegment{}
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetHLSSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetHLSSegment) ProtoMessage() {}

func (x *AssetHLSSegment) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_evt_v1_asset_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetHLSSegment.ProtoReflect.Descriptor instead.
func (*AssetHLSSegment) Descriptor() ([]byte, []int) {
	return file_chatto_core_evt_v1_asset_events_proto_rawDescGZIP(), []int{13}
}

func (x *AssetHLSSegment) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetHLSSegment) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_chatto_core_evt_v1_asset_events_proto protoreflect.FileDescriptor

const file_chatto_core_evt_v1_asset_events_proto_rawDesc = "" +
	"\n" +
	"%chatto/core/evt/v1/asset_events.proto\x12\x12chatto.core.evt.v1\x1a\x1fchatto/core/evt/v1/models.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x03\n" +
	"\x11AssetCreatedEvent\x125\n" +
	"\x05asset\x18\x01 \x01(\v2\x1f.chatto.core.evt.v1.AssetRecordR\x05asset\x12:\n" +
	"\x19original_binary_available\x18\x02 \x01(\bR\x17originalBinaryAvailable\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12&\n" +
	"\x0fparent_asset_id\x18\x05 \x01(\tR\rparentAssetId\x12P\n" +
	"\x0fderivative_role\x18\x06 \x01(\x0e2'.chatto.core.evt.v1.AssetDerivativeRoleR\x0ederivativeRole\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\x12\x16\n" +
	"\x06sha256\x18\b \x01(\tR\x06sha256\x12H\n" +
	"\x12pending_expires_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x10pendingExpiresAt\x124\n" +
	"\x16needs_video_processing\x18\n" +
	" \x01(\bR\x14needsVideoProcessingJ\x04\b\x04\x10\x05R\x10message_event_id\".\n" +
	"\x11AssetDeletedEvent\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\"\xc3\x01\n" +
	"\x12AssetAttachedEvent\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12(\n" +
	"\x10message_event_id\x18\x03 \x01(\tR\x0emessageEventId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x126\n" +
	"\x04burn\x18\x05 \x01(\v2\".chatto.core.evt.v1.AssetBurnStateR\x04burn\"\xa9\x05\n" +
	"\x0eAssetBurnState\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12(\n" +
	"\x10message_event_id\x18\x03 \x01(\tR\x0emessageEventId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12#\n" +
	"\rrecipient_ids\x18\x05 \x03(\tR\frecipientIds\x12J\n" +
	"\x13unopened_expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x11unopenedExpiresAt\x12(\n" +
	"\x10view_duration_ms\x18\a \x01(\x03R\x0eviewDurationMs\x120\n" +
	"\x14recovery_duration_ms\x18\b \x01(\x03R\x12recoveryDurationMs\x127\n" +
	"\x05views\x18\t \x03(\v2!.chatto.core.evt.v1.AssetBurnViewR\x05views\x12#\n" +
	"\rrequester_ids\x18\n" +
	" \x03(\tR\frequesterIds\x12\x1c\n" +
	"\tpermanent\x18\v \x01(\bR\tpermanent\x12,\n" +
	"\x12permanent_event_id\x18\f \x01(\tR\x10permanentEventId\x12B\n" +
	"\x0fundo_expires_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\rundoExpiresAt\x127\n" +
	"\x17permanence_acknowledged\x18\x0e \x01(\bR\x16permanenceAcknowledged\x12,\n" +
	"\x12use_video_duration\x18\x0f \x01(\bR\x10useVideoDuration\"\xbf\x01\n" +
	"\rAssetBurnView\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fsession_hash\x18\x02 \x01(\tR\vsessionHash\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x127\n" +
	"\tclosed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\"Q\n" +
	"\x15AssetBurnUpdatedEvent\x128\n" +
	"\x05state\x18\x01 \x01(\v2\".chatto.core.evt.v1.AssetBurnStateR\x05state\"b\n" +
	"\x1bAssetProcessingStartedEvent\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12(\n" +
	"\x10message_event_id\x18\x02 \x01(\tR\x0emessageEventId\"\xa3\x01\n" +
	"\x1dAssetProcessingSucceededEvent\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12=\n" +
	"\x05video\x18\x02 \x01(\v2'.chatto.core.evt.v1.AssetProcessedVideoR\x05video\x12(\n" +
	"\x10message_event_id\x18\x03 \x01(\tR\x0emessageEventId\"\xb4\x01\n" +
	"\x1aAssetProcessingFailedEvent\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12Q\n" +
	"\ffailure_code\x18\x02 \x01(\x0e2..chatto.core.evt.v1.AssetProcessingFailureCodeR\vfailureCode\x12(\n" +
	"\x10message_event_id\x18\x03 \x01(\tR\x0emessageEventId\"\x8e\x02\n" +
	"\x13AssetProcessedVideo\x12\x1f\n" +
	"\vduration_ms\x18\x01 \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12,\n" +
	"\x12thumbnail_asset_id\x18\x04 \x01(\tR\x10thumbnailAssetId\x12A\n" +
	"\bvariants\x18\x05 \x03(\v2%.chatto.core.evt.v1.AssetVideoVariantR\bvariants\x127\n" +
	"\x03hls\x18\x06 \x01(\v2%.chatto.core.evt.v1.AssetProcessedHLSR\x03hls\"H\n" +
	"\x11AssetVideoVariant\x12\x18\n" +
	"\aquality\x18\x01 \x01(\tR\aquality\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\"Z\n" +
	"\x11AssetProcessedHLS\x12E\n" +
	"\n" +
	"renditions\x18\x01 \x03(\v2%.chatto.core.evt.v1.AssetHLSRenditionR\n" +
	"renditions\"\xa0\x01\n" +
	"\x11AssetHLSRendition\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1c\n" +
	"\tbandwidth\x18\x04 \x01(\x03R\tbandwidth\x12?\n" +
	"\bsegments\x18\x05 \x03(\v2#.chatto.core.evt.v1.AssetHLSSegmentR\bsegments\"M\n" +
	"\x0fAssetHLSSegment\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x03R\n" +
	"durationMs*\xb7\x01\n" +
	"\x13AssetDerivativeRole\x12%\n" +
	"!ASSET_DERIVATIVE_ROLE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fASSET_DERIVATIVE_ROLE_THUMBNAIL\x10\x01\x12'\n" +
	"#ASSET_DERIVATIVE_ROLE_VIDEO_VARIANT\x10\x02\x12+\n" +
	"'ASSET_DERIVATIVE_ROLE_HLS_MEDIA_SEGMENT\x10\x03*\xb2\x01\n" +
	"\x1aAssetProcessingFailureCode\x12-\n" +
	")ASSET_PROCESSING_FAILURE_CODE_UNSPECIFIED\x10\x00\x123\n" +
	"/ASSET_PROCESSING_FAILURE_CODE_PROCESSING_FAILED\x10\x01\x120\n" +
	",ASSET_PROCESSING_FAILURE_CODE_SOURCE_MISSING\x10\x02B\xcb\x01\n" +
	"\x16com.chatto.core.evt.v1B\x10AssetEventsProtoP\x01Z4hmans.de/chatto/internal/pb/chatto/core/evt/v1;evtv1\xa2\x02\x03CCE\xaa\x02\x12Chatto.Core.Evt.V1\xca\x02\x12Chatto\\Core\\Evt\\V1\xe2\x02\x1eChatto\\Core\\Evt\\V1\\GPBMetadata\xea\x02\x15Chatto::Core::Evt::V1b\x06proto3"

var (
	file_chatto_core_evt_v1_asset_events_proto_rawDescOnce sync.Once
	file_chatto_core_evt_v1_asset_events_proto_rawDescData []byte
)

func file_chatto_core_evt_v1_asset_events_proto_rawDescGZIP() []byte {
	file_chatto_core_evt_v1_asset_events_proto_rawDescOnce.Do(func() {
		file_chatto_core_evt_v1_asset_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_core_evt_v1_asset_events_proto_rawDesc), len(file_chatto_core_evt_v1_asset_events_proto_rawDesc)))
	})
	return file_chatto_core_evt_v1_asset_events_proto_rawDescData
}

var file_chatto_core_evt_v1_asset_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chatto_core_evt_v1_asset_events_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_chatto_core_evt_v1_asset_events_proto_goTypes = []any{
	(AssetDerivativeRole)(0),              // 0: chatto.core.evt.v1.AssetDerivativeRole
	(AssetProcessingFailureCode)(0),       // 1: chatto.core.evt.v1.AssetProcessingFailureCode
	(*AssetCreatedEvent)(nil),             // 2: chatto.core.evt.v1.AssetCreatedEvent
	(*AssetDeletedEvent)(nil),             // 3: chatto.core.evt.v1.AssetDeletedEvent
	(*AssetAttachedEvent)(nil),            // 4: chatto.core.evt.v1.AssetAttachedEvent
	(*AssetBurnState)(nil),                // 5: chatto.core.evt.v1.AssetBurnState
	(*AssetBurnView)(nil),                 // 6: chatto.core.evt.v1.AssetBurnView
	(*AssetBurnUpdatedEvent)(nil),         // 7: chatto.core.evt.v1.AssetBurnUpdatedEvent
	(*AssetProcessingStartedEvent)(nil),   // 8: chatto.core.evt.v1.AssetProcessingStartedEvent
	(*AssetProcessingSucceededEvent)(nil), // 9: chatto.core.evt.v1.AssetProcessingSucceededEvent
	(*AssetProcessingFailedEvent)(nil),    // 10: chatto.core.evt.v1.AssetProcessingFailedEvent
	(*AssetProcessedVideo)(nil),           // 11: chatto.core.evt.v1.AssetProcessedVideo
	(*AssetVideoVariant)(nil),             // 12: chatto.core.evt.v1.AssetVideoVariant
	(*AssetProcessedHLS)(nil),             // 13: chatto.core.evt.v1.AssetProcessedHLS
	(*AssetHLSRendition)(nil),             // 14: chatto.core.evt.v1.AssetHLSRendition
	(*AssetHLSSegment)(nil),               // 15: chatto.core.evt.v1.AssetHLSSegment
	(*AssetRecord)(nil),                   // 16: chatto.core.evt.v1.AssetRecord
	(*timestamppb.Timestamp)(nil),         // 17: google.protobuf.Timestamp
}
var file_chatto_core_evt_v1_asset_events_proto_depIdxs = []int32{
	16, // 0: chatto.core.evt.v1.AssetCreatedEvent.asset:type_name -> chatto.core.evt.v1.AssetRecord
	0,  // 1: chatto.core.evt.v1.AssetCreatedEvent.derivative_role:type_name -> chatto.core.evt.v1.AssetDerivativeRole
	17, // 2: chatto.core.evt.v1.AssetCreatedEvent.pending_expires_at:type_name -> google.protobuf.Timestamp
	5,  // 3: chatto.core.evt.v1.AssetAttachedEvent.burn:type_name -> chatto.core.evt.v1.AssetBurnState
	17, // 4: chatto.core.evt.v1.AssetBurnState.unopened_expires_at:type_name -> google.protobuf.Timestamp
	6,  // 5: chatto.core.evt.v1.AssetBurnState.views:type_name -> chatto.core.evt.v1.AssetBurnView
	17, // 6: chatto.core.evt.v1.AssetBurnState.undo_expires_at:type_name -> google.protobuf.Timestamp
	17, // 7: chatto.core.evt.v1.AssetBurnView.expires_at:type_name -> google.protobuf.Timestamp
	17, // 8: chatto.core.evt.v1.AssetBurnView.closed_at:type_name -> google.protobuf.Timestamp
	5,  // 9: chatto.core.evt.v1.AssetBurnUpdatedEvent.state:type_name -> chatto.core.evt.v1.AssetBurnState
	11, // 10: chatto.core.evt.v1.AssetProcessingSucceededEvent.video:type_name -> chatto.core.evt.v1.AssetProcessedVideo
	1,  // 11: chatto.core.evt.v1.AssetProcessingFailedEvent.failure_code:type_name -> chatto.core.evt.v1.AssetProcessingFailureCode
	12, // 12: chatto.core.evt.v1.AssetProcessedVideo.variants:type_name -> chatto.core.evt.v1.AssetVideoVariant
	13, // 13: chatto.core.evt.v1.AssetProcessedVideo.hls:type_name -> chatto.core.evt.v1.AssetProcessedHLS
	14, // 14: chatto.core.evt.v1.AssetProcessedHLS.renditions:type_name -> chatto.core.evt.v1.AssetHLSRendition
	15, // 15: chatto.core.evt.v1.AssetHLSRendition.segments:type_name -> chatto.core.evt.v1.AssetHLSSegment
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_chatto_core_evt_v1_asset_events_proto_init() }
func file_chatto_core_evt_v1_asset_events_proto_init() {
	if File_chatto_core_evt_v1_asset_events_proto != nil {
		return
	}
	file_chatto_core_evt_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_core_evt_v1_asset_events_proto_rawDesc), len(file_chatto_core_evt_v1_asset_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_core_evt_v1_asset_events_proto_goTypes,
		DependencyIndexes: file_chatto_core_evt_v1_asset_events_proto_depIdxs,
		EnumInfos:         file_chatto_core_evt_v1_asset_events_proto_enumTypes,
		MessageInfos:      file_chatto_core_evt_v1_asset_events_proto_msgTypes,
	}.Build()
	File_chatto_core_evt_v1_asset_events_proto = out.File
	file_chatto_core_evt_v1_asset_events_proto_goTypes = nil
	file_chatto_core_evt_v1_asset_events_proto_depIdxs = nil
}
