// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/api/v1/account.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hmans.de/chatto/internal/pb/chatto/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MyAccountServiceName is the fully-qualified name of the MyAccountService service.
	MyAccountServiceName = "chatto.api.v1.MyAccountService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MyAccountServiceChangePasswordProcedure is the fully-qualified name of the MyAccountService's
	// ChangePassword RPC.
	MyAccountServiceChangePasswordProcedure = "/chatto.api.v1.MyAccountService/ChangePassword"
	// MyAccountServiceListVerifiedEmailsProcedure is the fully-qualified name of the MyAccountService's
	// ListVerifiedEmails RPC.
	MyAccountServiceListVerifiedEmailsProcedure = "/chatto.api.v1.MyAccountService/ListVerifiedEmails"
	// MyAccountServiceRequestEmailVerificationProcedure is the fully-qualified name of the
	// MyAccountService's RequestEmailVerification RPC.
	MyAccountServiceRequestEmailVerificationProcedure = "/chatto.api.v1.MyAccountService/RequestEmailVerification"
	// MyAccountServiceConfirmEmailVerificationProcedure is the fully-qualified name of the
	// MyAccountService's ConfirmEmailVerification RPC.
	MyAccountServiceConfirmEmailVerificationProcedure = "/chatto.api.v1.MyAccountService/ConfirmEmailVerification"
	// MyAccountServiceSetPrimaryEmailProcedure is the fully-qualified name of the MyAccountService's
	// SetPrimaryEmail RPC.
	MyAccountServiceSetPrimaryEmailProcedure = "/chatto.api.v1.MyAccountService/SetPrimaryEmail"
	// MyAccountServiceGetSettingsProcedure is the fully-qualified name of the MyAccountService's
	// GetSettings RPC.
	MyAccountServiceGetSettingsProcedure = "/chatto.api.v1.MyAccountService/GetSettings"
	// MyAccountServiceUpdateSettingsProcedure is the fully-qualified name of the MyAccountService's
	// UpdateSettings RPC.
	MyAccountServiceUpdateSettingsProcedure = "/chatto.api.v1.MyAccountService/UpdateSettings"
	// MyAccountServiceSetDMVisibilityProcedure is the fully-qualified name of the MyAccountService's
	// SetDMVisibility RPC.
	MyAccountServiceSetDMVisibilityProcedure = "/chatto.api.v1.MyAccountService/SetDMVisibility"
	// MyAccountServiceListExternalIdentitiesProcedure is the fully-qualified name of the
	// MyAccountService's ListExternalIdentities RPC.
	MyAccountServiceListExternalIdentitiesProcedure = "/chatto.api.v1.MyAccountService/ListExternalIdentities"
	// MyAccountServiceStartExternalIdentityLinkProcedure is the fully-qualified name of the
	// MyAccountService's StartExternalIdentityLink RPC.
	MyAccountServiceStartExternalIdentityLinkProcedure = "/chatto.api.v1.MyAccountService/StartExternalIdentityLink"
	// MyAccountServiceDisconnectExternalIdentityProcedure is the fully-qualified name of the
	// MyAccountService's DisconnectExternalIdentity RPC.
	MyAccountServiceDisconnectExternalIdentityProcedure = "/chatto.api.v1.MyAccountService/DisconnectExternalIdentity"
	// MyAccountServiceSetPresenceProcedure is the fully-qualified name of the MyAccountService's
	// SetPresence RPC.
	MyAccountServiceSetPresenceProcedure = "/chatto.api.v1.MyAccountService/SetPresence"
	// MyAccountServiceGetPresencePreferenceProcedure is the fully-qualified name of the
	// MyAccountService's GetPresencePreference RPC.
	MyAccountServiceGetPresencePreferenceProcedure = "/chatto.api.v1.MyAccountService/GetPresencePreference"
	// MyAccountServiceSetPresencePreferenceProcedure is the fully-qualified name of the
	// MyAccountService's SetPresencePreference RPC.
	MyAccountServiceSetPresencePreferenceProcedure = "/chatto.api.v1.MyAccountService/SetPresencePreference"
	// MyAccountServiceRefreshPresenceProcedure is the fully-qualified name of the MyAccountService's
	// RefreshPresence RPC.
	MyAccountServiceRefreshPresenceProcedure = "/chatto.api.v1.MyAccountService/RefreshPresence"
	// MyAccountServiceSetCustomStatusProcedure is the fully-qualified name of the MyAccountService's
	// SetCustomStatus RPC.
	MyAccountServiceSetCustomStatusProcedure = "/chatto.api.v1.MyAccountService/SetCustomStatus"
	// MyAccountServiceDeleteCustomStatusProcedure is the fully-qualified name of the MyAccountService's
	// DeleteCustomStatus RPC.
	MyAccountServiceDeleteCustomStatusProcedure = "/chatto.api.v1.MyAccountService/DeleteCustomStatus"
	// MyAccountServiceRequestAccountDeletionProcedure is the fully-qualified name of the
	// MyAccountService's RequestAccountDeletion RPC.
	MyAccountServiceRequestAccountDeletionProcedure = "/chatto.api.v1.MyAccountService/RequestAccountDeletion"
	// MyAccountServiceDeleteMyAccountProcedure is the fully-qualified name of the MyAccountService's
	// DeleteMyAccount RPC.
	MyAccountServiceDeleteMyAccountProcedure = "/chatto.api.v1.MyAccountService/DeleteMyAccount"
)

// MyAccountServiceClient is a client for the chatto.api.v1.MyAccountService service.
type MyAccountServiceClient interface {
	// Updates or adds the authenticated user's password.
	ChangePassword(context.Context, *connect.Request[v1.ChangePasswordRequest]) (*connect.Response[v1.ChangePasswordResponse], error)
	// Lists the authenticated user's verified email addresses and primary choice.
	// Returns FAILED_PRECONDITION when the authenticated account does not match
	// expected_user_id.
	ListVerifiedEmails(context.Context, *connect.Request[v1.ListVerifiedEmailsRequest]) (*connect.Response[v1.ListVerifiedEmailsResponse], error)
	// Sends a six-digit code to an email address that the authenticated user
	// wants to add. The code expires after the server-configured email OTP
	// lifetime. The client can request a new code after expiry. The server must
	// have transactional email enabled. Returns ALREADY_EXISTS when the address
	// is already verified for the user, RESOURCE_EXHAUSTED after too many code
	// requests or attempts, and UNAVAILABLE when email delivery is disabled or
	// fails. Returns FAILED_PRECONDITION when the authenticated account does not
	// match expected_user_id.
	RequestEmailVerification(context.Context, *connect.Request[v1.RequestEmailVerificationRequest]) (*connect.Response[v1.RequestEmailVerificationResponse], error)
	// Confirms a verification code and adds the address to the account. Returns
	// INVALID_ARGUMENT when the code is invalid or expired, and ALREADY_EXISTS
	// when another user already controls the address. Returns FAILED_PRECONDITION
	// when the authenticated account does not match expected_user_id.
	ConfirmEmailVerification(context.Context, *connect.Request[v1.ConfirmEmailVerificationRequest]) (*connect.Response[v1.ConfirmEmailVerificationResponse], error)
	// Selects one verified address for future account-directed email. Returns
	// NOT_FOUND when the address is not verified for the authenticated user, and
	// FAILED_PRECONDITION when the authenticated account does not match
	// expected_user_id.
	SetPrimaryEmail(context.Context, *connect.Request[v1.SetPrimaryEmailRequest]) (*connect.Response[v1.SetPrimaryEmailResponse], error)
	// Reads the authenticated user's display preferences without changing them.
	// Returns default settings when none have been saved.
	GetSettings(context.Context, *connect.Request[v1.GetSettingsRequest]) (*connect.Response[v1.GetSettingsResponse], error)
	// Updates the authenticated user's display preferences.
	UpdateSettings(context.Context, *connect.Request[v1.UpdateSettingsRequest]) (*connect.Response[v1.UpdateSettingsResponse], error)
	// Sets one private DM visibility choice. Requires DM membership, including
	// conversations with deleted participants. Does not change membership,
	// history, or notifications. Other accounts cannot read this choice.
	// StartDM restores an existing conversation for the caller. Clients receive
	// ViewerPreferencesChanged and refetch GetViewer or GetSettings to synchronize.
	SetDMVisibility(context.Context, *connect.Request[v1.SetDMVisibilityRequest]) (*connect.Response[v1.SetDMVisibilityResponse], error)
	// Lists configured external identity providers and identities linked to the
	// authenticated account.
	ListExternalIdentities(context.Context, *connect.Request[v1.ListExternalIdentitiesRequest]) (*connect.Response[v1.ListExternalIdentitiesResponse], error)
	// Creates a short-lived browser handoff URL for linking a provider identity
	// to the authenticated account. The provider callback completes through
	// chatto.auth.v1.ExternalIdentityAuthService.ConfirmExternalIdentityLink.
	StartExternalIdentityLink(context.Context, *connect.Request[v1.StartExternalIdentityLinkRequest]) (*connect.Response[v1.StartExternalIdentityLinkResponse], error)
	// Disconnects a provider identity from the authenticated account.
	DisconnectExternalIdentity(context.Context, *connect.Request[v1.DisconnectExternalIdentityRequest]) (*connect.Response[v1.DisconnectExternalIdentityResponse], error)
	// Legacy live presence report, expiring after 60 seconds without refresh.
	// A saved private choice overrides this report, including user_selected.
	// New clients use SetPresencePreference for choices and RefreshPresence
	// every 30 seconds for liveness.
	SetPresence(context.Context, *connect.Request[v1.SetPresenceRequest]) (*connect.Response[v1.SetPresenceResponse], error)
	// Reads the authenticated account's private saved availability choice.
	GetPresencePreference(context.Context, *connect.Request[v1.GetPresencePreferenceRequest]) (*connect.Response[v1.GetPresencePreferenceResponse], error)
	// Saves a choice for all devices on this server. A stale revision returns ABORTED.
	// OFFLINE suppresses public presence and typing; the choice survives disconnects.
	SetPresencePreference(context.Context, *connect.Request[v1.SetPresencePreferenceRequest]) (*connect.Response[v1.SetPresencePreferenceResponse], error)
	// Refreshes connection liveness without changing the saved choice. Clients call
	// every 30 seconds; liveness expires after 60 seconds without a refresh.
	// Accounts with a saved OFFLINE choice may refresh without public presence signals.
	RefreshPresence(context.Context, *connect.Request[v1.RefreshPresenceRequest]) (*connect.Response[v1.RefreshPresenceResponse], error)
	// Sets the current user's complete custom status. Emoji and text are required.
	// Omit expires_at for no expiry, or supply a future time.
	SetCustomStatus(context.Context, *connect.Request[v1.SetCustomStatusRequest]) (*connect.Response[v1.SetCustomStatusResponse], error)
	// Deletes the current user's custom status. The call is idempotent and returns
	// the resulting empty status state.
	DeleteCustomStatus(context.Context, *connect.Request[v1.DeleteCustomStatusRequest]) (*connect.Response[v1.DeleteCustomStatusResponse], error)
	// Issues a short-lived token used to confirm self-deletion. Requires
	// user.delete-self.
	RequestAccountDeletion(context.Context, *connect.Request[v1.RequestAccountDeletionRequest]) (*connect.Response[v1.RequestAccountDeletionResponse], error)
	// Permanently deletes the authenticated account after token validation.
	// Requires user.delete-self.
	DeleteMyAccount(context.Context, *connect.Request[v1.DeleteMyAccountRequest]) (*connect.Response[v1.DeleteMyAccountResponse], error)
}

// NewMyAccountServiceClient constructs a client for the chatto.api.v1.MyAccountService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMyAccountServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MyAccountServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	myAccountServiceMethods := v1.File_chatto_api_v1_account_proto.Services().ByName("MyAccountService").Methods()
	return &myAccountServiceClient{
		changePassword: connect.NewClient[v1.ChangePasswordRequest, v1.ChangePasswordResponse](
			httpClient,
			baseURL+MyAccountServiceChangePasswordProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("ChangePassword")),
			connect.WithClientOptions(opts...),
		),
		listVerifiedEmails: connect.NewClient[v1.ListVerifiedEmailsRequest, v1.ListVerifiedEmailsResponse](
			httpClient,
			baseURL+MyAccountServiceListVerifiedEmailsProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("ListVerifiedEmails")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		requestEmailVerification: connect.NewClient[v1.RequestEmailVerificationRequest, v1.RequestEmailVerificationResponse](
			httpClient,
			baseURL+MyAccountServiceRequestEmailVerificationProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("RequestEmailVerification")),
			connect.WithClientOptions(opts...),
		),
		confirmEmailVerification: connect.NewClient[v1.ConfirmEmailVerificationRequest, v1.ConfirmEmailVerificationResponse](
			httpClient,
			baseURL+MyAccountServiceConfirmEmailVerificationProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("ConfirmEmailVerification")),
			connect.WithClientOptions(opts...),
		),
		setPrimaryEmail: connect.NewClient[v1.SetPrimaryEmailRequest, v1.SetPrimaryEmailResponse](
			httpClient,
			baseURL+MyAccountServiceSetPrimaryEmailProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("SetPrimaryEmail")),
			connect.WithClientOptions(opts...),
		),
		getSettings: connect.NewClient[v1.GetSettingsRequest, v1.GetSettingsResponse](
			httpClient,
			baseURL+MyAccountServiceGetSettingsProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("GetSettings")),
			connect.WithClientOptions(opts...),
		),
		updateSettings: connect.NewClient[v1.UpdateSettingsRequest, v1.UpdateSettingsResponse](
			httpClient,
			baseURL+MyAccountServiceUpdateSettingsProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("UpdateSettings")),
			connect.WithClientOptions(opts...),
		),
		setDMVisibility: connect.NewClient[v1.SetDMVisibilityRequest, v1.SetDMVisibilityResponse](
			httpClient,
			baseURL+MyAccountServiceSetDMVisibilityProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("SetDMVisibility")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		listExternalIdentities: connect.NewClient[v1.ListExternalIdentitiesRequest, v1.ListExternalIdentitiesResponse](
			httpClient,
			baseURL+MyAccountServiceListExternalIdentitiesProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("ListExternalIdentities")),
			connect.WithClientOptions(opts...),
		),
		startExternalIdentityLink: connect.NewClient[v1.StartExternalIdentityLinkRequest, v1.StartExternalIdentityLinkResponse](
			httpClient,
			baseURL+MyAccountServiceStartExternalIdentityLinkProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("StartExternalIdentityLink")),
			connect.WithClientOptions(opts...),
		),
		disconnectExternalIdentity: connect.NewClient[v1.DisconnectExternalIdentityRequest, v1.DisconnectExternalIdentityResponse](
			httpClient,
			baseURL+MyAccountServiceDisconnectExternalIdentityProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("DisconnectExternalIdentity")),
			connect.WithClientOptions(opts...),
		),
		setPresence: connect.NewClient[v1.SetPresenceRequest, v1.SetPresenceResponse](
			httpClient,
			baseURL+MyAccountServiceSetPresenceProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("SetPresence")),
			connect.WithClientOptions(opts...),
		),
		getPresencePreference: connect.NewClient[v1.GetPresencePreferenceRequest, v1.GetPresencePreferenceResponse](
			httpClient,
			baseURL+MyAccountServiceGetPresencePreferenceProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("GetPresencePreference")),
			connect.WithClientOptions(opts...),
		),
		setPresencePreference: connect.NewClient[v1.SetPresencePreferenceRequest, v1.SetPresencePreferenceResponse](
			httpClient,
			baseURL+MyAccountServiceSetPresencePreferenceProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("SetPresencePreference")),
			connect.WithClientOptions(opts...),
		),
		refreshPresence: connect.NewClient[v1.RefreshPresenceRequest, v1.RefreshPresenceResponse](
			httpClient,
			baseURL+MyAccountServiceRefreshPresenceProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("RefreshPresence")),
			connect.WithClientOptions(opts...),
		),
		setCustomStatus: connect.NewClient[v1.SetCustomStatusRequest, v1.SetCustomStatusResponse](
			httpClient,
			baseURL+MyAccountServiceSetCustomStatusProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("SetCustomStatus")),
			connect.WithClientOptions(opts...),
		),
		deleteCustomStatus: connect.NewClient[v1.DeleteCustomStatusRequest, v1.DeleteCustomStatusResponse](
			httpClient,
			baseURL+MyAccountServiceDeleteCustomStatusProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("DeleteCustomStatus")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		requestAccountDeletion: connect.NewClient[v1.RequestAccountDeletionRequest, v1.RequestAccountDeletionResponse](
			httpClient,
			baseURL+MyAccountServiceRequestAccountDeletionProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("RequestAccountDeletion")),
			connect.WithClientOptions(opts...),
		),
		deleteMyAccount: connect.NewClient[v1.DeleteMyAccountRequest, v1.DeleteMyAccountResponse](
			httpClient,
			baseURL+MyAccountServiceDeleteMyAccountProcedure,
			connect.WithSchema(myAccountServiceMethods.ByName("DeleteMyAccount")),
			connect.WithClientOptions(opts...),
		),
	}
}

// myAccountServiceClient implements MyAccountServiceClient.
type myAccountServiceClient struct {
	changePassword             *connect.Client[v1.ChangePasswordRequest, v1.ChangePasswordResponse]
	listVerifiedEmails         *connect.Client[v1.ListVerifiedEmailsRequest, v1.ListVerifiedEmailsResponse]
	requestEmailVerification   *connect.Client[v1.RequestEmailVerificationRequest, v1.RequestEmailVerificationResponse]
	confirmEmailVerification   *connect.Client[v1.ConfirmEmailVerificationRequest, v1.ConfirmEmailVerificationResponse]
	setPrimaryEmail            *connect.Client[v1.SetPrimaryEmailRequest, v1.SetPrimaryEmailResponse]
	getSettings                *connect.Client[v1.GetSettingsRequest, v1.GetSettingsResponse]
	updateSettings             *connect.Client[v1.UpdateSettingsRequest, v1.UpdateSettingsResponse]
	setDMVisibility            *connect.Client[v1.SetDMVisibilityRequest, v1.SetDMVisibilityResponse]
	listExternalIdentities     *connect.Client[v1.ListExternalIdentitiesRequest, v1.ListExternalIdentitiesResponse]
	startExternalIdentityLink  *connect.Client[v1.StartExternalIdentityLinkRequest, v1.StartExternalIdentityLinkResponse]
	disconnectExternalIdentity *connect.Client[v1.DisconnectExternalIdentityRequest, v1.DisconnectExternalIdentityResponse]
	setPresence                *connect.Client[v1.SetPresenceRequest, v1.SetPresenceResponse]
	getPresencePreference      *connect.Client[v1.GetPresencePreferenceRequest, v1.GetPresencePreferenceResponse]
	setPresencePreference      *connect.Client[v1.SetPresencePreferenceRequest, v1.SetPresencePreferenceResponse]
	refreshPresence            *connect.Client[v1.RefreshPresenceRequest, v1.RefreshPresenceResponse]
	setCustomStatus            *connect.Client[v1.SetCustomStatusRequest, v1.SetCustomStatusResponse]
	deleteCustomStatus         *connect.Client[v1.DeleteCustomStatusRequest, v1.DeleteCustomStatusResponse]
	requestAccountDeletion     *connect.Client[v1.RequestAccountDeletionRequest, v1.RequestAccountDeletionResponse]
	deleteMyAccount            *connect.Client[v1.DeleteMyAccountRequest, v1.DeleteMyAccountResponse]
}

// ChangePassword calls chatto.api.v1.MyAccountService.ChangePassword.
func (c *myAccountServiceClient) ChangePassword(ctx context.Context, req *connect.Request[v1.ChangePasswordRequest]) (*connect.Response[v1.ChangePasswordResponse], error) {
	return c.changePassword.CallUnary(ctx, req)
}

// ListVerifiedEmails calls chatto.api.v1.MyAccountService.ListVerifiedEmails.
func (c *myAccountServiceClient) ListVerifiedEmails(ctx context.Context, req *connect.Request[v1.ListVerifiedEmailsRequest]) (*connect.Response[v1.ListVerifiedEmailsResponse], error) {
	return c.listVerifiedEmails.CallUnary(ctx, req)
}

// RequestEmailVerification calls chatto.api.v1.MyAccountService.RequestEmailVerification.
func (c *myAccountServiceClient) RequestEmailVerification(ctx context.Context, req *connect.Request[v1.RequestEmailVerificationRequest]) (*connect.Response[v1.RequestEmailVerificationResponse], error) {
	return c.requestEmailVerification.CallUnary(ctx, req)
}

// ConfirmEmailVerification calls chatto.api.v1.MyAccountService.ConfirmEmailVerification.
func (c *myAccountServiceClient) ConfirmEmailVerification(ctx context.Context, req *connect.Request[v1.ConfirmEmailVerificationRequest]) (*connect.Response[v1.ConfirmEmailVerificationResponse], error) {
	return c.confirmEmailVerification.CallUnary(ctx, req)
}

// SetPrimaryEmail calls chatto.api.v1.MyAccountService.SetPrimaryEmail.
func (c *myAccountServiceClient) SetPrimaryEmail(ctx context.Context, req *connect.Request[v1.SetPrimaryEmailRequest]) (*connect.Response[v1.SetPrimaryEmailResponse], error) {
	return c.setPrimaryEmail.CallUnary(ctx, req)
}

// GetSettings calls chatto.api.v1.MyAccountService.GetSettings.
func (c *myAccountServiceClient) GetSettings(ctx context.Context, req *connect.Request[v1.GetSettingsRequest]) (*connect.Response[v1.GetSettingsResponse], error) {
	return c.getSettings.CallUnary(ctx, req)
}

// UpdateSettings calls chatto.api.v1.MyAccountService.UpdateSettings.
func (c *myAccountServiceClient) UpdateSettings(ctx context.Context, req *connect.Request[v1.UpdateSettingsRequest]) (*connect.Response[v1.UpdateSettingsResponse], error) {
	return c.updateSettings.CallUnary(ctx, req)
}

// SetDMVisibility calls chatto.api.v1.MyAccountService.SetDMVisibility.
func (c *myAccountServiceClient) SetDMVisibility(ctx context.Context, req *connect.Request[v1.SetDMVisibilityRequest]) (*connect.Response[v1.SetDMVisibilityResponse], error) {
	return c.setDMVisibility.CallUnary(ctx, req)
}

// ListExternalIdentities calls chatto.api.v1.MyAccountService.ListExternalIdentities.
func (c *myAccountServiceClient) ListExternalIdentities(ctx context.Context, req *connect.Request[v1.ListExternalIdentitiesRequest]) (*connect.Response[v1.ListExternalIdentitiesResponse], error) {
	return c.listExternalIdentities.CallUnary(ctx, req)
}

// StartExternalIdentityLink calls chatto.api.v1.MyAccountService.StartExternalIdentityLink.
func (c *myAccountServiceClient) StartExternalIdentityLink(ctx context.Context, req *connect.Request[v1.StartExternalIdentityLinkRequest]) (*connect.Response[v1.StartExternalIdentityLinkResponse], error) {
	return c.startExternalIdentityLink.CallUnary(ctx, req)
}

// DisconnectExternalIdentity calls chatto.api.v1.MyAccountService.DisconnectExternalIdentity.
func (c *myAccountServiceClient) DisconnectExternalIdentity(ctx context.Context, req *connect.Request[v1.DisconnectExternalIdentityRequest]) (*connect.Response[v1.DisconnectExternalIdentityResponse], error) {
	return c.disconnectExternalIdentity.CallUnary(ctx, req)
}

// SetPresence calls chatto.api.v1.MyAccountService.SetPresence.
func (c *myAccountServiceClient) SetPresence(ctx context.Context, req *connect.Request[v1.SetPresenceRequest]) (*connect.Response[v1.SetPresenceResponse], error) {
	return c.setPresence.CallUnary(ctx, req)
}

// GetPresencePreference calls chatto.api.v1.MyAccountService.GetPresencePreference.
func (c *myAccountServiceClient) GetPresencePreference(ctx context.Context, req *connect.Request[v1.GetPresencePreferenceRequest]) (*connect.Response[v1.GetPresencePreferenceResponse], error) {
	return c.getPresencePreference.CallUnary(ctx, req)
}

// SetPresencePreference calls chatto.api.v1.MyAccountService.SetPresencePreference.
func (c *myAccountServiceClient) SetPresencePreference(ctx context.Context, req *connect.Request[v1.SetPresencePreferenceRequest]) (*connect.Response[v1.SetPresencePreferenceResponse], error) {
	return c.setPresencePreference.CallUnary(ctx, req)
}

// RefreshPresence calls chatto.api.v1.MyAccountService.RefreshPresence.
func (c *myAccountServiceClient) RefreshPresence(ctx context.Context, req *connect.Request[v1.RefreshPresenceRequest]) (*connect.Response[v1.RefreshPresenceResponse], error) {
	return c.refreshPresence.CallUnary(ctx, req)
}

// SetCustomStatus calls chatto.api.v1.MyAccountService.SetCustomStatus.
func (c *myAccountServiceClient) SetCustomStatus(ctx context.Context, req *connect.Request[v1.SetCustomStatusRequest]) (*connect.Response[v1.SetCustomStatusResponse], error) {
	return c.setCustomStatus.CallUnary(ctx, req)
}

// DeleteCustomStatus calls chatto.api.v1.MyAccountService.DeleteCustomStatus.
func (c *myAccountServiceClient) DeleteCustomStatus(ctx context.Context, req *connect.Request[v1.DeleteCustomStatusRequest]) (*connect.Response[v1.DeleteCustomStatusResponse], error) {
	return c.deleteCustomStatus.CallUnary(ctx, req)
}

// RequestAccountDeletion calls chatto.api.v1.MyAccountService.RequestAccountDeletion.
func (c *myAccountServiceClient) RequestAccountDeletion(ctx context.Context, req *connect.Request[v1.RequestAccountDeletionRequest]) (*connect.Response[v1.RequestAccountDeletionResponse], error) {
	return c.requestAccountDeletion.CallUnary(ctx, req)
}

// DeleteMyAccount calls chatto.api.v1.MyAccountService.DeleteMyAccount.
func (c *myAccountServiceClient) DeleteMyAccount(ctx context.Context, req *connect.Request[v1.DeleteMyAccountRequest]) (*connect.Response[v1.DeleteMyAccountResponse], error) {
	return c.deleteMyAccount.CallUnary(ctx, req)
}

// MyAccountServiceHandler is an implementation of the chatto.api.v1.MyAccountService service.
type MyAccountServiceHandler interface {
	// Updates or adds the authenticated user's password.
	ChangePassword(context.Context, *connect.Request[v1.ChangePasswordRequest]) (*connect.Response[v1.ChangePasswordResponse], error)
	// Lists the authenticated user's verified email addresses and primary choice.
	// Returns FAILED_PRECONDITION when the authenticated account does not match
	// expected_user_id.
	ListVerifiedEmails(context.Context, *connect.Request[v1.ListVerifiedEmailsRequest]) (*connect.Response[v1.ListVerifiedEmailsResponse], error)
	// Sends a six-digit code to an email address that the authenticated user
	// wants to add. The code expires after the server-configured email OTP
	// lifetime. The client can request a new code after expiry. The server must
	// have transactional email enabled. Returns ALREADY_EXISTS when the address
	// is already verified for the user, RESOURCE_EXHAUSTED after too many code
	// requests or attempts, and UNAVAILABLE when email delivery is disabled or
	// fails. Returns FAILED_PRECONDITION when the authenticated account does not
	// match expected_user_id.
	RequestEmailVerification(context.Context, *connect.Request[v1.RequestEmailVerificationRequest]) (*connect.Response[v1.RequestEmailVerificationResponse], error)
	// Confirms a verification code and adds the address to the account. Returns
	// INVALID_ARGUMENT when the code is invalid or expired, and ALREADY_EXISTS
	// when another user already controls the address. Returns FAILED_PRECONDITION
	// when the authenticated account does not match expected_user_id.
	ConfirmEmailVerification(context.Context, *connect.Request[v1.ConfirmEmailVerificationRequest]) (*connect.Response[v1.ConfirmEmailVerificationResponse], error)
	// Selects one verified address for future account-directed email. Returns
	// NOT_FOUND when the address is not verified for the authenticated user, and
	// FAILED_PRECONDITION when the authenticated account does not match
	// expected_user_id.
	SetPrimaryEmail(context.Context, *connect.Request[v1.SetPrimaryEmailRequest]) (*connect.Response[v1.SetPrimaryEmailResponse], error)
	// Reads the authenticated user's display preferences without changing them.
	// Returns default settings when none have been saved.
	GetSettings(context.Context, *connect.Request[v1.GetSettingsRequest]) (*connect.Response[v1.GetSettingsResponse], error)
	// Updates the authenticated user's display preferences.
	UpdateSettings(context.Context, *connect.Request[v1.UpdateSettingsRequest]) (*connect.Response[v1.UpdateSettingsResponse], error)
	// Sets one private DM visibility choice. Requires DM membership, including
	// conversations with deleted participants. Does not change membership,
	// history, or notifications. Other accounts cannot read this choice.
	// StartDM restores an existing conversation for the caller. Clients receive
	// ViewerPreferencesChanged and refetch GetViewer or GetSettings to synchronize.
	SetDMVisibility(context.Context, *connect.Request[v1.SetDMVisibilityRequest]) (*connect.Response[v1.SetDMVisibilityResponse], error)
	// Lists configured external identity providers and identities linked to the
	// authenticated account.
	ListExternalIdentities(context.Context, *connect.Request[v1.ListExternalIdentitiesRequest]) (*connect.Response[v1.ListExternalIdentitiesResponse], error)
	// Creates a short-lived browser handoff URL for linking a provider identity
	// to the authenticated account. The provider callback completes through
	// chatto.auth.v1.ExternalIdentityAuthService.ConfirmExternalIdentityLink.
	StartExternalIdentityLink(context.Context, *connect.Request[v1.StartExternalIdentityLinkRequest]) (*connect.Response[v1.StartExternalIdentityLinkResponse], error)
	// Disconnects a provider identity from the authenticated account.
	DisconnectExternalIdentity(context.Context, *connect.Request[v1.DisconnectExternalIdentityRequest]) (*connect.Response[v1.DisconnectExternalIdentityResponse], error)
	// Legacy live presence report, expiring after 60 seconds without refresh.
	// A saved private choice overrides this report, including user_selected.
	// New clients use SetPresencePreference for choices and RefreshPresence
	// every 30 seconds for liveness.
	SetPresence(context.Context, *connect.Request[v1.SetPresenceRequest]) (*connect.Response[v1.SetPresenceResponse], error)
	// Reads the authenticated account's private saved availability choice.
	GetPresencePreference(context.Context, *connect.Request[v1.GetPresencePreferenceRequest]) (*connect.Response[v1.GetPresencePreferenceResponse], error)
	// Saves a choice for all devices on this server. A stale revision returns ABORTED.
	// OFFLINE suppresses public presence and typing; the choice survives disconnects.
	SetPresencePreference(context.Context, *connect.Request[v1.SetPresencePreferenceRequest]) (*connect.Response[v1.SetPresencePreferenceResponse], error)
	// Refreshes connection liveness without changing the saved choice. Clients call
	// every 30 seconds; liveness expires after 60 seconds without a refresh.
	// Accounts with a saved OFFLINE choice may refresh without public presence signals.
	RefreshPresence(context.Context, *connect.Request[v1.RefreshPresenceRequest]) (*connect.Response[v1.RefreshPresenceResponse], error)
	// Sets the current user's complete custom status. Emoji and text are required.
	// Omit expires_at for no expiry, or supply a future time.
	SetCustomStatus(context.Context, *connect.Request[v1.SetCustomStatusRequest]) (*connect.Response[v1.SetCustomStatusResponse], error)
	// Deletes the current user's custom status. The call is idempotent and returns
	// the resulting empty status state.
	DeleteCustomStatus(context.Context, *connect.Request[v1.DeleteCustomStatusRequest]) (*connect.Response[v1.DeleteCustomStatusResponse], error)
	// Issues a short-lived token used to confirm self-deletion. Requires
	// user.delete-self.
	RequestAccountDeletion(context.Context, *connect.Request[v1.RequestAccountDeletionRequest]) (*connect.Response[v1.RequestAccountDeletionResponse], error)
	// Permanently deletes the authenticated account after token validation.
	// Requires user.delete-self.
	DeleteMyAccount(context.Context, *connect.Request[v1.DeleteMyAccountRequest]) (*connect.Response[v1.DeleteMyAccountResponse], error)
}

// NewMyAccountServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMyAccountServiceHandler(svc MyAccountServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	myAccountServiceMethods := v1.File_chatto_api_v1_account_proto.Services().ByName("MyAccountService").Methods()
	myAccountServiceChangePasswordHandler := connect.NewUnaryHandler(
		MyAccountServiceChangePasswordProcedure,
		svc.ChangePassword,
		connect.WithSchema(myAccountServiceMethods.ByName("ChangePassword")),
		connect.WithHandlerOptions(opts...),
	)
	myAccountServiceListVerifiedEmailsHandler := connect.NewUnaryHandler(
		MyAccountServiceListVerifiedEmailsProcedure,
		svc.ListVerifiedEmails,
		connect.WithSchema(myAccountServiceMethods.ByName("ListVerifiedEmails")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	myAccountServiceRequestEmailVerificationHandler := connect.NewUnaryHandler(
		MyAccountServiceRequestEmailVerificationProcedure,
		svc.RequestEmailVerification,
		connect.WithSchema(myAccountServiceMethods.ByName("RequestEmailVerification")),
		connect.WithHandlerOptions(opts...),
	)
	myAccountServiceConfirmEmailVerificationHandler := connect.NewUnaryHandler(
		MyAccountServiceConfirmEmailVerificationProcedure,
		svc.ConfirmEmailVerification,
		connect.WithSchema(myAccountServiceMethods.ByName("ConfirmEmailVerification")),
		connect.WithHandlerOptions(opts...),
	)
	myAccountServiceSetPrimaryEmailHandler := connect.NewUnaryHandler(
		MyAccountServiceSetPrimaryEmailProcedure,
		svc.SetPrimaryEmail,
		connect.WithSchema(myAccountServiceMethods.ByName("SetPrimaryEmail")),
		connect.WithHandlerOptions(opts...),
	)
	myAccountServiceGetSettingsHandler := connect.NewUnaryHandler(
		MyAccountServiceGetSettingsProcedure,
		svc.GetSettings,
		connect.WithSchema(myAccountServiceMethods.ByName("GetSettings")),
		connect.WithHandlerOptions(opts...),
	)
	myAccountServiceUpdateSettingsHandler := connect.NewUnaryHandler(
		MyAccountServiceUpdateSettingsProcedure,
		svc.UpdateSettings,
		connect.WithSchema(myAccountServiceMethods.ByName("UpdateSettings")),
		connect.WithHandlerOptions(opts...),
	)
	myAccountServiceSetDMVisibilityHandler := connect.NewUnaryHandler(
		MyAccountServiceSetDMVisibilityProcedure,
		svc.SetDMVisibility,
		connect.WithSchema(myAccountServiceMethods.ByName("SetDMVisibility")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	myAccountServiceListExternalIdentitiesHandler := connect.NewUnaryHandler(
		MyAccountServiceListExternalIdentitiesProcedure,
		svc.ListExternalIdentities,
		connect.WithSchema(myAccountServiceMethods.ByName("ListExternalIdentities")),
		connect.WithHandlerOptions(opts...),
	)
	myAccountServiceStartExternalIdentityLinkHandler := connect.NewUnaryHandler(
		MyAccountServiceStartExternalIdentityLinkProcedure,
		svc.StartExternalIdentityLink,
		connect.WithSchema(myAccountServiceMethods.ByName("StartExternalIdentityLink")),
		connect.WithHandlerOptions(opts...),
	)
	myAccountServiceDisconnectExternalIdentityHandler := connect.NewUnaryHandler(
		MyAccountServiceDisconnectExternalIdentityProcedure,
		svc.DisconnectExternalIdentity,
		connect.WithSchema(myAccountServiceMethods.ByName("DisconnectExternalIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	myAccountServiceSetPresenceHandler := connect.NewUnaryHandler(
		MyAccountServiceSetPresenceProcedure,
		svc.SetPresence,
		connect.WithSchema(myAccountServiceMethods.ByName("SetPresence")),
		connect.WithHandlerOptions(opts...),
	)
	myAccountServiceGetPresencePreferenceHandler := connect.NewUnaryHandler(
		MyAccountServiceGetPresencePreferenceProcedure,
		svc.GetPresencePreference,
		connect.WithSchema(myAccountServiceMethods.ByName("GetPresencePreference")),
		connect.WithHandlerOptions(opts...),
	)
	myAccountServiceSetPresencePreferenceHandler := connect.NewUnaryHandler(
		MyAccountServiceSetPresencePreferenceProcedure,
		svc.SetPresencePreference,
		connect.WithSchema(myAccountServiceMethods.ByName("SetPresencePreference")),
		connect.WithHandlerOptions(opts...),
	)
	myAccountServiceRefreshPresenceHandler := connect.NewUnaryHandler(
		MyAccountServiceRefreshPresenceProcedure,
		svc.RefreshPresence,
		connect.WithSchema(myAccountServiceMethods.ByName("RefreshPresence")),
		connect.WithHandlerOptions(opts...),
	)
	myAccountServiceSetCustomStatusHandler := connect.NewUnaryHandler(
		MyAccountServiceSetCustomStatusProcedure,
		svc.SetCustomStatus,
		connect.WithSchema(myAccountServiceMethods.ByName("SetCustomStatus")),
		connect.WithHandlerOptions(opts...),
	)
	myAccountServiceDeleteCustomStatusHandler := connect.NewUnaryHandler(
		MyAccountServiceDeleteCustomStatusProcedure,
		svc.DeleteCustomStatus,
		connect.WithSchema(myAccountServiceMethods.ByName("DeleteCustomStatus")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	myAccountServiceRequestAccountDeletionHandler := connect.NewUnaryHandler(
		MyAccountServiceRequestAccountDeletionProcedure,
		svc.RequestAccountDeletion,
		connect.WithSchema(myAccountServiceMethods.ByName("RequestAccountDeletion")),
		connect.WithHandlerOptions(opts...),
	)
	myAccountServiceDeleteMyAccountHandler := connect.NewUnaryHandler(
		MyAccountServiceDeleteMyAccountProcedure,
		svc.DeleteMyAccount,
		connect.WithSchema(myAccountServiceMethods.ByName("DeleteMyAccount")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.api.v1.MyAccountService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MyAccountServiceChangePasswordProcedure:
			myAccountServiceChangePasswordHandler.ServeHTTP(w, r)
		case MyAccountServiceListVerifiedEmailsProcedure:
			myAccountServiceListVerifiedEmailsHandler.ServeHTTP(w, r)
		case MyAccountServiceRequestEmailVerificationProcedure:
			myAccountServiceRequestEmailVerificationHandler.ServeHTTP(w, r)
		case MyAccountServiceConfirmEmailVerificationProcedure:
			myAccountServiceConfirmEmailVerificationHandler.ServeHTTP(w, r)
		case MyAccountServiceSetPrimaryEmailProcedure:
			myAccountServiceSetPrimaryEmailHandler.ServeHTTP(w, r)
		case MyAccountServiceGetSettingsProcedure:
			myAccountServiceGetSettingsHandler.ServeHTTP(w, r)
		case MyAccountServiceUpdateSettingsProcedure:
			myAccountServiceUpdateSettingsHandler.ServeHTTP(w, r)
		case MyAccountServiceSetDMVisibilityProcedure:
			myAccountServiceSetDMVisibilityHandler.ServeHTTP(w, r)
		case MyAccountServiceListExternalIdentitiesProcedure:
			myAccountServiceListExternalIdentitiesHandler.ServeHTTP(w, r)
		case MyAccountServiceStartExternalIdentityLinkProcedure:
			myAccountServiceStartExternalIdentityLinkHandler.ServeHTTP(w, r)
		case MyAccountServiceDisconnectExternalIdentityProcedure:
			myAccountServiceDisconnectExternalIdentityHandler.ServeHTTP(w, r)
		case MyAccountServiceSetPresenceProcedure:
			myAccountServiceSetPresenceHandler.ServeHTTP(w, r)
		case MyAccountServiceGetPresencePreferenceProcedure:
			myAccountServiceGetPresencePreferenceHandler.ServeHTTP(w, r)
		case MyAccountServiceSetPresencePreferenceProcedure:
			myAccountServiceSetPresencePreferenceHandler.ServeHTTP(w, r)
		case MyAccountServiceRefreshPresenceProcedure:
			myAccountServiceRefreshPresenceHandler.ServeHTTP(w, r)
		case MyAccountServiceSetCustomStatusProcedure:
			myAccountServiceSetCustomStatusHandler.ServeHTTP(w, r)
		case MyAccountServiceDeleteCustomStatusProcedure:
			myAccountServiceDeleteCustomStatusHandler.ServeHTTP(w, r)
		case MyAccountServiceRequestAccountDeletionProcedure:
			myAccountServiceRequestAccountDeletionHandler.ServeHTTP(w, r)
		case MyAccountServiceDeleteMyAccountProcedure:
			myAccountServiceDeleteMyAccountHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMyAccountServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMyAccountServiceHandler struct{}

func (UnimplementedMyAccountServiceHandler) ChangePassword(context.Context, *connect.Request[v1.ChangePasswordRequest]) (*connect.Response[v1.ChangePasswordResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.ChangePassword is not implemented"))
}

func (UnimplementedMyAccountServiceHandler) ListVerifiedEmails(context.Context, *connect.Request[v1.ListVerifiedEmailsRequest]) (*connect.Response[v1.ListVerifiedEmailsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.ListVerifiedEmails is not implemented"))
}

func (UnimplementedMyAccountServiceHandler) RequestEmailVerification(context.Context, *connect.Request[v1.RequestEmailVerificationRequest]) (*connect.Response[v1.RequestEmailVerificationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.RequestEmailVerification is not implemented"))
}

func (UnimplementedMyAccountServiceHandler) ConfirmEmailVerification(context.Context, *connect.Request[v1.ConfirmEmailVerificationRequest]) (*connect.Response[v1.ConfirmEmailVerificationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.ConfirmEmailVerification is not implemented"))
}

func (UnimplementedMyAccountServiceHandler) SetPrimaryEmail(context.Context, *connect.Request[v1.SetPrimaryEmailRequest]) (*connect.Response[v1.SetPrimaryEmailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.SetPrimaryEmail is not implemented"))
}

func (UnimplementedMyAccountServiceHandler) GetSettings(context.Context, *connect.Request[v1.GetSettingsRequest]) (*connect.Response[v1.GetSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.GetSettings is not implemented"))
}

func (UnimplementedMyAccountServiceHandler) UpdateSettings(context.Context, *connect.Request[v1.UpdateSettingsRequest]) (*connect.Response[v1.UpdateSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.UpdateSettings is not implemented"))
}

func (UnimplementedMyAccountServiceHandler) SetDMVisibility(context.Context, *connect.Request[v1.SetDMVisibilityRequest]) (*connect.Response[v1.SetDMVisibilityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.SetDMVisibility is not implemented"))
}

func (UnimplementedMyAccountServiceHandler) ListExternalIdentities(context.Context, *connect.Request[v1.ListExternalIdentitiesRequest]) (*connect.Response[v1.ListExternalIdentitiesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.ListExternalIdentities is not implemented"))
}

func (UnimplementedMyAccountServiceHandler) StartExternalIdentityLink(context.Context, *connect.Request[v1.StartExternalIdentityLinkRequest]) (*connect.Response[v1.StartExternalIdentityLinkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.StartExternalIdentityLink is not implemented"))
}

func (UnimplementedMyAccountServiceHandler) DisconnectExternalIdentity(context.Context, *connect.Request[v1.DisconnectExternalIdentityRequest]) (*connect.Response[v1.DisconnectExternalIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.DisconnectExternalIdentity is not implemented"))
}

func (UnimplementedMyAccountServiceHandler) SetPresence(context.Context, *connect.Request[v1.SetPresenceRequest]) (*connect.Response[v1.SetPresenceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.SetPresence is not implemented"))
}

func (UnimplementedMyAccountServiceHandler) GetPresencePreference(context.Context, *connect.Request[v1.GetPresencePreferenceRequest]) (*connect.Response[v1.GetPresencePreferenceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.GetPresencePreference is not implemented"))
}

func (UnimplementedMyAccountServiceHandler) SetPresencePreference(context.Context, *connect.Request[v1.SetPresencePreferenceRequest]) (*connect.Response[v1.SetPresencePreferenceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.SetPresencePreference is not implemented"))
}

func (UnimplementedMyAccountServiceHandler) RefreshPresence(context.Context, *connect.Request[v1.RefreshPresenceRequest]) (*connect.Response[v1.RefreshPresenceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.RefreshPresence is not implemented"))
}

func (UnimplementedMyAccountServiceHandler) SetCustomStatus(context.Context, *connect.Request[v1.SetCustomStatusRequest]) (*connect.Response[v1.SetCustomStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.SetCustomStatus is not implemented"))
}

func (UnimplementedMyAccountServiceHandler) DeleteCustomStatus(context.Context, *connect.Request[v1.DeleteCustomStatusRequest]) (*connect.Response[v1.DeleteCustomStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.DeleteCustomStatus is not implemented"))
}

func (UnimplementedMyAccountServiceHandler) RequestAccountDeletion(context.Context, *connect.Request[v1.RequestAccountDeletionRequest]) (*connect.Response[v1.RequestAccountDeletionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.RequestAccountDeletion is not implemented"))
}

func (UnimplementedMyAccountServiceHandler) DeleteMyAccount(context.Context, *connect.Request[v1.DeleteMyAccountRequest]) (*connect.Response[v1.DeleteMyAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MyAccountService.DeleteMyAccount is not implemented"))
}
