// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/api/v1/attachments.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hmans.de/chatto/internal/pb/chatto/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AssetServiceName is the fully-qualified name of the AssetService service.
	AssetServiceName = "chatto.api.v1.AssetService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AssetServiceOpenBurnAttachmentProcedure is the fully-qualified name of the AssetService's
	// OpenBurnAttachment RPC.
	AssetServiceOpenBurnAttachmentProcedure = "/chatto.api.v1.AssetService/OpenBurnAttachment"
	// AssetServiceCloseBurnAttachmentProcedure is the fully-qualified name of the AssetService's
	// CloseBurnAttachment RPC.
	AssetServiceCloseBurnAttachmentProcedure = "/chatto.api.v1.AssetService/CloseBurnAttachment"
	// AssetServiceRequestAttachmentPermanenceProcedure is the fully-qualified name of the
	// AssetService's RequestAttachmentPermanence RPC.
	AssetServiceRequestAttachmentPermanenceProcedure = "/chatto.api.v1.AssetService/RequestAttachmentPermanence"
	// AssetServiceMakeAttachmentPermanentProcedure is the fully-qualified name of the AssetService's
	// MakeAttachmentPermanent RPC.
	AssetServiceMakeAttachmentPermanentProcedure = "/chatto.api.v1.AssetService/MakeAttachmentPermanent"
	// AssetServiceUndoAttachmentPermanenceProcedure is the fully-qualified name of the AssetService's
	// UndoAttachmentPermanence RPC.
	AssetServiceUndoAttachmentPermanenceProcedure = "/chatto.api.v1.AssetService/UndoAttachmentPermanence"
	// AssetServiceGetAssetProcedure is the fully-qualified name of the AssetService's GetAsset RPC.
	AssetServiceGetAssetProcedure = "/chatto.api.v1.AssetService/GetAsset"
	// AssetServiceBatchGetAssetsProcedure is the fully-qualified name of the AssetService's
	// BatchGetAssets RPC.
	AssetServiceBatchGetAssetsProcedure = "/chatto.api.v1.AssetService/BatchGetAssets"
)

// AssetServiceClient is a client for the chatto.api.v1.AssetService service.
type AssetServiceClient interface {
	// Deliberately opens one session. Membership and current message-read access
	// are required. Audio uses its verified duration; video adds 10 seconds to
	// its verified duration to press Play. Other files use the configured limit.
	// Missing media duration returns failed_precondition without claiming a
	// session. Timers start on Open and continue during buffering or pauses.
	OpenBurnAttachment(context.Context, *connect.Request[v1.OpenBurnAttachmentRequest]) (*connect.Response[v1.OpenBurnAttachmentResponse], error)
	// End on viewer close, navigation, or privacy reset. A lost close is bounded
	// by the original session deadline; it does not create a new session.
	CloseBurnAttachment(context.Context, *connect.Request[v1.CloseBurnAttachmentRequest]) (*connect.Response[v1.CloseBurnAttachmentResponse], error)
	// Request or cancel normal access while the file is retained.
	RequestAttachmentPermanence(context.Context, *connect.Request[v1.RequestAttachmentPermanenceRequest]) (*connect.Response[v1.RequestAttachmentPermanenceResponse], error)
	// Sender-only conversion, including during the recovery window.
	MakeAttachmentPermanent(context.Context, *connect.Request[v1.MakeAttachmentPermanentRequest]) (*connect.Response[v1.MakeAttachmentPermanentResponse], error)
	// Sender-only undo during the returned deadline.
	UndoAttachmentPermanence(context.Context, *connect.Request[v1.UndoAttachmentPermanenceRequest]) (*connect.Response[v1.UndoAttachmentPermanenceResponse], error)
	// Reads one asset. Authentication and room membership are required.
	// Assets also require message.read or a matching thread relationship with
	// message.read-interactions. Returns NOT_FOUND when the asset is missing,
	// deleted, or owned by a
	// different room.
	GetAsset(context.Context, *connect.Request[v1.GetAssetRequest]) (*connect.Response[v1.GetAssetResponse], error)
	// Reads many assets in one room. Authentication and room membership are
	// required. Assets also require message.read or a matching thread
	// relationship with message.read-interactions. Missing, deleted, wrong-room, and inaccessible asset
	// IDs are omitted. Results preserve first-seen request order, and repeated
	// asset IDs are de-duplicated.
	BatchGetAssets(context.Context, *connect.Request[v1.BatchGetAssetsRequest]) (*connect.Response[v1.BatchGetAssetsResponse], error)
}

// NewAssetServiceClient constructs a client for the chatto.api.v1.AssetService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAssetServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AssetServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	assetServiceMethods := v1.File_chatto_api_v1_attachments_proto.Services().ByName("AssetService").Methods()
	return &assetServiceClient{
		openBurnAttachment: connect.NewClient[v1.OpenBurnAttachmentRequest, v1.OpenBurnAttachmentResponse](
			httpClient,
			baseURL+AssetServiceOpenBurnAttachmentProcedure,
			connect.WithSchema(assetServiceMethods.ByName("OpenBurnAttachment")),
			connect.WithClientOptions(opts...),
		),
		closeBurnAttachment: connect.NewClient[v1.CloseBurnAttachmentRequest, v1.CloseBurnAttachmentResponse](
			httpClient,
			baseURL+AssetServiceCloseBurnAttachmentProcedure,
			connect.WithSchema(assetServiceMethods.ByName("CloseBurnAttachment")),
			connect.WithClientOptions(opts...),
		),
		requestAttachmentPermanence: connect.NewClient[v1.RequestAttachmentPermanenceRequest, v1.RequestAttachmentPermanenceResponse](
			httpClient,
			baseURL+AssetServiceRequestAttachmentPermanenceProcedure,
			connect.WithSchema(assetServiceMethods.ByName("RequestAttachmentPermanence")),
			connect.WithClientOptions(opts...),
		),
		makeAttachmentPermanent: connect.NewClient[v1.MakeAttachmentPermanentRequest, v1.MakeAttachmentPermanentResponse](
			httpClient,
			baseURL+AssetServiceMakeAttachmentPermanentProcedure,
			connect.WithSchema(assetServiceMethods.ByName("MakeAttachmentPermanent")),
			connect.WithClientOptions(opts...),
		),
		undoAttachmentPermanence: connect.NewClient[v1.UndoAttachmentPermanenceRequest, v1.UndoAttachmentPermanenceResponse](
			httpClient,
			baseURL+AssetServiceUndoAttachmentPermanenceProcedure,
			connect.WithSchema(assetServiceMethods.ByName("UndoAttachmentPermanence")),
			connect.WithClientOptions(opts...),
		),
		getAsset: connect.NewClient[v1.GetAssetRequest, v1.GetAssetResponse](
			httpClient,
			baseURL+AssetServiceGetAssetProcedure,
			connect.WithSchema(assetServiceMethods.ByName("GetAsset")),
			connect.WithClientOptions(opts...),
		),
		batchGetAssets: connect.NewClient[v1.BatchGetAssetsRequest, v1.BatchGetAssetsResponse](
			httpClient,
			baseURL+AssetServiceBatchGetAssetsProcedure,
			connect.WithSchema(assetServiceMethods.ByName("BatchGetAssets")),
			connect.WithClientOptions(opts...),
		),
	}
}

// assetServiceClient implements AssetServiceClient.
type assetServiceClient struct {
	openBurnAttachment          *connect.Client[v1.OpenBurnAttachmentRequest, v1.OpenBurnAttachmentResponse]
	closeBurnAttachment         *connect.Client[v1.CloseBurnAttachmentRequest, v1.CloseBurnAttachmentResponse]
	requestAttachmentPermanence *connect.Client[v1.RequestAttachmentPermanenceRequest, v1.RequestAttachmentPermanenceResponse]
	makeAttachmentPermanent     *connect.Client[v1.MakeAttachmentPermanentRequest, v1.MakeAttachmentPermanentResponse]
	undoAttachmentPermanence    *connect.Client[v1.UndoAttachmentPermanenceRequest, v1.UndoAttachmentPermanenceResponse]
	getAsset                    *connect.Client[v1.GetAssetRequest, v1.GetAssetResponse]
	batchGetAssets              *connect.Client[v1.BatchGetAssetsRequest, v1.BatchGetAssetsResponse]
}

// OpenBurnAttachment calls chatto.api.v1.AssetService.OpenBurnAttachment.
func (c *assetServiceClient) OpenBurnAttachment(ctx context.Context, req *connect.Request[v1.OpenBurnAttachmentRequest]) (*connect.Response[v1.OpenBurnAttachmentResponse], error) {
	return c.openBurnAttachment.CallUnary(ctx, req)
}

// CloseBurnAttachment calls chatto.api.v1.AssetService.CloseBurnAttachment.
func (c *assetServiceClient) CloseBurnAttachment(ctx context.Context, req *connect.Request[v1.CloseBurnAttachmentRequest]) (*connect.Response[v1.CloseBurnAttachmentResponse], error) {
	return c.closeBurnAttachment.CallUnary(ctx, req)
}

// RequestAttachmentPermanence calls chatto.api.v1.AssetService.RequestAttachmentPermanence.
func (c *assetServiceClient) RequestAttachmentPermanence(ctx context.Context, req *connect.Request[v1.RequestAttachmentPermanenceRequest]) (*connect.Response[v1.RequestAttachmentPermanenceResponse], error) {
	return c.requestAttachmentPermanence.CallUnary(ctx, req)
}

// MakeAttachmentPermanent calls chatto.api.v1.AssetService.MakeAttachmentPermanent.
func (c *assetServiceClient) MakeAttachmentPermanent(ctx context.Context, req *connect.Request[v1.MakeAttachmentPermanentRequest]) (*connect.Response[v1.MakeAttachmentPermanentResponse], error) {
	return c.makeAttachmentPermanent.CallUnary(ctx, req)
}

// UndoAttachmentPermanence calls chatto.api.v1.AssetService.UndoAttachmentPermanence.
func (c *assetServiceClient) UndoAttachmentPermanence(ctx context.Context, req *connect.Request[v1.UndoAttachmentPermanenceRequest]) (*connect.Response[v1.UndoAttachmentPermanenceResponse], error) {
	return c.undoAttachmentPermanence.CallUnary(ctx, req)
}

// GetAsset calls chatto.api.v1.AssetService.GetAsset.
func (c *assetServiceClient) GetAsset(ctx context.Context, req *connect.Request[v1.GetAssetRequest]) (*connect.Response[v1.GetAssetResponse], error) {
	return c.getAsset.CallUnary(ctx, req)
}

// BatchGetAssets calls chatto.api.v1.AssetService.BatchGetAssets.
func (c *assetServiceClient) BatchGetAssets(ctx context.Context, req *connect.Request[v1.BatchGetAssetsRequest]) (*connect.Response[v1.BatchGetAssetsResponse], error) {
	return c.batchGetAssets.CallUnary(ctx, req)
}

// AssetServiceHandler is an implementation of the chatto.api.v1.AssetService service.
type AssetServiceHandler interface {
	// Deliberately opens one session. Membership and current message-read access
	// are required. Audio uses its verified duration; video adds 10 seconds to
	// its verified duration to press Play. Other files use the configured limit.
	// Missing media duration returns failed_precondition without claiming a
	// session. Timers start on Open and continue during buffering or pauses.
	OpenBurnAttachment(context.Context, *connect.Request[v1.OpenBurnAttachmentRequest]) (*connect.Response[v1.OpenBurnAttachmentResponse], error)
	// End on viewer close, navigation, or privacy reset. A lost close is bounded
	// by the original session deadline; it does not create a new session.
	CloseBurnAttachment(context.Context, *connect.Request[v1.CloseBurnAttachmentRequest]) (*connect.Response[v1.CloseBurnAttachmentResponse], error)
	// Request or cancel normal access while the file is retained.
	RequestAttachmentPermanence(context.Context, *connect.Request[v1.RequestAttachmentPermanenceRequest]) (*connect.Response[v1.RequestAttachmentPermanenceResponse], error)
	// Sender-only conversion, including during the recovery window.
	MakeAttachmentPermanent(context.Context, *connect.Request[v1.MakeAttachmentPermanentRequest]) (*connect.Response[v1.MakeAttachmentPermanentResponse], error)
	// Sender-only undo during the returned deadline.
	UndoAttachmentPermanence(context.Context, *connect.Request[v1.UndoAttachmentPermanenceRequest]) (*connect.Response[v1.UndoAttachmentPermanenceResponse], error)
	// Reads one asset. Authentication and room membership are required.
	// Assets also require message.read or a matching thread relationship with
	// message.read-interactions. Returns NOT_FOUND when the asset is missing,
	// deleted, or owned by a
	// different room.
	GetAsset(context.Context, *connect.Request[v1.GetAssetRequest]) (*connect.Response[v1.GetAssetResponse], error)
	// Reads many assets in one room. Authentication and room membership are
	// required. Assets also require message.read or a matching thread
	// relationship with message.read-interactions. Missing, deleted, wrong-room, and inaccessible asset
	// IDs are omitted. Results preserve first-seen request order, and repeated
	// asset IDs are de-duplicated.
	BatchGetAssets(context.Context, *connect.Request[v1.BatchGetAssetsRequest]) (*connect.Response[v1.BatchGetAssetsResponse], error)
}

// NewAssetServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAssetServiceHandler(svc AssetServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	assetServiceMethods := v1.File_chatto_api_v1_attachments_proto.Services().ByName("AssetService").Methods()
	assetServiceOpenBurnAttachmentHandler := connect.NewUnaryHandler(
		AssetServiceOpenBurnAttachmentProcedure,
		svc.OpenBurnAttachment,
		connect.WithSchema(assetServiceMethods.ByName("OpenBurnAttachment")),
		connect.WithHandlerOptions(opts...),
	)
	assetServiceCloseBurnAttachmentHandler := connect.NewUnaryHandler(
		AssetServiceCloseBurnAttachmentProcedure,
		svc.CloseBurnAttachment,
		connect.WithSchema(assetServiceMethods.ByName("CloseBurnAttachment")),
		connect.WithHandlerOptions(opts...),
	)
	assetServiceRequestAttachmentPermanenceHandler := connect.NewUnaryHandler(
		AssetServiceRequestAttachmentPermanenceProcedure,
		svc.RequestAttachmentPermanence,
		connect.WithSchema(assetServiceMethods.ByName("RequestAttachmentPermanence")),
		connect.WithHandlerOptions(opts...),
	)
	assetServiceMakeAttachmentPermanentHandler := connect.NewUnaryHandler(
		AssetServiceMakeAttachmentPermanentProcedure,
		svc.MakeAttachmentPermanent,
		connect.WithSchema(assetServiceMethods.ByName("MakeAttachmentPermanent")),
		connect.WithHandlerOptions(opts...),
	)
	assetServiceUndoAttachmentPermanenceHandler := connect.NewUnaryHandler(
		AssetServiceUndoAttachmentPermanenceProcedure,
		svc.UndoAttachmentPermanence,
		connect.WithSchema(assetServiceMethods.ByName("UndoAttachmentPermanence")),
		connect.WithHandlerOptions(opts...),
	)
	assetServiceGetAssetHandler := connect.NewUnaryHandler(
		AssetServiceGetAssetProcedure,
		svc.GetAsset,
		connect.WithSchema(assetServiceMethods.ByName("GetAsset")),
		connect.WithHandlerOptions(opts...),
	)
	assetServiceBatchGetAssetsHandler := connect.NewUnaryHandler(
		AssetServiceBatchGetAssetsProcedure,
		svc.BatchGetAssets,
		connect.WithSchema(assetServiceMethods.ByName("BatchGetAssets")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.api.v1.AssetService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AssetServiceOpenBurnAttachmentProcedure:
			assetServiceOpenBurnAttachmentHandler.ServeHTTP(w, r)
		case AssetServiceCloseBurnAttachmentProcedure:
			assetServiceCloseBurnAttachmentHandler.ServeHTTP(w, r)
		case AssetServiceRequestAttachmentPermanenceProcedure:
			assetServiceRequestAttachmentPermanenceHandler.ServeHTTP(w, r)
		case AssetServiceMakeAttachmentPermanentProcedure:
			assetServiceMakeAttachmentPermanentHandler.ServeHTTP(w, r)
		case AssetServiceUndoAttachmentPermanenceProcedure:
			assetServiceUndoAttachmentPermanenceHandler.ServeHTTP(w, r)
		case AssetServiceGetAssetProcedure:
			assetServiceGetAssetHandler.ServeHTTP(w, r)
		case AssetServiceBatchGetAssetsProcedure:
			assetServiceBatchGetAssetsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAssetServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAssetServiceHandler struct{}

func (UnimplementedAssetServiceHandler) OpenBurnAttachment(context.Context, *connect.Request[v1.OpenBurnAttachmentRequest]) (*connect.Response[v1.OpenBurnAttachmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AssetService.OpenBurnAttachment is not implemented"))
}

func (UnimplementedAssetServiceHandler) CloseBurnAttachment(context.Context, *connect.Request[v1.CloseBurnAttachmentRequest]) (*connect.Response[v1.CloseBurnAttachmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AssetService.CloseBurnAttachment is not implemented"))
}

func (UnimplementedAssetServiceHandler) RequestAttachmentPermanence(context.Context, *connect.Request[v1.RequestAttachmentPermanenceRequest]) (*connect.Response[v1.RequestAttachmentPermanenceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AssetService.RequestAttachmentPermanence is not implemented"))
}

func (UnimplementedAssetServiceHandler) MakeAttachmentPermanent(context.Context, *connect.Request[v1.MakeAttachmentPermanentRequest]) (*connect.Response[v1.MakeAttachmentPermanentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AssetService.MakeAttachmentPermanent is not implemented"))
}

func (UnimplementedAssetServiceHandler) UndoAttachmentPermanence(context.Context, *connect.Request[v1.UndoAttachmentPermanenceRequest]) (*connect.Response[v1.UndoAttachmentPermanenceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AssetService.UndoAttachmentPermanence is not implemented"))
}

func (UnimplementedAssetServiceHandler) GetAsset(context.Context, *connect.Request[v1.GetAssetRequest]) (*connect.Response[v1.GetAssetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AssetService.GetAsset is not implemented"))
}

func (UnimplementedAssetServiceHandler) BatchGetAssets(context.Context, *connect.Request[v1.BatchGetAssetsRequest]) (*connect.Response[v1.BatchGetAssetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.AssetService.BatchGetAssets is not implemented"))
}
