// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/api/v1/rooms.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hmans.de/chatto/internal/pb/chatto/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RoomServiceName is the fully-qualified name of the RoomService service.
	RoomServiceName = "chatto.api.v1.RoomService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RoomServiceGetRoomReadStateProcedure is the fully-qualified name of the RoomService's
	// GetRoomReadState RPC.
	RoomServiceGetRoomReadStateProcedure = "/chatto.api.v1.RoomService/GetRoomReadState"
	// RoomServiceBatchGetRoomReadStatesProcedure is the fully-qualified name of the RoomService's
	// BatchGetRoomReadStates RPC.
	RoomServiceBatchGetRoomReadStatesProcedure = "/chatto.api.v1.RoomService/BatchGetRoomReadStates"
	// RoomServiceCreateRoomProcedure is the fully-qualified name of the RoomService's CreateRoom RPC.
	RoomServiceCreateRoomProcedure = "/chatto.api.v1.RoomService/CreateRoom"
	// RoomServiceUpdateRoomProcedure is the fully-qualified name of the RoomService's UpdateRoom RPC.
	RoomServiceUpdateRoomProcedure = "/chatto.api.v1.RoomService/UpdateRoom"
	// RoomServiceArchiveRoomProcedure is the fully-qualified name of the RoomService's ArchiveRoom RPC.
	RoomServiceArchiveRoomProcedure = "/chatto.api.v1.RoomService/ArchiveRoom"
	// RoomServiceUnarchiveRoomProcedure is the fully-qualified name of the RoomService's UnarchiveRoom
	// RPC.
	RoomServiceUnarchiveRoomProcedure = "/chatto.api.v1.RoomService/UnarchiveRoom"
	// RoomServiceJoinRoomProcedure is the fully-qualified name of the RoomService's JoinRoom RPC.
	RoomServiceJoinRoomProcedure = "/chatto.api.v1.RoomService/JoinRoom"
	// RoomServiceJoinRoomGroupProcedure is the fully-qualified name of the RoomService's JoinRoomGroup
	// RPC.
	RoomServiceJoinRoomGroupProcedure = "/chatto.api.v1.RoomService/JoinRoomGroup"
	// RoomServiceStartDMProcedure is the fully-qualified name of the RoomService's StartDM RPC.
	RoomServiceStartDMProcedure = "/chatto.api.v1.RoomService/StartDM"
	// RoomServiceLeaveRoomProcedure is the fully-qualified name of the RoomService's LeaveRoom RPC.
	RoomServiceLeaveRoomProcedure = "/chatto.api.v1.RoomService/LeaveRoom"
	// RoomServiceListMembersProcedure is the fully-qualified name of the RoomService's ListMembers RPC.
	RoomServiceListMembersProcedure = "/chatto.api.v1.RoomService/ListMembers"
	// RoomServiceGetMemberProcedure is the fully-qualified name of the RoomService's GetMember RPC.
	RoomServiceGetMemberProcedure = "/chatto.api.v1.RoomService/GetMember"
	// RoomServiceBatchGetMembersProcedure is the fully-qualified name of the RoomService's
	// BatchGetMembers RPC.
	RoomServiceBatchGetMembersProcedure = "/chatto.api.v1.RoomService/BatchGetMembers"
	// RoomServiceAddMemberProcedure is the fully-qualified name of the RoomService's AddMember RPC.
	RoomServiceAddMemberProcedure = "/chatto.api.v1.RoomService/AddMember"
	// RoomServiceRemoveMemberProcedure is the fully-qualified name of the RoomService's RemoveMember
	// RPC.
	RoomServiceRemoveMemberProcedure = "/chatto.api.v1.RoomService/RemoveMember"
	// RoomServiceListSuspensionsProcedure is the fully-qualified name of the RoomService's
	// ListSuspensions RPC.
	RoomServiceListSuspensionsProcedure = "/chatto.api.v1.RoomService/ListSuspensions"
	// RoomServiceListRoomAttachmentsProcedure is the fully-qualified name of the RoomService's
	// ListRoomAttachments RPC.
	RoomServiceListRoomAttachmentsProcedure = "/chatto.api.v1.RoomService/ListRoomAttachments"
	// RoomServiceListPinnedMessagesProcedure is the fully-qualified name of the RoomService's
	// ListPinnedMessages RPC.
	RoomServiceListPinnedMessagesProcedure = "/chatto.api.v1.RoomService/ListPinnedMessages"
	// RoomServiceCreatePinnedMessageProcedure is the fully-qualified name of the RoomService's
	// CreatePinnedMessage RPC.
	RoomServiceCreatePinnedMessageProcedure = "/chatto.api.v1.RoomService/CreatePinnedMessage"
	// RoomServiceDeletePinnedMessageProcedure is the fully-qualified name of the RoomService's
	// DeletePinnedMessage RPC.
	RoomServiceDeletePinnedMessageProcedure = "/chatto.api.v1.RoomService/DeletePinnedMessage"
	// RoomServiceRefreshTypingIndicatorProcedure is the fully-qualified name of the RoomService's
	// RefreshTypingIndicator RPC.
	RoomServiceRefreshTypingIndicatorProcedure = "/chatto.api.v1.RoomService/RefreshTypingIndicator"
	// RoomServiceGetRoomEventsProcedure is the fully-qualified name of the RoomService's GetRoomEvents
	// RPC.
	RoomServiceGetRoomEventsProcedure = "/chatto.api.v1.RoomService/GetRoomEvents"
	// RoomServiceGetRoomEventsAroundProcedure is the fully-qualified name of the RoomService's
	// GetRoomEventsAround RPC.
	RoomServiceGetRoomEventsAroundProcedure = "/chatto.api.v1.RoomService/GetRoomEventsAround"
	// RoomServiceMarkRoomAsReadProcedure is the fully-qualified name of the RoomService's
	// MarkRoomAsRead RPC.
	RoomServiceMarkRoomAsReadProcedure = "/chatto.api.v1.RoomService/MarkRoomAsRead"
	// RoomServiceRemoveUserProcedure is the fully-qualified name of the RoomService's RemoveUser RPC.
	RoomServiceRemoveUserProcedure = "/chatto.api.v1.RoomService/RemoveUser"
	// RoomServiceLiftSuspensionProcedure is the fully-qualified name of the RoomService's
	// LiftSuspension RPC.
	RoomServiceLiftSuspensionProcedure = "/chatto.api.v1.RoomService/LiftSuspension"
)

// RoomServiceClient is a client for the chatto.api.v1.RoomService service.
type RoomServiceClient interface {
	// Reads the current viewer's stored marker without changing it. Requires the
	// same membership and read access as MarkRoomAsRead. Missing resources
	// return NOT_FOUND; inaccessible resources return PERMISSION_DENIED.
	GetRoomReadState(context.Context, *connect.Request[v1.GetRoomReadStateRequest]) (*connect.Response[v1.GetRoomReadStateResponse], error)
	// Reads up to 100 states under the same authorization as GetRoomReadState.
	// Missing and inaccessible resources are omitted; duplicates use first-seen order.
	BatchGetRoomReadStates(context.Context, *connect.Request[v1.BatchGetRoomReadStatesRequest]) (*connect.Response[v1.BatchGetRoomReadStatesResponse], error)
	// Creates a new channel room in a room group. The caller must be allowed to
	// create rooms in the target group.
	CreateRoom(context.Context, *connect.Request[v1.CreateRoomRequest]) (*connect.Response[v1.CreateRoomResponse], error)
	// Updates a room's editable metadata. The caller must be allowed to manage
	// rooms. Direct-message rooms cannot be universal.
	UpdateRoom(context.Context, *connect.Request[v1.UpdateRoomRequest]) (*connect.Response[v1.UpdateRoomResponse], error)
	// Archives a room so it is hidden from active room lists. The caller must be
	// allowed to manage rooms.
	ArchiveRoom(context.Context, *connect.Request[v1.ArchiveRoomRequest]) (*connect.Response[v1.ArchiveRoomResponse], error)
	// Restores an archived room to active room lists. The caller must be allowed
	// to manage rooms.
	UnarchiveRoom(context.Context, *connect.Request[v1.UnarchiveRoomRequest]) (*connect.Response[v1.UnarchiveRoomResponse], error)
	// Joins the room as the current user when room permissions allow it.
	JoinRoom(context.Context, *connect.Request[v1.JoinRoomRequest]) (*connect.Response[v1.JoinRoomResponse], error)
	// Joins every unarchived room in a group that the current user can join.
	// Already-joined and non-joinable rooms are skipped.
	JoinRoomGroup(context.Context, *connect.Request[v1.JoinRoomGroupRequest]) (*connect.Response[v1.JoinRoomGroupResponse], error)
	// Starts a direct-message room for the current human user and the requested
	// participant set, or restores its existing DM to the caller's conversation
	// list across clients. message.post is required
	// only when the DM must be created. A valid request from a bot receives
	// PERMISSION_DENIED and cannot use this RPC to fetch an existing DM.
	StartDM(context.Context, *connect.Request[v1.StartDMRequest]) (*connect.Response[v1.StartDMResponse], error)
	// Leaves the room as the current user. Direct-message and universal rooms
	// cannot be left.
	LeaveRoom(context.Context, *connect.Request[v1.LeaveRoomRequest]) (*connect.Response[v1.LeaveRoomResponse], error)
	// Lists effective room member IDs in ascending ID order. Resolve user details
	// with UserService.BatchGetUsers. Existing members and room.manage holders may
	// list a channel room; other nonmembers need both room.list and room.join.
	ListMembers(context.Context, *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error)
	// Gets one effective member, including automatic universal membership.
	// Channel-room members, room.manage holders, and user.manage-accounts holders
	// may read members. Bot owners and bot.manage holders may read their target
	// bots only. DMs require caller membership. Returns NOT_FOUND for nonmembers.
	GetMember(context.Context, *connect.Request[v1.GetMemberRequest]) (*connect.Response[v1.GetMemberResponse], error)
	// Gets effective member rows for the requested accounts. Uses the same
	// authorization as GetMember; omits unknown accounts and nonmembers.
	BatchGetMembers(context.Context, *connect.Request[v1.BatchGetMembersRequest]) (*connect.Response[v1.BatchGetMembersResponse], error)
	// Adds an account as an explicit channel-room member. room.manage for this
	// room or user.manage-accounts overrides the target's missing room.join.
	// Bot owners and bot.manage holders may also add bots, but without either
	// override the bot needs effective room.join, bounded by its owner's authority.
	// Preserves permission grants. Suspensions, archived, universal, and DM rooms prevent adding.
	AddMember(context.Context, *connect.Request[v1.AddMemberRequest]) (*connect.Response[v1.AddMemberResponse], error)
	// Removes an explicit channel-room member. Requires room.manage for this room,
	// user.manage-accounts, ownership of the target bot, or bot.manage.
	// Removal is allowed after room.join is lost and from archived rooms.
	// Preserves permission grants. Universal and DM membership cannot be edited.
	RemoveMember(context.Context, *connect.Request[v1.RemoveMemberRequest]) (*connect.Response[v1.RemoveMemberResponse], error)
	// Lists active channel room suspensions. Requires server-scope
	// room.remove-member.
	ListSuspensions(context.Context, *connect.Request[v1.ListSuspensionsRequest]) (*connect.Response[v1.ListSuspensionsResponse], error)
	// Lists current message-owned room attachments. Authentication and room
	// membership are required. Attachments also require message.read or a
	// matching thread relationship with message.read-interactions. The server omits attachments from
	// inaccessible threads. Returns PERMISSION_DENIED when the room is
	// inaccessible to the caller.
	ListRoomAttachments(context.Context, *connect.Request[v1.ListRoomAttachmentsRequest]) (*connect.Response[v1.ListRoomAttachmentsResponse], error)
	// Lists current pinned messages in a channel room. Room membership plus
	// message.read or message.read-interactions are required. The server omits
	// pins from threads that the caller cannot read. Direct-message rooms do not
	// support pins.
	ListPinnedMessages(context.Context, *connect.Request[v1.ListPinnedMessagesRequest]) (*connect.Response[v1.ListPinnedMessagesResponse], error)
	// Pins a current message. The caller must have room.manage and must be able
	// to read the message. Repeating an existing pin is idempotent. Direct-message
	// rooms are rejected.
	CreatePinnedMessage(context.Context, *connect.Request[v1.CreatePinnedMessageRequest]) (*connect.Response[v1.CreatePinnedMessageResponse], error)
	// Removes a current pin. The caller must have room.manage. Removing a
	// missing pin is idempotent. Direct-message rooms are rejected.
	DeletePinnedMessage(context.Context, *connect.Request[v1.DeletePinnedMessageRequest]) (*connect.Response[v1.DeletePinnedMessageResponse], error)
	// Refreshes the current user's live-only typing indicator for a room or
	// thread. Room membership is required; message posting permission is not.
	// Send at most once every 2 seconds while typing. After posting a message,
	// the next typing activity can send immediately. Stop sending when typing
	// stops; receivers clear the indicator after 6 seconds without an event.
	RefreshTypingIndicator(context.Context, *connect.Request[v1.RefreshTypingIndicatorRequest]) (*connect.Response[v1.RefreshTypingIndicatorResponse], error)
	// Returns one page of room timeline events, including related user data
	// needed to render the page. Room membership is required. Reads also require
	// message.read or message.read-interactions. The server returns only related
	// thread roots for an interaction-scoped caller.
	GetRoomEvents(context.Context, *connect.Request[v1.GetRoomEventsRequest]) (*connect.Response[v1.GetRoomEventsResponse], error)
	// Returns a room timeline window centered around a specific event. Use this to
	// open a permalink, search result, or notification target in context. Returns
	// NOT_FOUND when the anchor event is missing or not visible in the room
	// timeline. Returns PERMISSION_DENIED when room membership or both read modes
	// are missing, or when the anchor is in an unrelated thread.
	GetRoomEventsAround(context.Context, *connect.Request[v1.GetRoomEventsAroundRequest]) (*connect.Response[v1.GetRoomEventsAroundResponse], error)
	// Marks a room timeline as read through the supplied event. Room membership
	// is required. Reads also require message.read or
	// message.read-interactions. If no event
	// is supplied, the server marks through the latest root event that the caller
	// can read. Clients
	// usually call this after the user has viewed the latest visible event in the
	// room.
	MarkRoomAsRead(context.Context, *connect.Request[v1.MarkRoomAsReadRequest]) (*connect.Response[v1.MarkRoomAsReadResponse], error)
	// Removes a current channel room member with a required reason. Requires
	// room.remove-member. Without suspension, ordinary join rules apply afterward.
	// Universal rooms require a suspension. Direct-message rooms are excluded.
	RemoveUser(context.Context, *connect.Request[v1.RemoveUserRequest]) (*connect.Response[v1.RemoveUserResponse], error)
	// Lifts an active channel room suspension. Requires room.remove-member.
	// Calling this when no active suspension exists succeeds.
	LiftSuspension(context.Context, *connect.Request[v1.LiftSuspensionRequest]) (*connect.Response[v1.LiftSuspensionResponse], error)
}

// NewRoomServiceClient constructs a client for the chatto.api.v1.RoomService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRoomServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RoomServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	roomServiceMethods := v1.File_chatto_api_v1_rooms_proto.Services().ByName("RoomService").Methods()
	return &roomServiceClient{
		getRoomReadState: connect.NewClient[v1.GetRoomReadStateRequest, v1.GetRoomReadStateResponse](
			httpClient,
			baseURL+RoomServiceGetRoomReadStateProcedure,
			connect.WithSchema(roomServiceMethods.ByName("GetRoomReadState")),
			connect.WithClientOptions(opts...),
		),
		batchGetRoomReadStates: connect.NewClient[v1.BatchGetRoomReadStatesRequest, v1.BatchGetRoomReadStatesResponse](
			httpClient,
			baseURL+RoomServiceBatchGetRoomReadStatesProcedure,
			connect.WithSchema(roomServiceMethods.ByName("BatchGetRoomReadStates")),
			connect.WithClientOptions(opts...),
		),
		createRoom: connect.NewClient[v1.CreateRoomRequest, v1.CreateRoomResponse](
			httpClient,
			baseURL+RoomServiceCreateRoomProcedure,
			connect.WithSchema(roomServiceMethods.ByName("CreateRoom")),
			connect.WithClientOptions(opts...),
		),
		updateRoom: connect.NewClient[v1.UpdateRoomRequest, v1.UpdateRoomResponse](
			httpClient,
			baseURL+RoomServiceUpdateRoomProcedure,
			connect.WithSchema(roomServiceMethods.ByName("UpdateRoom")),
			connect.WithClientOptions(opts...),
		),
		archiveRoom: connect.NewClient[v1.ArchiveRoomRequest, v1.ArchiveRoomResponse](
			httpClient,
			baseURL+RoomServiceArchiveRoomProcedure,
			connect.WithSchema(roomServiceMethods.ByName("ArchiveRoom")),
			connect.WithClientOptions(opts...),
		),
		unarchiveRoom: connect.NewClient[v1.UnarchiveRoomRequest, v1.UnarchiveRoomResponse](
			httpClient,
			baseURL+RoomServiceUnarchiveRoomProcedure,
			connect.WithSchema(roomServiceMethods.ByName("UnarchiveRoom")),
			connect.WithClientOptions(opts...),
		),
		joinRoom: connect.NewClient[v1.JoinRoomRequest, v1.JoinRoomResponse](
			httpClient,
			baseURL+RoomServiceJoinRoomProcedure,
			connect.WithSchema(roomServiceMethods.ByName("JoinRoom")),
			connect.WithClientOptions(opts...),
		),
		joinRoomGroup: connect.NewClient[v1.JoinRoomGroupRequest, v1.JoinRoomGroupResponse](
			httpClient,
			baseURL+RoomServiceJoinRoomGroupProcedure,
			connect.WithSchema(roomServiceMethods.ByName("JoinRoomGroup")),
			connect.WithClientOptions(opts...),
		),
		startDM: connect.NewClient[v1.StartDMRequest, v1.StartDMResponse](
			httpClient,
			baseURL+RoomServiceStartDMProcedure,
			connect.WithSchema(roomServiceMethods.ByName("StartDM")),
			connect.WithClientOptions(opts...),
		),
		leaveRoom: connect.NewClient[v1.LeaveRoomRequest, v1.LeaveRoomResponse](
			httpClient,
			baseURL+RoomServiceLeaveRoomProcedure,
			connect.WithSchema(roomServiceMethods.ByName("LeaveRoom")),
			connect.WithClientOptions(opts...),
		),
		listMembers: connect.NewClient[v1.ListMembersRequest, v1.ListMembersResponse](
			httpClient,
			baseURL+RoomServiceListMembersProcedure,
			connect.WithSchema(roomServiceMethods.ByName("ListMembers")),
			connect.WithClientOptions(opts...),
		),
		getMember: connect.NewClient[v1.GetMemberRequest, v1.GetMemberResponse](
			httpClient,
			baseURL+RoomServiceGetMemberProcedure,
			connect.WithSchema(roomServiceMethods.ByName("GetMember")),
			connect.WithClientOptions(opts...),
		),
		batchGetMembers: connect.NewClient[v1.BatchGetMembersRequest, v1.BatchGetMembersResponse](
			httpClient,
			baseURL+RoomServiceBatchGetMembersProcedure,
			connect.WithSchema(roomServiceMethods.ByName("BatchGetMembers")),
			connect.WithClientOptions(opts...),
		),
		addMember: connect.NewClient[v1.AddMemberRequest, v1.AddMemberResponse](
			httpClient,
			baseURL+RoomServiceAddMemberProcedure,
			connect.WithSchema(roomServiceMethods.ByName("AddMember")),
			connect.WithClientOptions(opts...),
		),
		removeMember: connect.NewClient[v1.RemoveMemberRequest, v1.RemoveMemberResponse](
			httpClient,
			baseURL+RoomServiceRemoveMemberProcedure,
			connect.WithSchema(roomServiceMethods.ByName("RemoveMember")),
			connect.WithClientOptions(opts...),
		),
		listSuspensions: connect.NewClient[v1.ListSuspensionsRequest, v1.ListSuspensionsResponse](
			httpClient,
			baseURL+RoomServiceListSuspensionsProcedure,
			connect.WithSchema(roomServiceMethods.ByName("ListSuspensions")),
			connect.WithClientOptions(opts...),
		),
		listRoomAttachments: connect.NewClient[v1.ListRoomAttachmentsRequest, v1.ListRoomAttachmentsResponse](
			httpClient,
			baseURL+RoomServiceListRoomAttachmentsProcedure,
			connect.WithSchema(roomServiceMethods.ByName("ListRoomAttachments")),
			connect.WithClientOptions(opts...),
		),
		listPinnedMessages: connect.NewClient[v1.ListPinnedMessagesRequest, v1.ListPinnedMessagesResponse](
			httpClient,
			baseURL+RoomServiceListPinnedMessagesProcedure,
			connect.WithSchema(roomServiceMethods.ByName("ListPinnedMessages")),
			connect.WithClientOptions(opts...),
		),
		createPinnedMessage: connect.NewClient[v1.CreatePinnedMessageRequest, v1.CreatePinnedMessageResponse](
			httpClient,
			baseURL+RoomServiceCreatePinnedMessageProcedure,
			connect.WithSchema(roomServiceMethods.ByName("CreatePinnedMessage")),
			connect.WithClientOptions(opts...),
		),
		deletePinnedMessage: connect.NewClient[v1.DeletePinnedMessageRequest, v1.DeletePinnedMessageResponse](
			httpClient,
			baseURL+RoomServiceDeletePinnedMessageProcedure,
			connect.WithSchema(roomServiceMethods.ByName("DeletePinnedMessage")),
			connect.WithClientOptions(opts...),
		),
		refreshTypingIndicator: connect.NewClient[v1.RefreshTypingIndicatorRequest, v1.RefreshTypingIndicatorResponse](
			httpClient,
			baseURL+RoomServiceRefreshTypingIndicatorProcedure,
			connect.WithSchema(roomServiceMethods.ByName("RefreshTypingIndicator")),
			connect.WithClientOptions(opts...),
		),
		getRoomEvents: connect.NewClient[v1.GetRoomEventsRequest, v1.GetRoomEventsResponse](
			httpClient,
			baseURL+RoomServiceGetRoomEventsProcedure,
			connect.WithSchema(roomServiceMethods.ByName("GetRoomEvents")),
			connect.WithClientOptions(opts...),
		),
		getRoomEventsAround: connect.NewClient[v1.GetRoomEventsAroundRequest, v1.GetRoomEventsAroundResponse](
			httpClient,
			baseURL+RoomServiceGetRoomEventsAroundProcedure,
			connect.WithSchema(roomServiceMethods.ByName("GetRoomEventsAround")),
			connect.WithClientOptions(opts...),
		),
		markRoomAsRead: connect.NewClient[v1.MarkRoomAsReadRequest, v1.MarkRoomAsReadResponse](
			httpClient,
			baseURL+RoomServiceMarkRoomAsReadProcedure,
			connect.WithSchema(roomServiceMethods.ByName("MarkRoomAsRead")),
			connect.WithClientOptions(opts...),
		),
		removeUser: connect.NewClient[v1.RemoveUserRequest, v1.RemoveUserResponse](
			httpClient,
			baseURL+RoomServiceRemoveUserProcedure,
			connect.WithSchema(roomServiceMethods.ByName("RemoveUser")),
			connect.WithClientOptions(opts...),
		),
		liftSuspension: connect.NewClient[v1.LiftSuspensionRequest, v1.LiftSuspensionResponse](
			httpClient,
			baseURL+RoomServiceLiftSuspensionProcedure,
			connect.WithSchema(roomServiceMethods.ByName("LiftSuspension")),
			connect.WithClientOptions(opts...),
		),
	}
}

// roomServiceClient implements RoomServiceClient.
type roomServiceClient struct {
	getRoomReadState       *connect.Client[v1.GetRoomReadStateRequest, v1.GetRoomReadStateResponse]
	batchGetRoomReadStates *connect.Client[v1.BatchGetRoomReadStatesRequest, v1.BatchGetRoomReadStatesResponse]
	createRoom             *connect.Client[v1.CreateRoomRequest, v1.CreateRoomResponse]
	updateRoom             *connect.Client[v1.UpdateRoomRequest, v1.UpdateRoomResponse]
	archiveRoom            *connect.Client[v1.ArchiveRoomRequest, v1.ArchiveRoomResponse]
	unarchiveRoom          *connect.Client[v1.UnarchiveRoomRequest, v1.UnarchiveRoomResponse]
	joinRoom               *connect.Client[v1.JoinRoomRequest, v1.JoinRoomResponse]
	joinRoomGroup          *connect.Client[v1.JoinRoomGroupRequest, v1.JoinRoomGroupResponse]
	startDM                *connect.Client[v1.StartDMRequest, v1.StartDMResponse]
	leaveRoom              *connect.Client[v1.LeaveRoomRequest, v1.LeaveRoomResponse]
	listMembers            *connect.Client[v1.ListMembersRequest, v1.ListMembersResponse]
	getMember              *connect.Client[v1.GetMemberRequest, v1.GetMemberResponse]
	batchGetMembers        *connect.Client[v1.BatchGetMembersRequest, v1.BatchGetMembersResponse]
	addMember              *connect.Client[v1.AddMemberRequest, v1.AddMemberResponse]
	removeMember           *connect.Client[v1.RemoveMemberRequest, v1.RemoveMemberResponse]
	listSuspensions        *connect.Client[v1.ListSuspensionsRequest, v1.ListSuspensionsResponse]
	listRoomAttachments    *connect.Client[v1.ListRoomAttachmentsRequest, v1.ListRoomAttachmentsResponse]
	listPinnedMessages     *connect.Client[v1.ListPinnedMessagesRequest, v1.ListPinnedMessagesResponse]
	createPinnedMessage    *connect.Client[v1.CreatePinnedMessageRequest, v1.CreatePinnedMessageResponse]
	deletePinnedMessage    *connect.Client[v1.DeletePinnedMessageRequest, v1.DeletePinnedMessageResponse]
	refreshTypingIndicator *connect.Client[v1.RefreshTypingIndicatorRequest, v1.RefreshTypingIndicatorResponse]
	getRoomEvents          *connect.Client[v1.GetRoomEventsRequest, v1.GetRoomEventsResponse]
	getRoomEventsAround    *connect.Client[v1.GetRoomEventsAroundRequest, v1.GetRoomEventsAroundResponse]
	markRoomAsRead         *connect.Client[v1.MarkRoomAsReadRequest, v1.MarkRoomAsReadResponse]
	removeUser             *connect.Client[v1.RemoveUserRequest, v1.RemoveUserResponse]
	liftSuspension         *connect.Client[v1.LiftSuspensionRequest, v1.LiftSuspensionResponse]
}

// GetRoomReadState calls chatto.api.v1.RoomService.GetRoomReadState.
func (c *roomServiceClient) GetRoomReadState(ctx context.Context, req *connect.Request[v1.GetRoomReadStateRequest]) (*connect.Response[v1.GetRoomReadStateResponse], error) {
	return c.getRoomReadState.CallUnary(ctx, req)
}

// BatchGetRoomReadStates calls chatto.api.v1.RoomService.BatchGetRoomReadStates.
func (c *roomServiceClient) BatchGetRoomReadStates(ctx context.Context, req *connect.Request[v1.BatchGetRoomReadStatesRequest]) (*connect.Response[v1.BatchGetRoomReadStatesResponse], error) {
	return c.batchGetRoomReadStates.CallUnary(ctx, req)
}

// CreateRoom calls chatto.api.v1.RoomService.CreateRoom.
func (c *roomServiceClient) CreateRoom(ctx context.Context, req *connect.Request[v1.CreateRoomRequest]) (*connect.Response[v1.CreateRoomResponse], error) {
	return c.createRoom.CallUnary(ctx, req)
}

// UpdateRoom calls chatto.api.v1.RoomService.UpdateRoom.
func (c *roomServiceClient) UpdateRoom(ctx context.Context, req *connect.Request[v1.UpdateRoomRequest]) (*connect.Response[v1.UpdateRoomResponse], error) {
	return c.updateRoom.CallUnary(ctx, req)
}

// ArchiveRoom calls chatto.api.v1.RoomService.ArchiveRoom.
func (c *roomServiceClient) ArchiveRoom(ctx context.Context, req *connect.Request[v1.ArchiveRoomRequest]) (*connect.Response[v1.ArchiveRoomResponse], error) {
	return c.archiveRoom.CallUnary(ctx, req)
}

// UnarchiveRoom calls chatto.api.v1.RoomService.UnarchiveRoom.
func (c *roomServiceClient) UnarchiveRoom(ctx context.Context, req *connect.Request[v1.UnarchiveRoomRequest]) (*connect.Response[v1.UnarchiveRoomResponse], error) {
	return c.unarchiveRoom.CallUnary(ctx, req)
}

// JoinRoom calls chatto.api.v1.RoomService.JoinRoom.
func (c *roomServiceClient) JoinRoom(ctx context.Context, req *connect.Request[v1.JoinRoomRequest]) (*connect.Response[v1.JoinRoomResponse], error) {
	return c.joinRoom.CallUnary(ctx, req)
}

// JoinRoomGroup calls chatto.api.v1.RoomService.JoinRoomGroup.
func (c *roomServiceClient) JoinRoomGroup(ctx context.Context, req *connect.Request[v1.JoinRoomGroupRequest]) (*connect.Response[v1.JoinRoomGroupResponse], error) {
	return c.joinRoomGroup.CallUnary(ctx, req)
}

// StartDM calls chatto.api.v1.RoomService.StartDM.
func (c *roomServiceClient) StartDM(ctx context.Context, req *connect.Request[v1.StartDMRequest]) (*connect.Response[v1.StartDMResponse], error) {
	return c.startDM.CallUnary(ctx, req)
}

// LeaveRoom calls chatto.api.v1.RoomService.LeaveRoom.
func (c *roomServiceClient) LeaveRoom(ctx context.Context, req *connect.Request[v1.LeaveRoomRequest]) (*connect.Response[v1.LeaveRoomResponse], error) {
	return c.leaveRoom.CallUnary(ctx, req)
}

// ListMembers calls chatto.api.v1.RoomService.ListMembers.
func (c *roomServiceClient) ListMembers(ctx context.Context, req *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error) {
	return c.listMembers.CallUnary(ctx, req)
}

// GetMember calls chatto.api.v1.RoomService.GetMember.
func (c *roomServiceClient) GetMember(ctx context.Context, req *connect.Request[v1.GetMemberRequest]) (*connect.Response[v1.GetMemberResponse], error) {
	return c.getMember.CallUnary(ctx, req)
}

// BatchGetMembers calls chatto.api.v1.RoomService.BatchGetMembers.
func (c *roomServiceClient) BatchGetMembers(ctx context.Context, req *connect.Request[v1.BatchGetMembersRequest]) (*connect.Response[v1.BatchGetMembersResponse], error) {
	return c.batchGetMembers.CallUnary(ctx, req)
}

// AddMember calls chatto.api.v1.RoomService.AddMember.
func (c *roomServiceClient) AddMember(ctx context.Context, req *connect.Request[v1.AddMemberRequest]) (*connect.Response[v1.AddMemberResponse], error) {
	return c.addMember.CallUnary(ctx, req)
}

// RemoveMember calls chatto.api.v1.RoomService.RemoveMember.
func (c *roomServiceClient) RemoveMember(ctx context.Context, req *connect.Request[v1.RemoveMemberRequest]) (*connect.Response[v1.RemoveMemberResponse], error) {
	return c.removeMember.CallUnary(ctx, req)
}

// ListSuspensions calls chatto.api.v1.RoomService.ListSuspensions.
func (c *roomServiceClient) ListSuspensions(ctx context.Context, req *connect.Request[v1.ListSuspensionsRequest]) (*connect.Response[v1.ListSuspensionsResponse], error) {
	return c.listSuspensions.CallUnary(ctx, req)
}

// ListRoomAttachments calls chatto.api.v1.RoomService.ListRoomAttachments.
func (c *roomServiceClient) ListRoomAttachments(ctx context.Context, req *connect.Request[v1.ListRoomAttachmentsRequest]) (*connect.Response[v1.ListRoomAttachmentsResponse], error) {
	return c.listRoomAttachments.CallUnary(ctx, req)
}

// ListPinnedMessages calls chatto.api.v1.RoomService.ListPinnedMessages.
func (c *roomServiceClient) ListPinnedMessages(ctx context.Context, req *connect.Request[v1.ListPinnedMessagesRequest]) (*connect.Response[v1.ListPinnedMessagesResponse], error) {
	return c.listPinnedMessages.CallUnary(ctx, req)
}

// CreatePinnedMessage calls chatto.api.v1.RoomService.CreatePinnedMessage.
func (c *roomServiceClient) CreatePinnedMessage(ctx context.Context, req *connect.Request[v1.CreatePinnedMessageRequest]) (*connect.Response[v1.CreatePinnedMessageResponse], error) {
	return c.createPinnedMessage.CallUnary(ctx, req)
}

// DeletePinnedMessage calls chatto.api.v1.RoomService.DeletePinnedMessage.
func (c *roomServiceClient) DeletePinnedMessage(ctx context.Context, req *connect.Request[v1.DeletePinnedMessageRequest]) (*connect.Response[v1.DeletePinnedMessageResponse], error) {
	return c.deletePinnedMessage.CallUnary(ctx, req)
}

// RefreshTypingIndicator calls chatto.api.v1.RoomService.RefreshTypingIndicator.
func (c *roomServiceClient) RefreshTypingIndicator(ctx context.Context, req *connect.Request[v1.RefreshTypingIndicatorRequest]) (*connect.Response[v1.RefreshTypingIndicatorResponse], error) {
	return c.refreshTypingIndicator.CallUnary(ctx, req)
}

// GetRoomEvents calls chatto.api.v1.RoomService.GetRoomEvents.
func (c *roomServiceClient) GetRoomEvents(ctx context.Context, req *connect.Request[v1.GetRoomEventsRequest]) (*connect.Response[v1.GetRoomEventsResponse], error) {
	return c.getRoomEvents.CallUnary(ctx, req)
}

// GetRoomEventsAround calls chatto.api.v1.RoomService.GetRoomEventsAround.
func (c *roomServiceClient) GetRoomEventsAround(ctx context.Context, req *connect.Request[v1.GetRoomEventsAroundRequest]) (*connect.Response[v1.GetRoomEventsAroundResponse], error) {
	return c.getRoomEventsAround.CallUnary(ctx, req)
}

// MarkRoomAsRead calls chatto.api.v1.RoomService.MarkRoomAsRead.
func (c *roomServiceClient) MarkRoomAsRead(ctx context.Context, req *connect.Request[v1.MarkRoomAsReadRequest]) (*connect.Response[v1.MarkRoomAsReadResponse], error) {
	return c.markRoomAsRead.CallUnary(ctx, req)
}

// RemoveUser calls chatto.api.v1.RoomService.RemoveUser.
func (c *roomServiceClient) RemoveUser(ctx context.Context, req *connect.Request[v1.RemoveUserRequest]) (*connect.Response[v1.RemoveUserResponse], error) {
	return c.removeUser.CallUnary(ctx, req)
}

// LiftSuspension calls chatto.api.v1.RoomService.LiftSuspension.
func (c *roomServiceClient) LiftSuspension(ctx context.Context, req *connect.Request[v1.LiftSuspensionRequest]) (*connect.Response[v1.LiftSuspensionResponse], error) {
	return c.liftSuspension.CallUnary(ctx, req)
}

// RoomServiceHandler is an implementation of the chatto.api.v1.RoomService service.
type RoomServiceHandler interface {
	// Reads the current viewer's stored marker without changing it. Requires the
	// same membership and read access as MarkRoomAsRead. Missing resources
	// return NOT_FOUND; inaccessible resources return PERMISSION_DENIED.
	GetRoomReadState(context.Context, *connect.Request[v1.GetRoomReadStateRequest]) (*connect.Response[v1.GetRoomReadStateResponse], error)
	// Reads up to 100 states under the same authorization as GetRoomReadState.
	// Missing and inaccessible resources are omitted; duplicates use first-seen order.
	BatchGetRoomReadStates(context.Context, *connect.Request[v1.BatchGetRoomReadStatesRequest]) (*connect.Response[v1.BatchGetRoomReadStatesResponse], error)
	// Creates a new channel room in a room group. The caller must be allowed to
	// create rooms in the target group.
	CreateRoom(context.Context, *connect.Request[v1.CreateRoomRequest]) (*connect.Response[v1.CreateRoomResponse], error)
	// Updates a room's editable metadata. The caller must be allowed to manage
	// rooms. Direct-message rooms cannot be universal.
	UpdateRoom(context.Context, *connect.Request[v1.UpdateRoomRequest]) (*connect.Response[v1.UpdateRoomResponse], error)
	// Archives a room so it is hidden from active room lists. The caller must be
	// allowed to manage rooms.
	ArchiveRoom(context.Context, *connect.Request[v1.ArchiveRoomRequest]) (*connect.Response[v1.ArchiveRoomResponse], error)
	// Restores an archived room to active room lists. The caller must be allowed
	// to manage rooms.
	UnarchiveRoom(context.Context, *connect.Request[v1.UnarchiveRoomRequest]) (*connect.Response[v1.UnarchiveRoomResponse], error)
	// Joins the room as the current user when room permissions allow it.
	JoinRoom(context.Context, *connect.Request[v1.JoinRoomRequest]) (*connect.Response[v1.JoinRoomResponse], error)
	// Joins every unarchived room in a group that the current user can join.
	// Already-joined and non-joinable rooms are skipped.
	JoinRoomGroup(context.Context, *connect.Request[v1.JoinRoomGroupRequest]) (*connect.Response[v1.JoinRoomGroupResponse], error)
	// Starts a direct-message room for the current human user and the requested
	// participant set, or restores its existing DM to the caller's conversation
	// list across clients. message.post is required
	// only when the DM must be created. A valid request from a bot receives
	// PERMISSION_DENIED and cannot use this RPC to fetch an existing DM.
	StartDM(context.Context, *connect.Request[v1.StartDMRequest]) (*connect.Response[v1.StartDMResponse], error)
	// Leaves the room as the current user. Direct-message and universal rooms
	// cannot be left.
	LeaveRoom(context.Context, *connect.Request[v1.LeaveRoomRequest]) (*connect.Response[v1.LeaveRoomResponse], error)
	// Lists effective room member IDs in ascending ID order. Resolve user details
	// with UserService.BatchGetUsers. Existing members and room.manage holders may
	// list a channel room; other nonmembers need both room.list and room.join.
	ListMembers(context.Context, *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error)
	// Gets one effective member, including automatic universal membership.
	// Channel-room members, room.manage holders, and user.manage-accounts holders
	// may read members. Bot owners and bot.manage holders may read their target
	// bots only. DMs require caller membership. Returns NOT_FOUND for nonmembers.
	GetMember(context.Context, *connect.Request[v1.GetMemberRequest]) (*connect.Response[v1.GetMemberResponse], error)
	// Gets effective member rows for the requested accounts. Uses the same
	// authorization as GetMember; omits unknown accounts and nonmembers.
	BatchGetMembers(context.Context, *connect.Request[v1.BatchGetMembersRequest]) (*connect.Response[v1.BatchGetMembersResponse], error)
	// Adds an account as an explicit channel-room member. room.manage for this
	// room or user.manage-accounts overrides the target's missing room.join.
	// Bot owners and bot.manage holders may also add bots, but without either
	// override the bot needs effective room.join, bounded by its owner's authority.
	// Preserves permission grants. Suspensions, archived, universal, and DM rooms prevent adding.
	AddMember(context.Context, *connect.Request[v1.AddMemberRequest]) (*connect.Response[v1.AddMemberResponse], error)
	// Removes an explicit channel-room member. Requires room.manage for this room,
	// user.manage-accounts, ownership of the target bot, or bot.manage.
	// Removal is allowed after room.join is lost and from archived rooms.
	// Preserves permission grants. Universal and DM membership cannot be edited.
	RemoveMember(context.Context, *connect.Request[v1.RemoveMemberRequest]) (*connect.Response[v1.RemoveMemberResponse], error)
	// Lists active channel room suspensions. Requires server-scope
	// room.remove-member.
	ListSuspensions(context.Context, *connect.Request[v1.ListSuspensionsRequest]) (*connect.Response[v1.ListSuspensionsResponse], error)
	// Lists current message-owned room attachments. Authentication and room
	// membership are required. Attachments also require message.read or a
	// matching thread relationship with message.read-interactions. The server omits attachments from
	// inaccessible threads. Returns PERMISSION_DENIED when the room is
	// inaccessible to the caller.
	ListRoomAttachments(context.Context, *connect.Request[v1.ListRoomAttachmentsRequest]) (*connect.Response[v1.ListRoomAttachmentsResponse], error)
	// Lists current pinned messages in a channel room. Room membership plus
	// message.read or message.read-interactions are required. The server omits
	// pins from threads that the caller cannot read. Direct-message rooms do not
	// support pins.
	ListPinnedMessages(context.Context, *connect.Request[v1.ListPinnedMessagesRequest]) (*connect.Response[v1.ListPinnedMessagesResponse], error)
	// Pins a current message. The caller must have room.manage and must be able
	// to read the message. Repeating an existing pin is idempotent. Direct-message
	// rooms are rejected.
	CreatePinnedMessage(context.Context, *connect.Request[v1.CreatePinnedMessageRequest]) (*connect.Response[v1.CreatePinnedMessageResponse], error)
	// Removes a current pin. The caller must have room.manage. Removing a
	// missing pin is idempotent. Direct-message rooms are rejected.
	DeletePinnedMessage(context.Context, *connect.Request[v1.DeletePinnedMessageRequest]) (*connect.Response[v1.DeletePinnedMessageResponse], error)
	// Refreshes the current user's live-only typing indicator for a room or
	// thread. Room membership is required; message posting permission is not.
	// Send at most once every 2 seconds while typing. After posting a message,
	// the next typing activity can send immediately. Stop sending when typing
	// stops; receivers clear the indicator after 6 seconds without an event.
	RefreshTypingIndicator(context.Context, *connect.Request[v1.RefreshTypingIndicatorRequest]) (*connect.Response[v1.RefreshTypingIndicatorResponse], error)
	// Returns one page of room timeline events, including related user data
	// needed to render the page. Room membership is required. Reads also require
	// message.read or message.read-interactions. The server returns only related
	// thread roots for an interaction-scoped caller.
	GetRoomEvents(context.Context, *connect.Request[v1.GetRoomEventsRequest]) (*connect.Response[v1.GetRoomEventsResponse], error)
	// Returns a room timeline window centered around a specific event. Use this to
	// open a permalink, search result, or notification target in context. Returns
	// NOT_FOUND when the anchor event is missing or not visible in the room
	// timeline. Returns PERMISSION_DENIED when room membership or both read modes
	// are missing, or when the anchor is in an unrelated thread.
	GetRoomEventsAround(context.Context, *connect.Request[v1.GetRoomEventsAroundRequest]) (*connect.Response[v1.GetRoomEventsAroundResponse], error)
	// Marks a room timeline as read through the supplied event. Room membership
	// is required. Reads also require message.read or
	// message.read-interactions. If no event
	// is supplied, the server marks through the latest root event that the caller
	// can read. Clients
	// usually call this after the user has viewed the latest visible event in the
	// room.
	MarkRoomAsRead(context.Context, *connect.Request[v1.MarkRoomAsReadRequest]) (*connect.Response[v1.MarkRoomAsReadResponse], error)
	// Removes a current channel room member with a required reason. Requires
	// room.remove-member. Without suspension, ordinary join rules apply afterward.
	// Universal rooms require a suspension. Direct-message rooms are excluded.
	RemoveUser(context.Context, *connect.Request[v1.RemoveUserRequest]) (*connect.Response[v1.RemoveUserResponse], error)
	// Lifts an active channel room suspension. Requires room.remove-member.
	// Calling this when no active suspension exists succeeds.
	LiftSuspension(context.Context, *connect.Request[v1.LiftSuspensionRequest]) (*connect.Response[v1.LiftSuspensionResponse], error)
}

// NewRoomServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRoomServiceHandler(svc RoomServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	roomServiceMethods := v1.File_chatto_api_v1_rooms_proto.Services().ByName("RoomService").Methods()
	roomServiceGetRoomReadStateHandler := connect.NewUnaryHandler(
		RoomServiceGetRoomReadStateProcedure,
		svc.GetRoomReadState,
		connect.WithSchema(roomServiceMethods.ByName("GetRoomReadState")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceBatchGetRoomReadStatesHandler := connect.NewUnaryHandler(
		RoomServiceBatchGetRoomReadStatesProcedure,
		svc.BatchGetRoomReadStates,
		connect.WithSchema(roomServiceMethods.ByName("BatchGetRoomReadStates")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceCreateRoomHandler := connect.NewUnaryHandler(
		RoomServiceCreateRoomProcedure,
		svc.CreateRoom,
		connect.WithSchema(roomServiceMethods.ByName("CreateRoom")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceUpdateRoomHandler := connect.NewUnaryHandler(
		RoomServiceUpdateRoomProcedure,
		svc.UpdateRoom,
		connect.WithSchema(roomServiceMethods.ByName("UpdateRoom")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceArchiveRoomHandler := connect.NewUnaryHandler(
		RoomServiceArchiveRoomProcedure,
		svc.ArchiveRoom,
		connect.WithSchema(roomServiceMethods.ByName("ArchiveRoom")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceUnarchiveRoomHandler := connect.NewUnaryHandler(
		RoomServiceUnarchiveRoomProcedure,
		svc.UnarchiveRoom,
		connect.WithSchema(roomServiceMethods.ByName("UnarchiveRoom")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceJoinRoomHandler := connect.NewUnaryHandler(
		RoomServiceJoinRoomProcedure,
		svc.JoinRoom,
		connect.WithSchema(roomServiceMethods.ByName("JoinRoom")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceJoinRoomGroupHandler := connect.NewUnaryHandler(
		RoomServiceJoinRoomGroupProcedure,
		svc.JoinRoomGroup,
		connect.WithSchema(roomServiceMethods.ByName("JoinRoomGroup")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceStartDMHandler := connect.NewUnaryHandler(
		RoomServiceStartDMProcedure,
		svc.StartDM,
		connect.WithSchema(roomServiceMethods.ByName("StartDM")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceLeaveRoomHandler := connect.NewUnaryHandler(
		RoomServiceLeaveRoomProcedure,
		svc.LeaveRoom,
		connect.WithSchema(roomServiceMethods.ByName("LeaveRoom")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceListMembersHandler := connect.NewUnaryHandler(
		RoomServiceListMembersProcedure,
		svc.ListMembers,
		connect.WithSchema(roomServiceMethods.ByName("ListMembers")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceGetMemberHandler := connect.NewUnaryHandler(
		RoomServiceGetMemberProcedure,
		svc.GetMember,
		connect.WithSchema(roomServiceMethods.ByName("GetMember")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceBatchGetMembersHandler := connect.NewUnaryHandler(
		RoomServiceBatchGetMembersProcedure,
		svc.BatchGetMembers,
		connect.WithSchema(roomServiceMethods.ByName("BatchGetMembers")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceAddMemberHandler := connect.NewUnaryHandler(
		RoomServiceAddMemberProcedure,
		svc.AddMember,
		connect.WithSchema(roomServiceMethods.ByName("AddMember")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceRemoveMemberHandler := connect.NewUnaryHandler(
		RoomServiceRemoveMemberProcedure,
		svc.RemoveMember,
		connect.WithSchema(roomServiceMethods.ByName("RemoveMember")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceListSuspensionsHandler := connect.NewUnaryHandler(
		RoomServiceListSuspensionsProcedure,
		svc.ListSuspensions,
		connect.WithSchema(roomServiceMethods.ByName("ListSuspensions")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceListRoomAttachmentsHandler := connect.NewUnaryHandler(
		RoomServiceListRoomAttachmentsProcedure,
		svc.ListRoomAttachments,
		connect.WithSchema(roomServiceMethods.ByName("ListRoomAttachments")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceListPinnedMessagesHandler := connect.NewUnaryHandler(
		RoomServiceListPinnedMessagesProcedure,
		svc.ListPinnedMessages,
		connect.WithSchema(roomServiceMethods.ByName("ListPinnedMessages")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceCreatePinnedMessageHandler := connect.NewUnaryHandler(
		RoomServiceCreatePinnedMessageProcedure,
		svc.CreatePinnedMessage,
		connect.WithSchema(roomServiceMethods.ByName("CreatePinnedMessage")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceDeletePinnedMessageHandler := connect.NewUnaryHandler(
		RoomServiceDeletePinnedMessageProcedure,
		svc.DeletePinnedMessage,
		connect.WithSchema(roomServiceMethods.ByName("DeletePinnedMessage")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceRefreshTypingIndicatorHandler := connect.NewUnaryHandler(
		RoomServiceRefreshTypingIndicatorProcedure,
		svc.RefreshTypingIndicator,
		connect.WithSchema(roomServiceMethods.ByName("RefreshTypingIndicator")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceGetRoomEventsHandler := connect.NewUnaryHandler(
		RoomServiceGetRoomEventsProcedure,
		svc.GetRoomEvents,
		connect.WithSchema(roomServiceMethods.ByName("GetRoomEvents")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceGetRoomEventsAroundHandler := connect.NewUnaryHandler(
		RoomServiceGetRoomEventsAroundProcedure,
		svc.GetRoomEventsAround,
		connect.WithSchema(roomServiceMethods.ByName("GetRoomEventsAround")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceMarkRoomAsReadHandler := connect.NewUnaryHandler(
		RoomServiceMarkRoomAsReadProcedure,
		svc.MarkRoomAsRead,
		connect.WithSchema(roomServiceMethods.ByName("MarkRoomAsRead")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceRemoveUserHandler := connect.NewUnaryHandler(
		RoomServiceRemoveUserProcedure,
		svc.RemoveUser,
		connect.WithSchema(roomServiceMethods.ByName("RemoveUser")),
		connect.WithHandlerOptions(opts...),
	)
	roomServiceLiftSuspensionHandler := connect.NewUnaryHandler(
		RoomServiceLiftSuspensionProcedure,
		svc.LiftSuspension,
		connect.WithSchema(roomServiceMethods.ByName("LiftSuspension")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.api.v1.RoomService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RoomServiceGetRoomReadStateProcedure:
			roomServiceGetRoomReadStateHandler.ServeHTTP(w, r)
		case RoomServiceBatchGetRoomReadStatesProcedure:
			roomServiceBatchGetRoomReadStatesHandler.ServeHTTP(w, r)
		case RoomServiceCreateRoomProcedure:
			roomServiceCreateRoomHandler.ServeHTTP(w, r)
		case RoomServiceUpdateRoomProcedure:
			roomServiceUpdateRoomHandler.ServeHTTP(w, r)
		case RoomServiceArchiveRoomProcedure:
			roomServiceArchiveRoomHandler.ServeHTTP(w, r)
		case RoomServiceUnarchiveRoomProcedure:
			roomServiceUnarchiveRoomHandler.ServeHTTP(w, r)
		case RoomServiceJoinRoomProcedure:
			roomServiceJoinRoomHandler.ServeHTTP(w, r)
		case RoomServiceJoinRoomGroupProcedure:
			roomServiceJoinRoomGroupHandler.ServeHTTP(w, r)
		case RoomServiceStartDMProcedure:
			roomServiceStartDMHandler.ServeHTTP(w, r)
		case RoomServiceLeaveRoomProcedure:
			roomServiceLeaveRoomHandler.ServeHTTP(w, r)
		case RoomServiceListMembersProcedure:
			roomServiceListMembersHandler.ServeHTTP(w, r)
		case RoomServiceGetMemberProcedure:
			roomServiceGetMemberHandler.ServeHTTP(w, r)
		case RoomServiceBatchGetMembersProcedure:
			roomServiceBatchGetMembersHandler.ServeHTTP(w, r)
		case RoomServiceAddMemberProcedure:
			roomServiceAddMemberHandler.ServeHTTP(w, r)
		case RoomServiceRemoveMemberProcedure:
			roomServiceRemoveMemberHandler.ServeHTTP(w, r)
		case RoomServiceListSuspensionsProcedure:
			roomServiceListSuspensionsHandler.ServeHTTP(w, r)
		case RoomServiceListRoomAttachmentsProcedure:
			roomServiceListRoomAttachmentsHandler.ServeHTTP(w, r)
		case RoomServiceListPinnedMessagesProcedure:
			roomServiceListPinnedMessagesHandler.ServeHTTP(w, r)
		case RoomServiceCreatePinnedMessageProcedure:
			roomServiceCreatePinnedMessageHandler.ServeHTTP(w, r)
		case RoomServiceDeletePinnedMessageProcedure:
			roomServiceDeletePinnedMessageHandler.ServeHTTP(w, r)
		case RoomServiceRefreshTypingIndicatorProcedure:
			roomServiceRefreshTypingIndicatorHandler.ServeHTTP(w, r)
		case RoomServiceGetRoomEventsProcedure:
			roomServiceGetRoomEventsHandler.ServeHTTP(w, r)
		case RoomServiceGetRoomEventsAroundProcedure:
			roomServiceGetRoomEventsAroundHandler.ServeHTTP(w, r)
		case RoomServiceMarkRoomAsReadProcedure:
			roomServiceMarkRoomAsReadHandler.ServeHTTP(w, r)
		case RoomServiceRemoveUserProcedure:
			roomServiceRemoveUserHandler.ServeHTTP(w, r)
		case RoomServiceLiftSuspensionProcedure:
			roomServiceLiftSuspensionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRoomServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRoomServiceHandler struct{}

func (UnimplementedRoomServiceHandler) GetRoomReadState(context.Context, *connect.Request[v1.GetRoomReadStateRequest]) (*connect.Response[v1.GetRoomReadStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.GetRoomReadState is not implemented"))
}

func (UnimplementedRoomServiceHandler) BatchGetRoomReadStates(context.Context, *connect.Request[v1.BatchGetRoomReadStatesRequest]) (*connect.Response[v1.BatchGetRoomReadStatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.BatchGetRoomReadStates is not implemented"))
}

func (UnimplementedRoomServiceHandler) CreateRoom(context.Context, *connect.Request[v1.CreateRoomRequest]) (*connect.Response[v1.CreateRoomResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.CreateRoom is not implemented"))
}

func (UnimplementedRoomServiceHandler) UpdateRoom(context.Context, *connect.Request[v1.UpdateRoomRequest]) (*connect.Response[v1.UpdateRoomResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.UpdateRoom is not implemented"))
}

func (UnimplementedRoomServiceHandler) ArchiveRoom(context.Context, *connect.Request[v1.ArchiveRoomRequest]) (*connect.Response[v1.ArchiveRoomResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.ArchiveRoom is not implemented"))
}

func (UnimplementedRoomServiceHandler) UnarchiveRoom(context.Context, *connect.Request[v1.UnarchiveRoomRequest]) (*connect.Response[v1.UnarchiveRoomResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.UnarchiveRoom is not implemented"))
}

func (UnimplementedRoomServiceHandler) JoinRoom(context.Context, *connect.Request[v1.JoinRoomRequest]) (*connect.Response[v1.JoinRoomResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.JoinRoom is not implemented"))
}

func (UnimplementedRoomServiceHandler) JoinRoomGroup(context.Context, *connect.Request[v1.JoinRoomGroupRequest]) (*connect.Response[v1.JoinRoomGroupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.JoinRoomGroup is not implemented"))
}

func (UnimplementedRoomServiceHandler) StartDM(context.Context, *connect.Request[v1.StartDMRequest]) (*connect.Response[v1.StartDMResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.StartDM is not implemented"))
}

func (UnimplementedRoomServiceHandler) LeaveRoom(context.Context, *connect.Request[v1.LeaveRoomRequest]) (*connect.Response[v1.LeaveRoomResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.LeaveRoom is not implemented"))
}

func (UnimplementedRoomServiceHandler) ListMembers(context.Context, *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.ListMembers is not implemented"))
}

func (UnimplementedRoomServiceHandler) GetMember(context.Context, *connect.Request[v1.GetMemberRequest]) (*connect.Response[v1.GetMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.GetMember is not implemented"))
}

func (UnimplementedRoomServiceHandler) BatchGetMembers(context.Context, *connect.Request[v1.BatchGetMembersRequest]) (*connect.Response[v1.BatchGetMembersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.BatchGetMembers is not implemented"))
}

func (UnimplementedRoomServiceHandler) AddMember(context.Context, *connect.Request[v1.AddMemberRequest]) (*connect.Response[v1.AddMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.AddMember is not implemented"))
}

func (UnimplementedRoomServiceHandler) RemoveMember(context.Context, *connect.Request[v1.RemoveMemberRequest]) (*connect.Response[v1.RemoveMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.RemoveMember is not implemented"))
}

func (UnimplementedRoomServiceHandler) ListSuspensions(context.Context, *connect.Request[v1.ListSuspensionsRequest]) (*connect.Response[v1.ListSuspensionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.ListSuspensions is not implemented"))
}

func (UnimplementedRoomServiceHandler) ListRoomAttachments(context.Context, *connect.Request[v1.ListRoomAttachmentsRequest]) (*connect.Response[v1.ListRoomAttachmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.ListRoomAttachments is not implemented"))
}

func (UnimplementedRoomServiceHandler) ListPinnedMessages(context.Context, *connect.Request[v1.ListPinnedMessagesRequest]) (*connect.Response[v1.ListPinnedMessagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.ListPinnedMessages is not implemented"))
}

func (UnimplementedRoomServiceHandler) CreatePinnedMessage(context.Context, *connect.Request[v1.CreatePinnedMessageRequest]) (*connect.Response[v1.CreatePinnedMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.CreatePinnedMessage is not implemented"))
}

func (UnimplementedRoomServiceHandler) DeletePinnedMessage(context.Context, *connect.Request[v1.DeletePinnedMessageRequest]) (*connect.Response[v1.DeletePinnedMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.DeletePinnedMessage is not implemented"))
}

func (UnimplementedRoomServiceHandler) RefreshTypingIndicator(context.Context, *connect.Request[v1.RefreshTypingIndicatorRequest]) (*connect.Response[v1.RefreshTypingIndicatorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.RefreshTypingIndicator is not implemented"))
}

func (UnimplementedRoomServiceHandler) GetRoomEvents(context.Context, *connect.Request[v1.GetRoomEventsRequest]) (*connect.Response[v1.GetRoomEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.GetRoomEvents is not implemented"))
}

func (UnimplementedRoomServiceHandler) GetRoomEventsAround(context.Context, *connect.Request[v1.GetRoomEventsAroundRequest]) (*connect.Response[v1.GetRoomEventsAroundResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.GetRoomEventsAround is not implemented"))
}

func (UnimplementedRoomServiceHandler) MarkRoomAsRead(context.Context, *connect.Request[v1.MarkRoomAsReadRequest]) (*connect.Response[v1.MarkRoomAsReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.MarkRoomAsRead is not implemented"))
}

func (UnimplementedRoomServiceHandler) RemoveUser(context.Context, *connect.Request[v1.RemoveUserRequest]) (*connect.Response[v1.RemoveUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.RemoveUser is not implemented"))
}

func (UnimplementedRoomServiceHandler) LiftSuspension(context.Context, *connect.Request[v1.LiftSuspensionRequest]) (*connect.Response[v1.LiftSuspensionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.RoomService.LiftSuspension is not implemented"))
}
