// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/realtime/v1/events.proto (package chatto.realtime.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { RoomKind } from "../../api/v1/rooms_pb.js";
import { RoomThreadingMode } from "../../api/v1/common_pb.js";
import { PresenceStatus } from "../../api/v1/presence_pb.js";

/**
 * AssetProcessingFailureCode identifies a stable processing failure class.
 *
 * @generated from enum chatto.realtime.v1.AssetProcessingFailureCode
 */
export enum AssetProcessingFailureCode {
  /**
   * The failure class is not known.
   *
   * @generated from enum value: ASSET_PROCESSING_FAILURE_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Asset processing failed without a more specific public reason.
   *
   * @generated from enum value: ASSET_PROCESSING_FAILURE_CODE_PROCESSING_FAILED = 1;
   */
  PROCESSING_FAILED = 1,

  /**
   * The source asset was not available.
   *
   * @generated from enum value: ASSET_PROCESSING_FAILURE_CODE_SOURCE_MISSING = 2;
   */
  SOURCE_MISSING = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(AssetProcessingFailureCode)
proto3.util.setEnumType(AssetProcessingFailureCode, "chatto.realtime.v1.AssetProcessingFailureCode", [
  { no: 0, name: "ASSET_PROCESSING_FAILURE_CODE_UNSPECIFIED" },
  { no: 1, name: "ASSET_PROCESSING_FAILURE_CODE_PROCESSING_FAILED" },
  { no: 2, name: "ASSET_PROCESSING_FAILURE_CODE_SOURCE_MISSING" },
]);

/**
 * A public role was created. Read its current metadata with RoleService.
 *
 * @generated from message chatto.realtime.v1.RoleCreatedEvent
 */
export class RoleCreatedEvent extends Message<RoleCreatedEvent> {
  /**
   * Stable role name.
   *
   * @generated from field: string role_name = 1;
   */
  roleName = "";

  constructor(data?: PartialMessage<RoleCreatedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RoleCreatedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoleCreatedEvent {
    return new RoleCreatedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoleCreatedEvent {
    return new RoleCreatedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoleCreatedEvent {
    return new RoleCreatedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RoleCreatedEvent | PlainMessage<RoleCreatedEvent> | undefined, b: RoleCreatedEvent | PlainMessage<RoleCreatedEvent> | undefined): boolean {
    return proto3.util.equals(RoleCreatedEvent, a, b);
  }
}

/**
 * Public role metadata changed. Read its current metadata with RoleService.
 * This event does not change permission decisions.
 *
 * @generated from message chatto.realtime.v1.RoleUpdatedEvent
 */
export class RoleUpdatedEvent extends Message<RoleUpdatedEvent> {
  /**
   * Stable role name.
   *
   * @generated from field: string role_name = 1;
   */
  roleName = "";

  constructor(data?: PartialMessage<RoleUpdatedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RoleUpdatedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoleUpdatedEvent {
    return new RoleUpdatedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoleUpdatedEvent {
    return new RoleUpdatedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoleUpdatedEvent {
    return new RoleUpdatedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RoleUpdatedEvent | PlainMessage<RoleUpdatedEvent> | undefined, b: RoleUpdatedEvent | PlainMessage<RoleUpdatedEvent> | undefined): boolean {
    return proto3.util.equals(RoleUpdatedEvent, a, b);
  }
}

/**
 * A role was deleted. Remove it from role catalogues and member role lists.
 * Clients retaining this role for their viewer must discard private cached
 * data and load current authorized state before displaying it again.
 *
 * @generated from message chatto.realtime.v1.RoleDeletedEvent
 */
export class RoleDeletedEvent extends Message<RoleDeletedEvent> {
  /**
   * Stable name of the deleted role.
   *
   * @generated from field: string role_name = 1;
   */
  roleName = "";

  constructor(data?: PartialMessage<RoleDeletedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RoleDeletedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoleDeletedEvent {
    return new RoleDeletedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoleDeletedEvent {
    return new RoleDeletedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoleDeletedEvent {
    return new RoleDeletedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RoleDeletedEvent | PlainMessage<RoleDeletedEvent> | undefined, b: RoleDeletedEvent | PlainMessage<RoleDeletedEvent> | undefined): boolean {
    return proto3.util.equals(RoleDeletedEvent, a, b);
  }
}

/**
 * Custom roles changed display order. Permission decisions are unchanged.
 *
 * @generated from message chatto.realtime.v1.RolesReorderedEvent
 */
export class RolesReorderedEvent extends Message<RolesReorderedEvent> {
  /**
   * Custom role names in ascending display position.
   *
   * @generated from field: repeated string role_names = 1;
   */
  roleNames: string[] = [];

  constructor(data?: PartialMessage<RolesReorderedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RolesReorderedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "role_names", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RolesReorderedEvent {
    return new RolesReorderedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RolesReorderedEvent {
    return new RolesReorderedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RolesReorderedEvent {
    return new RolesReorderedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RolesReorderedEvent | PlainMessage<RolesReorderedEvent> | undefined, b: RolesReorderedEvent | PlainMessage<RolesReorderedEvent> | undefined): boolean {
    return proto3.util.equals(RolesReorderedEvent, a, b);
  }
}

/**
 * A user was assigned a role. The named user's clients must discard private
 * cached data and load current authorized state. Other viewers update member
 * role lists without a full reload.
 *
 * @generated from message chatto.realtime.v1.RoleAssignedEvent
 */
export class RoleAssignedEvent extends Message<RoleAssignedEvent> {
  /**
   * User whose assignment changed.
   *
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * Stable role name.
   *
   * @generated from field: string role_name = 2;
   */
  roleName = "";

  constructor(data?: PartialMessage<RoleAssignedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RoleAssignedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoleAssignedEvent {
    return new RoleAssignedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoleAssignedEvent {
    return new RoleAssignedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoleAssignedEvent {
    return new RoleAssignedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RoleAssignedEvent | PlainMessage<RoleAssignedEvent> | undefined, b: RoleAssignedEvent | PlainMessage<RoleAssignedEvent> | undefined): boolean {
    return proto3.util.equals(RoleAssignedEvent, a, b);
  }
}

/**
 * A user's role assignment was removed. The named user's clients must discard
 * private cached data and load current authorized state.
 *
 * @generated from message chatto.realtime.v1.RoleRevokedEvent
 */
export class RoleRevokedEvent extends Message<RoleRevokedEvent> {
  /**
   * User whose assignment changed.
   *
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * Stable role name.
   *
   * @generated from field: string role_name = 2;
   */
  roleName = "";

  constructor(data?: PartialMessage<RoleRevokedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RoleRevokedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoleRevokedEvent {
    return new RoleRevokedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoleRevokedEvent {
    return new RoleRevokedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoleRevokedEvent {
    return new RoleRevokedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RoleRevokedEvent | PlainMessage<RoleRevokedEvent> | undefined, b: RoleRevokedEvent | PlainMessage<RoleRevokedEvent> | undefined): boolean {
    return proto3.util.equals(RoleRevokedEvent, a, b);
  }
}

/**
 * A role's permission decisions changed. Clients whose viewer has this role
 * must discard private cached data and load current authorized state. The
 * implicit everyone role applies to every viewer. Private scopes and permission
 * decisions are not included. Read current decisions through authorized APIs.
 *
 * @generated from message chatto.realtime.v1.RolePermissionsChangedEvent
 */
export class RolePermissionsChangedEvent extends Message<RolePermissionsChangedEvent> {
  /**
   * Stable role name.
   *
   * @generated from field: string role_name = 1;
   */
  roleName = "";

  constructor(data?: PartialMessage<RolePermissionsChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RolePermissionsChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RolePermissionsChangedEvent {
    return new RolePermissionsChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RolePermissionsChangedEvent {
    return new RolePermissionsChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RolePermissionsChangedEvent {
    return new RolePermissionsChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RolePermissionsChangedEvent | PlainMessage<RolePermissionsChangedEvent> | undefined, b: RolePermissionsChangedEvent | PlainMessage<RolePermissionsChangedEvent> | undefined): boolean {
    return proto3.util.equals(RolePermissionsChangedEvent, a, b);
  }
}

/**
 * The authenticated viewer's permission decisions may have changed. This also
 * covers changes to a bot's owner permission ceiling. Delivered only to the
 * affected viewer. Discard private cached data and load current authorized
 * state before displaying it again. The connection itself remains open.
 *
 * @generated from message chatto.realtime.v1.ViewerPermissionsChangedEvent
 */
export class ViewerPermissionsChangedEvent extends Message<ViewerPermissionsChangedEvent> {
  constructor(data?: PartialMessage<ViewerPermissionsChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.ViewerPermissionsChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ViewerPermissionsChangedEvent {
    return new ViewerPermissionsChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ViewerPermissionsChangedEvent {
    return new ViewerPermissionsChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ViewerPermissionsChangedEvent {
    return new ViewerPermissionsChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: ViewerPermissionsChangedEvent | PlainMessage<ViewerPermissionsChangedEvent> | undefined, b: ViewerPermissionsChangedEvent | PlainMessage<ViewerPermissionsChangedEvent> | undefined): boolean {
    return proto3.util.equals(ViewerPermissionsChangedEvent, a, b);
  }
}

/**
 * RoomCreatedEvent reports a new room that is visible to the caller.
 *
 * @generated from message chatto.realtime.v1.RoomCreatedEvent
 */
export class RoomCreatedEvent extends Message<RoomCreatedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string description = 3;
   */
  description = "";

  /**
   * @generated from field: chatto.api.v1.RoomKind kind = 4;
   */
  kind = RoomKind.UNSPECIFIED;

  /**
   * @generated from field: bool universal = 5;
   */
  universal = false;

  /**
   * @generated from field: chatto.api.v1.RoomThreadingMode threading_mode = 6;
   */
  threadingMode = RoomThreadingMode.UNSPECIFIED;

  constructor(data?: PartialMessage<RoomCreatedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RoomCreatedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "kind", kind: "enum", T: proto3.getEnumType(RoomKind) },
    { no: 5, name: "universal", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "threading_mode", kind: "enum", T: proto3.getEnumType(RoomThreadingMode) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomCreatedEvent {
    return new RoomCreatedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomCreatedEvent {
    return new RoomCreatedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomCreatedEvent {
    return new RoomCreatedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RoomCreatedEvent | PlainMessage<RoomCreatedEvent> | undefined, b: RoomCreatedEvent | PlainMessage<RoomCreatedEvent> | undefined): boolean {
    return proto3.util.equals(RoomCreatedEvent, a, b);
  }
}

/**
 * RoomUpdatedEvent reports changed room metadata.
 *
 * @generated from message chatto.realtime.v1.RoomUpdatedEvent
 */
export class RoomUpdatedEvent extends Message<RoomUpdatedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string description = 3;
   */
  description = "";

  constructor(data?: PartialMessage<RoomUpdatedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RoomUpdatedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomUpdatedEvent {
    return new RoomUpdatedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomUpdatedEvent {
    return new RoomUpdatedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomUpdatedEvent {
    return new RoomUpdatedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RoomUpdatedEvent | PlainMessage<RoomUpdatedEvent> | undefined, b: RoomUpdatedEvent | PlainMessage<RoomUpdatedEvent> | undefined): boolean {
    return proto3.util.equals(RoomUpdatedEvent, a, b);
  }
}

/**
 * RoomDeletedEvent reports a deleted room.
 *
 * @generated from message chatto.realtime.v1.RoomDeletedEvent
 */
export class RoomDeletedEvent extends Message<RoomDeletedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  constructor(data?: PartialMessage<RoomDeletedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RoomDeletedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomDeletedEvent {
    return new RoomDeletedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomDeletedEvent {
    return new RoomDeletedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomDeletedEvent {
    return new RoomDeletedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RoomDeletedEvent | PlainMessage<RoomDeletedEvent> | undefined, b: RoomDeletedEvent | PlainMessage<RoomDeletedEvent> | undefined): boolean {
    return proto3.util.equals(RoomDeletedEvent, a, b);
  }
}

/**
 * RoomArchivedEvent reports a room that became archived.
 *
 * @generated from message chatto.realtime.v1.RoomArchivedEvent
 */
export class RoomArchivedEvent extends Message<RoomArchivedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  constructor(data?: PartialMessage<RoomArchivedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RoomArchivedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomArchivedEvent {
    return new RoomArchivedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomArchivedEvent {
    return new RoomArchivedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomArchivedEvent {
    return new RoomArchivedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RoomArchivedEvent | PlainMessage<RoomArchivedEvent> | undefined, b: RoomArchivedEvent | PlainMessage<RoomArchivedEvent> | undefined): boolean {
    return proto3.util.equals(RoomArchivedEvent, a, b);
  }
}

/**
 * RoomUnarchivedEvent reports a room that became active again.
 *
 * @generated from message chatto.realtime.v1.RoomUnarchivedEvent
 */
export class RoomUnarchivedEvent extends Message<RoomUnarchivedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  constructor(data?: PartialMessage<RoomUnarchivedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RoomUnarchivedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomUnarchivedEvent {
    return new RoomUnarchivedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomUnarchivedEvent {
    return new RoomUnarchivedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomUnarchivedEvent {
    return new RoomUnarchivedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RoomUnarchivedEvent | PlainMessage<RoomUnarchivedEvent> | undefined, b: RoomUnarchivedEvent | PlainMessage<RoomUnarchivedEvent> | undefined): boolean {
    return proto3.util.equals(RoomUnarchivedEvent, a, b);
  }
}

/**
 * RoomUniversalChangedEvent reports the current universal-membership setting.
 *
 * @generated from message chatto.realtime.v1.RoomUniversalChangedEvent
 */
export class RoomUniversalChangedEvent extends Message<RoomUniversalChangedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: bool universal = 2;
   */
  universal = false;

  constructor(data?: PartialMessage<RoomUniversalChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RoomUniversalChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "universal", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomUniversalChangedEvent {
    return new RoomUniversalChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomUniversalChangedEvent {
    return new RoomUniversalChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomUniversalChangedEvent {
    return new RoomUniversalChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RoomUniversalChangedEvent | PlainMessage<RoomUniversalChangedEvent> | undefined, b: RoomUniversalChangedEvent | PlainMessage<RoomUniversalChangedEvent> | undefined): boolean {
    return proto3.util.equals(RoomUniversalChangedEvent, a, b);
  }
}

/**
 * RoomSlowModeChangedEvent reports the current slow-mode interval.
 *
 * @generated from message chatto.realtime.v1.RoomSlowModeChangedEvent
 */
export class RoomSlowModeChangedEvent extends Message<RoomSlowModeChangedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: uint32 slow_mode_seconds = 2;
   */
  slowModeSeconds = 0;

  constructor(data?: PartialMessage<RoomSlowModeChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RoomSlowModeChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "slow_mode_seconds", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomSlowModeChangedEvent {
    return new RoomSlowModeChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomSlowModeChangedEvent {
    return new RoomSlowModeChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomSlowModeChangedEvent {
    return new RoomSlowModeChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RoomSlowModeChangedEvent | PlainMessage<RoomSlowModeChangedEvent> | undefined, b: RoomSlowModeChangedEvent | PlainMessage<RoomSlowModeChangedEvent> | undefined): boolean {
    return proto3.util.equals(RoomSlowModeChangedEvent, a, b);
  }
}

/**
 * RoomThreadingModeChangedEvent reports the current room threading policy.
 *
 * @generated from message chatto.realtime.v1.RoomThreadingModeChangedEvent
 */
export class RoomThreadingModeChangedEvent extends Message<RoomThreadingModeChangedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: chatto.api.v1.RoomThreadingMode threading_mode = 2;
   */
  threadingMode = RoomThreadingMode.UNSPECIFIED;

  constructor(data?: PartialMessage<RoomThreadingModeChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RoomThreadingModeChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "threading_mode", kind: "enum", T: proto3.getEnumType(RoomThreadingMode) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomThreadingModeChangedEvent {
    return new RoomThreadingModeChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomThreadingModeChangedEvent {
    return new RoomThreadingModeChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomThreadingModeChangedEvent {
    return new RoomThreadingModeChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RoomThreadingModeChangedEvent | PlainMessage<RoomThreadingModeChangedEvent> | undefined, b: RoomThreadingModeChangedEvent | PlainMessage<RoomThreadingModeChangedEvent> | undefined): boolean {
    return proto3.util.equals(RoomThreadingModeChangedEvent, a, b);
  }
}

/**
 * UserJoinedRoomEvent reports that the actor joined a room.
 *
 * @generated from message chatto.realtime.v1.UserJoinedRoomEvent
 */
export class UserJoinedRoomEvent extends Message<UserJoinedRoomEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  constructor(data?: PartialMessage<UserJoinedRoomEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.UserJoinedRoomEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserJoinedRoomEvent {
    return new UserJoinedRoomEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserJoinedRoomEvent {
    return new UserJoinedRoomEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserJoinedRoomEvent {
    return new UserJoinedRoomEvent().fromJsonString(jsonString, options);
  }

  static equals(a: UserJoinedRoomEvent | PlainMessage<UserJoinedRoomEvent> | undefined, b: UserJoinedRoomEvent | PlainMessage<UserJoinedRoomEvent> | undefined): boolean {
    return proto3.util.equals(UserJoinedRoomEvent, a, b);
  }
}

/**
 * UserLeftRoomEvent reports that the actor left a room.
 *
 * @generated from message chatto.realtime.v1.UserLeftRoomEvent
 */
export class UserLeftRoomEvent extends Message<UserLeftRoomEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  constructor(data?: PartialMessage<UserLeftRoomEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.UserLeftRoomEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserLeftRoomEvent {
    return new UserLeftRoomEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserLeftRoomEvent {
    return new UserLeftRoomEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserLeftRoomEvent {
    return new UserLeftRoomEvent().fromJsonString(jsonString, options);
  }

  static equals(a: UserLeftRoomEvent | PlainMessage<UserLeftRoomEvent> | undefined, b: UserLeftRoomEvent | PlainMessage<UserLeftRoomEvent> | undefined): boolean {
    return proto3.util.equals(UserLeftRoomEvent, a, b);
  }
}

/**
 * VoiceCallParticipantJoinedEvent reports that the actor joined a call session.
 *
 * @generated from message chatto.realtime.v1.VoiceCallParticipantJoinedEvent
 */
export class VoiceCallParticipantJoinedEvent extends Message<VoiceCallParticipantJoinedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string call_id = 2;
   */
  callId = "";

  constructor(data?: PartialMessage<VoiceCallParticipantJoinedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.VoiceCallParticipantJoinedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VoiceCallParticipantJoinedEvent {
    return new VoiceCallParticipantJoinedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VoiceCallParticipantJoinedEvent {
    return new VoiceCallParticipantJoinedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VoiceCallParticipantJoinedEvent {
    return new VoiceCallParticipantJoinedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: VoiceCallParticipantJoinedEvent | PlainMessage<VoiceCallParticipantJoinedEvent> | undefined, b: VoiceCallParticipantJoinedEvent | PlainMessage<VoiceCallParticipantJoinedEvent> | undefined): boolean {
    return proto3.util.equals(VoiceCallParticipantJoinedEvent, a, b);
  }
}

/**
 * VoiceCallParticipantLeftEvent reports that the actor left a call session.
 *
 * @generated from message chatto.realtime.v1.VoiceCallParticipantLeftEvent
 */
export class VoiceCallParticipantLeftEvent extends Message<VoiceCallParticipantLeftEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string call_id = 2;
   */
  callId = "";

  constructor(data?: PartialMessage<VoiceCallParticipantLeftEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.VoiceCallParticipantLeftEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VoiceCallParticipantLeftEvent {
    return new VoiceCallParticipantLeftEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VoiceCallParticipantLeftEvent {
    return new VoiceCallParticipantLeftEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VoiceCallParticipantLeftEvent {
    return new VoiceCallParticipantLeftEvent().fromJsonString(jsonString, options);
  }

  static equals(a: VoiceCallParticipantLeftEvent | PlainMessage<VoiceCallParticipantLeftEvent> | undefined, b: VoiceCallParticipantLeftEvent | PlainMessage<VoiceCallParticipantLeftEvent> | undefined): boolean {
    return proto3.util.equals(VoiceCallParticipantLeftEvent, a, b);
  }
}

/**
 * VoiceCallStartedEvent reports a new call session.
 *
 * @generated from message chatto.realtime.v1.VoiceCallStartedEvent
 */
export class VoiceCallStartedEvent extends Message<VoiceCallStartedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string call_id = 2;
   */
  callId = "";

  constructor(data?: PartialMessage<VoiceCallStartedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.VoiceCallStartedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VoiceCallStartedEvent {
    return new VoiceCallStartedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VoiceCallStartedEvent {
    return new VoiceCallStartedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VoiceCallStartedEvent {
    return new VoiceCallStartedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: VoiceCallStartedEvent | PlainMessage<VoiceCallStartedEvent> | undefined, b: VoiceCallStartedEvent | PlainMessage<VoiceCallStartedEvent> | undefined): boolean {
    return proto3.util.equals(VoiceCallStartedEvent, a, b);
  }
}

/**
 * VoiceCallEndedEvent reports the end of a call session.
 *
 * @generated from message chatto.realtime.v1.VoiceCallEndedEvent
 */
export class VoiceCallEndedEvent extends Message<VoiceCallEndedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string call_id = 2;
   */
  callId = "";

  constructor(data?: PartialMessage<VoiceCallEndedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.VoiceCallEndedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VoiceCallEndedEvent {
    return new VoiceCallEndedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VoiceCallEndedEvent {
    return new VoiceCallEndedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VoiceCallEndedEvent {
    return new VoiceCallEndedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: VoiceCallEndedEvent | PlainMessage<VoiceCallEndedEvent> | undefined, b: VoiceCallEndedEvent | PlainMessage<VoiceCallEndedEvent> | undefined): boolean {
    return proto3.util.equals(VoiceCallEndedEvent, a, b);
  }
}

/**
 * MessagePostedEvent reports a new room message.
 *
 * @generated from message chatto.realtime.v1.MessagePostedEvent
 */
export class MessagePostedEvent extends Message<MessagePostedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string in_reply_to = 2;
   */
  inReplyTo = "";

  /**
   * Root message ID for a thread reply. Empty for a room-level message.
   *
   * @generated from field: string thread_root_event_id = 3;
   */
  threadRootEventId = "";

  /**
   * @generated from field: string echo_of_event_id = 5;
   */
  echoOfEventId = "";

  /**
   * @generated from field: string echo_from_thread_root_event_id = 6;
   */
  echoFromThreadRootEventId = "";

  /**
   * Distinct mention targets, without expanded role or broadcast recipients.
   *
   * @generated from field: repeated chatto.realtime.v1.MessageMention mentions = 7;
   */
  mentions: MessageMention[] = [];

  /**
   * Plaintext message text. The field is absent after key shredding.
   *
   * @generated from field: optional string body_plaintext = 8;
   */
  bodyPlaintext?: string;

  /**
   * Immutable room kind. Direct messages do not require a mention to address a bot.
   *
   * @generated from field: chatto.api.v1.RoomKind room_kind = 9;
   */
  roomKind = RoomKind.UNSPECIFIED;

  constructor(data?: PartialMessage<MessagePostedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.MessagePostedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "in_reply_to", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "thread_root_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "echo_of_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "echo_from_thread_root_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "mentions", kind: "message", T: MessageMention, repeated: true },
    { no: 8, name: "body_plaintext", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 9, name: "room_kind", kind: "enum", T: proto3.getEnumType(RoomKind) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessagePostedEvent {
    return new MessagePostedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessagePostedEvent {
    return new MessagePostedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessagePostedEvent {
    return new MessagePostedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: MessagePostedEvent | PlainMessage<MessagePostedEvent> | undefined, b: MessagePostedEvent | PlainMessage<MessagePostedEvent> | undefined): boolean {
    return proto3.util.equals(MessagePostedEvent, a, b);
  }
}

/**
 * DirectUserMention identifies a direct user mention.
 *
 * @generated from message chatto.realtime.v1.DirectUserMention
 */
export class DirectUserMention extends Message<DirectUserMention> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  constructor(data?: PartialMessage<DirectUserMention>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.DirectUserMention";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DirectUserMention {
    return new DirectUserMention().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DirectUserMention {
    return new DirectUserMention().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DirectUserMention {
    return new DirectUserMention().fromJsonString(jsonString, options);
  }

  static equals(a: DirectUserMention | PlainMessage<DirectUserMention> | undefined, b: DirectUserMention | PlainMessage<DirectUserMention> | undefined): boolean {
    return proto3.util.equals(DirectUserMention, a, b);
  }
}

/**
 * RoleMessageMention identifies the role that caused a mention.
 *
 * @generated from message chatto.realtime.v1.RoleMessageMention
 */
export class RoleMessageMention extends Message<RoleMessageMention> {
  /**
   * @generated from field: string role_name = 1;
   */
  roleName = "";

  constructor(data?: PartialMessage<RoleMessageMention>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RoleMessageMention";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoleMessageMention {
    return new RoleMessageMention().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoleMessageMention {
    return new RoleMessageMention().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoleMessageMention {
    return new RoleMessageMention().fromJsonString(jsonString, options);
  }

  static equals(a: RoleMessageMention | PlainMessage<RoleMessageMention> | undefined, b: RoleMessageMention | PlainMessage<RoleMessageMention> | undefined): boolean {
    return proto3.util.equals(RoleMessageMention, a, b);
  }
}

/**
 * HereMessageMention identifies a presence-scoped mention.
 *
 * @generated from message chatto.realtime.v1.HereMessageMention
 */
export class HereMessageMention extends Message<HereMessageMention> {
  constructor(data?: PartialMessage<HereMessageMention>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.HereMessageMention";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HereMessageMention {
    return new HereMessageMention().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HereMessageMention {
    return new HereMessageMention().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HereMessageMention {
    return new HereMessageMention().fromJsonString(jsonString, options);
  }

  static equals(a: HereMessageMention | PlainMessage<HereMessageMention> | undefined, b: HereMessageMention | PlainMessage<HereMessageMention> | undefined): boolean {
    return proto3.util.equals(HereMessageMention, a, b);
  }
}

/**
 * AllMessageMention identifies a room-wide mention.
 *
 * @generated from message chatto.realtime.v1.AllMessageMention
 */
export class AllMessageMention extends Message<AllMessageMention> {
  constructor(data?: PartialMessage<AllMessageMention>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.AllMessageMention";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AllMessageMention {
    return new AllMessageMention().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AllMessageMention {
    return new AllMessageMention().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AllMessageMention {
    return new AllMessageMention().fromJsonString(jsonString, options);
  }

  static equals(a: AllMessageMention | PlainMessage<AllMessageMention> | undefined, b: AllMessageMention | PlainMessage<AllMessageMention> | undefined): boolean {
    return proto3.util.equals(AllMessageMention, a, b);
  }
}

/**
 * MessageMention identifies one distinct mention target. Role, here, and all
 * targets occur once, regardless of the number of recipients. Targets with no
 * resolved recipients are omitted. Recipient decisions are from message creation,
 * including during replay; clients must not infer them from current membership.
 *
 * @generated from message chatto.realtime.v1.MessageMention
 */
export class MessageMention extends Message<MessageMention> {
  /**
   * @generated from oneof chatto.realtime.v1.MessageMention.cause
   */
  cause: {
    /**
     * @generated from field: chatto.realtime.v1.DirectUserMention direct = 2;
     */
    value: DirectUserMention;
    case: "direct";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.RoleMessageMention role = 3;
     */
    value: RoleMessageMention;
    case: "role";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.HereMessageMention here = 4;
     */
    value: HereMessageMention;
    case: "here";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.AllMessageMention all = 5;
     */
    value: AllMessageMention;
    case: "all";
  } | { case: undefined; value?: undefined } = { case: undefined };

  /**
   * True if this target included the authenticated caller when the message was posted.
   *
   * @generated from field: bool includes_viewer = 6;
   */
  includesViewer = false;

  constructor(data?: PartialMessage<MessageMention>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.MessageMention";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "direct", kind: "message", T: DirectUserMention, oneof: "cause" },
    { no: 3, name: "role", kind: "message", T: RoleMessageMention, oneof: "cause" },
    { no: 4, name: "here", kind: "message", T: HereMessageMention, oneof: "cause" },
    { no: 5, name: "all", kind: "message", T: AllMessageMention, oneof: "cause" },
    { no: 6, name: "includes_viewer", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageMention {
    return new MessageMention().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageMention {
    return new MessageMention().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageMention {
    return new MessageMention().fromJsonString(jsonString, options);
  }

  static equals(a: MessageMention | PlainMessage<MessageMention> | undefined, b: MessageMention | PlainMessage<MessageMention> | undefined): boolean {
    return proto3.util.equals(MessageMention, a, b);
  }
}

/**
 * MessageEditedEvent reports changed message content or metadata.
 *
 * @generated from message chatto.realtime.v1.MessageEditedEvent
 */
export class MessageEditedEvent extends Message<MessageEditedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string message_event_id = 2;
   */
  messageEventId = "";

  constructor(data?: PartialMessage<MessageEditedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.MessageEditedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "message_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageEditedEvent {
    return new MessageEditedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageEditedEvent {
    return new MessageEditedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageEditedEvent {
    return new MessageEditedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: MessageEditedEvent | PlainMessage<MessageEditedEvent> | undefined, b: MessageEditedEvent | PlainMessage<MessageEditedEvent> | undefined): boolean {
    return proto3.util.equals(MessageEditedEvent, a, b);
  }
}

/**
 * MessageRetractedEvent reports a retracted message.
 *
 * @generated from message chatto.realtime.v1.MessageRetractedEvent
 */
export class MessageRetractedEvent extends Message<MessageRetractedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string message_event_id = 2;
   */
  messageEventId = "";

  constructor(data?: PartialMessage<MessageRetractedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.MessageRetractedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "message_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageRetractedEvent {
    return new MessageRetractedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageRetractedEvent {
    return new MessageRetractedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageRetractedEvent {
    return new MessageRetractedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: MessageRetractedEvent | PlainMessage<MessageRetractedEvent> | undefined, b: MessageRetractedEvent | PlainMessage<MessageRetractedEvent> | undefined): boolean {
    return proto3.util.equals(MessageRetractedEvent, a, b);
  }
}

/**
 * MessagePinnedEvent reports a newly pinned message.
 *
 * @generated from message chatto.realtime.v1.MessagePinnedEvent
 */
export class MessagePinnedEvent extends Message<MessagePinnedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string message_event_id = 2;
   */
  messageEventId = "";

  constructor(data?: PartialMessage<MessagePinnedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.MessagePinnedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "message_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessagePinnedEvent {
    return new MessagePinnedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessagePinnedEvent {
    return new MessagePinnedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessagePinnedEvent {
    return new MessagePinnedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: MessagePinnedEvent | PlainMessage<MessagePinnedEvent> | undefined, b: MessagePinnedEvent | PlainMessage<MessagePinnedEvent> | undefined): boolean {
    return proto3.util.equals(MessagePinnedEvent, a, b);
  }
}

/**
 * MessageUnpinnedEvent reports a message that is no longer pinned.
 *
 * @generated from message chatto.realtime.v1.MessageUnpinnedEvent
 */
export class MessageUnpinnedEvent extends Message<MessageUnpinnedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string message_event_id = 2;
   */
  messageEventId = "";

  constructor(data?: PartialMessage<MessageUnpinnedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.MessageUnpinnedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "message_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageUnpinnedEvent {
    return new MessageUnpinnedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageUnpinnedEvent {
    return new MessageUnpinnedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageUnpinnedEvent {
    return new MessageUnpinnedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: MessageUnpinnedEvent | PlainMessage<MessageUnpinnedEvent> | undefined, b: MessageUnpinnedEvent | PlainMessage<MessageUnpinnedEvent> | undefined): boolean {
    return proto3.util.equals(MessageUnpinnedEvent, a, b);
  }
}

/**
 * ThreadCreatedEvent reports a new message thread.
 *
 * @generated from message chatto.realtime.v1.ThreadCreatedEvent
 */
export class ThreadCreatedEvent extends Message<ThreadCreatedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string thread_root_event_id = 2;
   */
  threadRootEventId = "";

  constructor(data?: PartialMessage<ThreadCreatedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.ThreadCreatedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "thread_root_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ThreadCreatedEvent {
    return new ThreadCreatedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ThreadCreatedEvent {
    return new ThreadCreatedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ThreadCreatedEvent {
    return new ThreadCreatedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: ThreadCreatedEvent | PlainMessage<ThreadCreatedEvent> | undefined, b: ThreadCreatedEvent | PlainMessage<ThreadCreatedEvent> | undefined): boolean {
    return proto3.util.equals(ThreadCreatedEvent, a, b);
  }
}

/**
 * AssetProcessingStartedEvent reports that message-asset processing started.
 *
 * @generated from message chatto.realtime.v1.AssetProcessingStartedEvent
 */
export class AssetProcessingStartedEvent extends Message<AssetProcessingStartedEvent> {
  /**
   * @generated from field: string asset_id = 1;
   */
  assetId = "";

  /**
   * @generated from field: string message_event_id = 2;
   */
  messageEventId = "";

  /**
   * Room containing the affected message.
   *
   * @generated from field: string room_id = 3;
   */
  roomId = "";

  constructor(data?: PartialMessage<AssetProcessingStartedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.AssetProcessingStartedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "asset_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "message_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AssetProcessingStartedEvent {
    return new AssetProcessingStartedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AssetProcessingStartedEvent {
    return new AssetProcessingStartedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AssetProcessingStartedEvent {
    return new AssetProcessingStartedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: AssetProcessingStartedEvent | PlainMessage<AssetProcessingStartedEvent> | undefined, b: AssetProcessingStartedEvent | PlainMessage<AssetProcessingStartedEvent> | undefined): boolean {
    return proto3.util.equals(AssetProcessingStartedEvent, a, b);
  }
}

/**
 * AssetProcessingSucceededEvent reports successful message-asset processing.
 * Read the message resource for current attachments and processed video data.
 *
 * @generated from message chatto.realtime.v1.AssetProcessingSucceededEvent
 */
export class AssetProcessingSucceededEvent extends Message<AssetProcessingSucceededEvent> {
  /**
   * @generated from field: string asset_id = 1;
   */
  assetId = "";

  /**
   * @generated from field: string message_event_id = 3;
   */
  messageEventId = "";

  /**
   * Room containing the affected message.
   *
   * @generated from field: string room_id = 4;
   */
  roomId = "";

  constructor(data?: PartialMessage<AssetProcessingSucceededEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.AssetProcessingSucceededEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "asset_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "message_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AssetProcessingSucceededEvent {
    return new AssetProcessingSucceededEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AssetProcessingSucceededEvent {
    return new AssetProcessingSucceededEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AssetProcessingSucceededEvent {
    return new AssetProcessingSucceededEvent().fromJsonString(jsonString, options);
  }

  static equals(a: AssetProcessingSucceededEvent | PlainMessage<AssetProcessingSucceededEvent> | undefined, b: AssetProcessingSucceededEvent | PlainMessage<AssetProcessingSucceededEvent> | undefined): boolean {
    return proto3.util.equals(AssetProcessingSucceededEvent, a, b);
  }
}

/**
 * AssetProcessingFailedEvent reports failed message-asset processing.
 *
 * @generated from message chatto.realtime.v1.AssetProcessingFailedEvent
 */
export class AssetProcessingFailedEvent extends Message<AssetProcessingFailedEvent> {
  /**
   * @generated from field: string asset_id = 1;
   */
  assetId = "";

  /**
   * @generated from field: chatto.realtime.v1.AssetProcessingFailureCode failure_code = 2;
   */
  failureCode = AssetProcessingFailureCode.UNSPECIFIED;

  /**
   * @generated from field: string message_event_id = 3;
   */
  messageEventId = "";

  /**
   * Room containing the affected message.
   *
   * @generated from field: string room_id = 4;
   */
  roomId = "";

  constructor(data?: PartialMessage<AssetProcessingFailedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.AssetProcessingFailedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "asset_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "failure_code", kind: "enum", T: proto3.getEnumType(AssetProcessingFailureCode) },
    { no: 3, name: "message_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AssetProcessingFailedEvent {
    return new AssetProcessingFailedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AssetProcessingFailedEvent {
    return new AssetProcessingFailedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AssetProcessingFailedEvent {
    return new AssetProcessingFailedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: AssetProcessingFailedEvent | PlainMessage<AssetProcessingFailedEvent> | undefined, b: AssetProcessingFailedEvent | PlainMessage<AssetProcessingFailedEvent> | undefined): boolean {
    return proto3.util.equals(AssetProcessingFailedEvent, a, b);
  }
}

/**
 * AttachmentChangedEvent invalidates current attachment access metadata.
 * Read the message or asset for the viewer-specific state. It does not expose
 * the audience, session capabilities, or who has viewed an attachment.
 *
 * @generated from message chatto.realtime.v1.AttachmentChangedEvent
 */
export class AttachmentChangedEvent extends Message<AttachmentChangedEvent> {
  /**
   * Source attachment asset ID.
   *
   * @generated from field: string asset_id = 1;
   */
  assetId = "";

  /**
   * Room containing the owning message.
   *
   * @generated from field: string room_id = 2;
   */
  roomId = "";

  /**
   * Message to reconcile with a viewer-specific resource read.
   *
   * @generated from field: string message_event_id = 3;
   */
  messageEventId = "";

  constructor(data?: PartialMessage<AttachmentChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.AttachmentChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "asset_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "message_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AttachmentChangedEvent {
    return new AttachmentChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AttachmentChangedEvent {
    return new AttachmentChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AttachmentChangedEvent {
    return new AttachmentChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: AttachmentChangedEvent | PlainMessage<AttachmentChangedEvent> | undefined, b: AttachmentChangedEvent | PlainMessage<AttachmentChangedEvent> | undefined): boolean {
    return proto3.util.equals(AttachmentChangedEvent, a, b);
  }
}

/**
 * AssetDeletedEvent reports a deleted asset.
 *
 * @generated from message chatto.realtime.v1.AssetDeletedEvent
 */
export class AssetDeletedEvent extends Message<AssetDeletedEvent> {
  /**
   * @generated from field: string asset_id = 1;
   */
  assetId = "";

  /**
   * Room containing the affected message.
   *
   * @generated from field: string room_id = 2;
   */
  roomId = "";

  /**
   * Message that owns the asset, including a deleted derivative asset.
   *
   * @generated from field: string message_event_id = 3;
   */
  messageEventId = "";

  constructor(data?: PartialMessage<AssetDeletedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.AssetDeletedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "asset_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "message_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AssetDeletedEvent {
    return new AssetDeletedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AssetDeletedEvent {
    return new AssetDeletedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AssetDeletedEvent {
    return new AssetDeletedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: AssetDeletedEvent | PlainMessage<AssetDeletedEvent> | undefined, b: AssetDeletedEvent | PlainMessage<AssetDeletedEvent> | undefined): boolean {
    return proto3.util.equals(AssetDeletedEvent, a, b);
  }
}

/**
 * ServerMotdChangedEvent reports the current message of the day.
 *
 * @generated from message chatto.realtime.v1.ServerMotdChangedEvent
 */
export class ServerMotdChangedEvent extends Message<ServerMotdChangedEvent> {
  /**
   * @generated from field: string motd = 1;
   */
  motd = "";

  constructor(data?: PartialMessage<ServerMotdChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.ServerMotdChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "motd", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerMotdChangedEvent {
    return new ServerMotdChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerMotdChangedEvent {
    return new ServerMotdChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerMotdChangedEvent {
    return new ServerMotdChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: ServerMotdChangedEvent | PlainMessage<ServerMotdChangedEvent> | undefined, b: ServerMotdChangedEvent | PlainMessage<ServerMotdChangedEvent> | undefined): boolean {
    return proto3.util.equals(ServerMotdChangedEvent, a, b);
  }
}

/**
 * UserAccountCreatedEvent reports a new public user account.
 *
 * @generated from message chatto.realtime.v1.UserAccountCreatedEvent
 */
export class UserAccountCreatedEvent extends Message<UserAccountCreatedEvent> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * @generated from field: bool is_bot = 2;
   */
  isBot = false;

  constructor(data?: PartialMessage<UserAccountCreatedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.UserAccountCreatedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "is_bot", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserAccountCreatedEvent {
    return new UserAccountCreatedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserAccountCreatedEvent {
    return new UserAccountCreatedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserAccountCreatedEvent {
    return new UserAccountCreatedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: UserAccountCreatedEvent | PlainMessage<UserAccountCreatedEvent> | undefined, b: UserAccountCreatedEvent | PlainMessage<UserAccountCreatedEvent> | undefined): boolean {
    return proto3.util.equals(UserAccountCreatedEvent, a, b);
  }
}

/**
 * UserAccountDeletedEvent reports a deleted user account.
 *
 * @generated from message chatto.realtime.v1.UserAccountDeletedEvent
 */
export class UserAccountDeletedEvent extends Message<UserAccountDeletedEvent> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  constructor(data?: PartialMessage<UserAccountDeletedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.UserAccountDeletedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserAccountDeletedEvent {
    return new UserAccountDeletedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserAccountDeletedEvent {
    return new UserAccountDeletedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserAccountDeletedEvent {
    return new UserAccountDeletedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: UserAccountDeletedEvent | PlainMessage<UserAccountDeletedEvent> | undefined, b: UserAccountDeletedEvent | PlainMessage<UserAccountDeletedEvent> | undefined): boolean {
    return proto3.util.equals(UserAccountDeletedEvent, a, b);
  }
}

/**
 * ReactionAddedEvent reports a new message reaction.
 *
 * @generated from message chatto.realtime.v1.ReactionAddedEvent
 */
export class ReactionAddedEvent extends Message<ReactionAddedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string message_event_id = 2;
   */
  messageEventId = "";

  /**
   * @generated from field: string emoji = 3;
   */
  emoji = "";

  constructor(data?: PartialMessage<ReactionAddedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.ReactionAddedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "message_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "emoji", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReactionAddedEvent {
    return new ReactionAddedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReactionAddedEvent {
    return new ReactionAddedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReactionAddedEvent {
    return new ReactionAddedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: ReactionAddedEvent | PlainMessage<ReactionAddedEvent> | undefined, b: ReactionAddedEvent | PlainMessage<ReactionAddedEvent> | undefined): boolean {
    return proto3.util.equals(ReactionAddedEvent, a, b);
  }
}

/**
 * ReactionRemovedEvent reports a removed message reaction.
 *
 * @generated from message chatto.realtime.v1.ReactionRemovedEvent
 */
export class ReactionRemovedEvent extends Message<ReactionRemovedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string message_event_id = 2;
   */
  messageEventId = "";

  /**
   * @generated from field: string emoji = 3;
   */
  emoji = "";

  constructor(data?: PartialMessage<ReactionRemovedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.ReactionRemovedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "message_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "emoji", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReactionRemovedEvent {
    return new ReactionRemovedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReactionRemovedEvent {
    return new ReactionRemovedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReactionRemovedEvent {
    return new ReactionRemovedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: ReactionRemovedEvent | PlainMessage<ReactionRemovedEvent> | undefined, b: ReactionRemovedEvent | PlainMessage<ReactionRemovedEvent> | undefined): boolean {
    return proto3.util.equals(ReactionRemovedEvent, a, b);
  }
}

/**
 * RoomLayoutChangedEvent reports a change to room groups, their entries, or order.
 * Refresh RoomDirectoryService.ListRoomGroups with this event's cursor as the
 * minimum boundary. The event contains no room IDs or other hidden layout data.
 *
 * @generated from message chatto.realtime.v1.RoomLayoutChangedEvent
 */
export class RoomLayoutChangedEvent extends Message<RoomLayoutChangedEvent> {
  constructor(data?: PartialMessage<RoomLayoutChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RoomLayoutChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomLayoutChangedEvent {
    return new RoomLayoutChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomLayoutChangedEvent {
    return new RoomLayoutChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomLayoutChangedEvent {
    return new RoomLayoutChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RoomLayoutChangedEvent | PlainMessage<RoomLayoutChangedEvent> | undefined, b: RoomLayoutChangedEvent | PlainMessage<RoomLayoutChangedEvent> | undefined): boolean {
    return proto3.util.equals(RoomLayoutChangedEvent, a, b);
  }
}

/**
 * UserProfileChangedEvent reports that the current public user resource changed.
 * Read the user through UserService with this event's resume cursor as the
 * minimum boundary.
 *
 * @generated from message chatto.realtime.v1.UserProfileChangedEvent
 */
export class UserProfileChangedEvent extends Message<UserProfileChangedEvent> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  constructor(data?: PartialMessage<UserProfileChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.UserProfileChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserProfileChangedEvent {
    return new UserProfileChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserProfileChangedEvent {
    return new UserProfileChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserProfileChangedEvent {
    return new UserProfileChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: UserProfileChangedEvent | PlainMessage<UserProfileChangedEvent> | undefined, b: UserProfileChangedEvent | PlainMessage<UserProfileChangedEvent> | undefined): boolean {
    return proto3.util.equals(UserProfileChangedEvent, a, b);
  }
}

/**
 * ViewerPreferencesChangedEvent reports that the caller's private user
 * preferences changed. Read ViewerService with this event's resume cursor as
 * the minimum boundary.
 *
 * @generated from message chatto.realtime.v1.ViewerPreferencesChangedEvent
 */
export class ViewerPreferencesChangedEvent extends Message<ViewerPreferencesChangedEvent> {
  constructor(data?: PartialMessage<ViewerPreferencesChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.ViewerPreferencesChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ViewerPreferencesChangedEvent {
    return new ViewerPreferencesChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ViewerPreferencesChangedEvent {
    return new ViewerPreferencesChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ViewerPreferencesChangedEvent {
    return new ViewerPreferencesChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: ViewerPreferencesChangedEvent | PlainMessage<ViewerPreferencesChangedEvent> | undefined, b: ViewerPreferencesChangedEvent | PlainMessage<ViewerPreferencesChangedEvent> | undefined): boolean {
    return proto3.util.equals(ViewerPreferencesChangedEvent, a, b);
  }
}

/**
 * ThreadViewerStateChangedEvent reports the caller's current thread state.
 *
 * @generated from message chatto.realtime.v1.ThreadViewerStateChangedEvent
 */
export class ThreadViewerStateChangedEvent extends Message<ThreadViewerStateChangedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string thread_root_event_id = 2;
   */
  threadRootEventId = "";

  /**
   * @generated from field: bool is_following = 3;
   */
  isFollowing = false;

  constructor(data?: PartialMessage<ThreadViewerStateChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.ThreadViewerStateChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "thread_root_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "is_following", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ThreadViewerStateChangedEvent {
    return new ThreadViewerStateChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ThreadViewerStateChangedEvent {
    return new ThreadViewerStateChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ThreadViewerStateChangedEvent {
    return new ThreadViewerStateChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: ThreadViewerStateChangedEvent | PlainMessage<ThreadViewerStateChangedEvent> | undefined, b: ThreadViewerStateChangedEvent | PlainMessage<ThreadViewerStateChangedEvent> | undefined): boolean {
    return proto3.util.equals(ThreadViewerStateChangedEvent, a, b);
  }
}

/**
 * ServerProfileChangedEvent reports that the public server profile changed.
 * Read ServerService with this event's resume cursor as the minimum boundary.
 *
 * @generated from message chatto.realtime.v1.ServerProfileChangedEvent
 */
export class ServerProfileChangedEvent extends Message<ServerProfileChangedEvent> {
  constructor(data?: PartialMessage<ServerProfileChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.ServerProfileChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerProfileChangedEvent {
    return new ServerProfileChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerProfileChangedEvent {
    return new ServerProfileChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerProfileChangedEvent {
    return new ServerProfileChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: ServerProfileChangedEvent | PlainMessage<ServerProfileChangedEvent> | undefined, b: ServerProfileChangedEvent | PlainMessage<ServerProfileChangedEvent> | undefined): boolean {
    return proto3.util.equals(ServerProfileChangedEvent, a, b);
  }
}

/**
 * UserTypingEvent reports current typing activity for the event actor.
 * Track each actor separately for each room and thread. Clear the indicator
 * 6 seconds after the last received typing event, or when that actor posts
 * a message in the same room or thread. No stop-typing event is sent.
 *
 * @generated from message chatto.realtime.v1.UserTypingEvent
 */
export class UserTypingEvent extends Message<UserTypingEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: optional string thread_root_event_id = 2;
   */
  threadRootEventId?: string;

  constructor(data?: PartialMessage<UserTypingEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.UserTypingEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "thread_root_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserTypingEvent {
    return new UserTypingEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserTypingEvent {
    return new UserTypingEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserTypingEvent {
    return new UserTypingEvent().fromJsonString(jsonString, options);
  }

  static equals(a: UserTypingEvent | PlainMessage<UserTypingEvent> | undefined, b: UserTypingEvent | PlainMessage<UserTypingEvent> | undefined): boolean {
    return proto3.util.equals(UserTypingEvent, a, b);
  }
}

/**
 * PresenceChangedEvent reports the actor's current presence.
 *
 * @generated from message chatto.realtime.v1.PresenceChangedEvent
 */
export class PresenceChangedEvent extends Message<PresenceChangedEvent> {
  /**
   * @generated from field: chatto.api.v1.PresenceStatus status = 1;
   */
  status = PresenceStatus.UNSPECIFIED;

  constructor(data?: PartialMessage<PresenceChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.PresenceChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "enum", T: proto3.getEnumType(PresenceStatus) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PresenceChangedEvent {
    return new PresenceChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PresenceChangedEvent {
    return new PresenceChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PresenceChangedEvent {
    return new PresenceChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: PresenceChangedEvent | PlainMessage<PresenceChangedEvent> | undefined, b: PresenceChangedEvent | PlainMessage<PresenceChangedEvent> | undefined): boolean {
    return proto3.util.equals(PresenceChangedEvent, a, b);
  }
}

/**
 * Delivered only to the account whose private availability choice changed.
 * Refetch MyAccountService.GetPresencePreference to obtain the current choice.
 *
 * @generated from message chatto.realtime.v1.ViewerPresencePreferenceChangedEvent
 */
export class ViewerPresencePreferenceChangedEvent extends Message<ViewerPresencePreferenceChangedEvent> {
  constructor(data?: PartialMessage<ViewerPresencePreferenceChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.ViewerPresencePreferenceChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ViewerPresencePreferenceChangedEvent {
    return new ViewerPresencePreferenceChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ViewerPresencePreferenceChangedEvent {
    return new ViewerPresencePreferenceChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ViewerPresencePreferenceChangedEvent {
    return new ViewerPresencePreferenceChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: ViewerPresencePreferenceChangedEvent | PlainMessage<ViewerPresencePreferenceChangedEvent> | undefined, b: ViewerPresencePreferenceChangedEvent | PlainMessage<ViewerPresencePreferenceChangedEvent> | undefined): boolean {
    return proto3.util.equals(ViewerPresencePreferenceChangedEvent, a, b);
  }
}

/**
 * NotificationOccurrencesChangedEvent reports that the caller's current
 * notification occurrences changed and requests an authoritative resource read.
 *
 * @generated from message chatto.realtime.v1.NotificationOccurrencesChangedEvent
 */
export class NotificationOccurrencesChangedEvent extends Message<NotificationOccurrencesChangedEvent> {
  /**
   * ID of a newly created notification, including read notifications and
   * creations during Do Not Disturb. Absent for updates and removals.
   * This is a best-effort live hint, not a sound instruction or durable delivery.
   * Clients decide whether to alert after they read current notification state.
   *
   * @generated from field: optional string created_notification_id = 1;
   */
  createdNotificationId?: string;

  constructor(data?: PartialMessage<NotificationOccurrencesChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.NotificationOccurrencesChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "created_notification_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NotificationOccurrencesChangedEvent {
    return new NotificationOccurrencesChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NotificationOccurrencesChangedEvent {
    return new NotificationOccurrencesChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NotificationOccurrencesChangedEvent {
    return new NotificationOccurrencesChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: NotificationOccurrencesChangedEvent | PlainMessage<NotificationOccurrencesChangedEvent> | undefined, b: NotificationOccurrencesChangedEvent | PlainMessage<NotificationOccurrencesChangedEvent> | undefined): boolean {
    return proto3.util.equals(NotificationOccurrencesChangedEvent, a, b);
  }
}

/**
 * NotificationUnreadStateChangedEvent reports that the caller's notification
 * unread state changed and requests authoritative notification and room reads.
 *
 * @generated from message chatto.realtime.v1.NotificationUnreadStateChangedEvent
 */
export class NotificationUnreadStateChangedEvent extends Message<NotificationUnreadStateChangedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Event ID of the affected thread root, or empty for room state.
   *
   * @generated from field: string thread_root_event_id = 2;
   */
  threadRootEventId = "";

  constructor(data?: PartialMessage<NotificationUnreadStateChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.NotificationUnreadStateChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "thread_root_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NotificationUnreadStateChangedEvent {
    return new NotificationUnreadStateChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NotificationUnreadStateChangedEvent {
    return new NotificationUnreadStateChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NotificationUnreadStateChangedEvent {
    return new NotificationUnreadStateChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: NotificationUnreadStateChangedEvent | PlainMessage<NotificationUnreadStateChangedEvent> | undefined, b: NotificationUnreadStateChangedEvent | PlainMessage<NotificationUnreadStateChangedEvent> | undefined): boolean {
    return proto3.util.equals(NotificationUnreadStateChangedEvent, a, b);
  }
}

/**
 * RoomReadStateChangedEvent reports the caller's current room read state.
 *
 * @generated from message chatto.realtime.v1.RoomReadStateChangedEvent
 */
export class RoomReadStateChangedEvent extends Message<RoomReadStateChangedEvent> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  constructor(data?: PartialMessage<RoomReadStateChangedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RoomReadStateChangedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomReadStateChangedEvent {
    return new RoomReadStateChangedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomReadStateChangedEvent {
    return new RoomReadStateChangedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomReadStateChangedEvent {
    return new RoomReadStateChangedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RoomReadStateChangedEvent | PlainMessage<RoomReadStateChangedEvent> | undefined, b: RoomReadStateChangedEvent | PlainMessage<RoomReadStateChangedEvent> | undefined): boolean {
    return proto3.util.equals(RoomReadStateChangedEvent, a, b);
  }
}
