// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/realtime/v1/realtime.proto (package chatto.realtime.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Duration, Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { ServerPublicProfile } from "../../api/v1/server_pb.js";
import { RoomGroup, RoomWithViewerState } from "../../api/v1/room_directory_pb.js";
import { DirectoryMember } from "../../api/v1/member_directory_pb.js";
import { ActiveCall } from "../../api/v1/voice_calls_pb.js";
import { AssetDeletedEvent, AssetProcessingFailedEvent, AssetProcessingStartedEvent, AssetProcessingSucceededEvent, AttachmentChangedEvent, MessageEditedEvent, MessagePinnedEvent, MessagePostedEvent, MessageRetractedEvent, MessageUnpinnedEvent, NotificationOccurrencesChangedEvent, NotificationUnreadStateChangedEvent, PresenceChangedEvent, ReactionAddedEvent, ReactionRemovedEvent, RoleAssignedEvent, RoleCreatedEvent, RoleDeletedEvent, RolePermissionsChangedEvent, RoleRevokedEvent, RolesReorderedEvent, RoleUpdatedEvent, RoomArchivedEvent, RoomCreatedEvent, RoomDeletedEvent, RoomLayoutChangedEvent, RoomReadStateChangedEvent, RoomSlowModeChangedEvent, RoomThreadingModeChangedEvent, RoomUnarchivedEvent, RoomUniversalChangedEvent, RoomUpdatedEvent, ServerMotdChangedEvent, ServerProfileChangedEvent, ThreadCreatedEvent, ThreadViewerStateChangedEvent, UserAccountCreatedEvent, UserAccountDeletedEvent, UserJoinedRoomEvent, UserLeftRoomEvent, UserProfileChangedEvent, UserTypingEvent, ViewerPermissionsChangedEvent, ViewerPreferencesChangedEvent, ViewerPresencePreferenceChangedEvent, VoiceCallEndedEvent, VoiceCallParticipantJoinedEvent, VoiceCallParticipantLeftEvent, VoiceCallStartedEvent } from "./events_pb.js";

/**
 * Startup behavior when a subscription cannot resume from its cursor.
 *
 * @generated from enum chatto.realtime.v1.RealtimeInitialState
 */
export enum RealtimeInitialState {
  /**
   * Invalid value. The server rejects subscriptions that use it.
   *
   * @generated from enum value: REALTIME_INITIAL_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Start at the current event boundary without sending current resources.
   *
   * @generated from enum value: REALTIME_INITIAL_STATE_LIVE_ONLY = 1;
   */
  LIVE_ONLY = 1,

  /**
   * Send an exact authorized snapshot before later public events.
   *
   * @generated from enum value: REALTIME_INITIAL_STATE_SNAPSHOT = 2;
   */
  SNAPSHOT = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(RealtimeInitialState)
proto3.util.setEnumType(RealtimeInitialState, "chatto.realtime.v1.RealtimeInitialState", [
  { no: 0, name: "REALTIME_INITIAL_STATE_UNSPECIFIED" },
  { no: 1, name: "REALTIME_INITIAL_STATE_LIVE_ONLY" },
  { no: 2, name: "REALTIME_INITIAL_STATE_SNAPSHOT" },
]);

/**
 * How the server reached the live-delivery boundary.
 *
 * @generated from enum chatto.realtime.v1.RealtimeRecovery
 */
export enum RealtimeRecovery {
  /**
   * Invalid value. The server always supplies a recovery result.
   *
   * @generated from enum value: REALTIME_RECOVERY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The requested cursor was accepted and all available authorized events followed it.
   *
   * @generated from enum value: REALTIME_RECOVERY_RESUMED = 1;
   */
  RESUMED = 1,

  /**
   * The server sent a replacement snapshot.
   *
   * @generated from enum value: REALTIME_RECOVERY_SNAPSHOT = 2;
   */
  SNAPSHOT = 2,

  /**
   * The server started at the current boundary without past events or resources.
   *
   * @generated from enum value: REALTIME_RECOVERY_LIVE_ONLY = 3;
   */
  LIVE_ONLY = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(RealtimeRecovery)
proto3.util.setEnumType(RealtimeRecovery, "chatto.realtime.v1.RealtimeRecovery", [
  { no: 0, name: "REALTIME_RECOVERY_UNSPECIFIED" },
  { no: 1, name: "REALTIME_RECOVERY_RESUMED" },
  { no: 2, name: "REALTIME_RECOVERY_SNAPSHOT" },
  { no: 3, name: "REALTIME_RECOVERY_LIVE_ONLY" },
]);

/**
 * Stable server-requested close category.
 *
 * @generated from enum chatto.realtime.v1.RealtimeCloseCode
 */
export enum RealtimeCloseCode {
  /**
   * Invalid or unknown close code.
   *
   * @generated from enum value: REALTIME_CLOSE_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The subscription message is malformed or contains an invalid value.
   *
   * @generated from enum value: REALTIME_CLOSE_CODE_INVALID_REQUEST = 1;
   */
  INVALID_REQUEST = 1,

  /**
   * The requested behavioral protocol version is not supported.
   *
   * @generated from enum value: REALTIME_CLOSE_CODE_UNSUPPORTED_PROTOCOL = 2;
   */
  UNSUPPORTED_PROTOCOL = 2,

  /**
   * The server cannot accept or continue a realtime session at present.
   *
   * @generated from enum value: REALTIME_CLOSE_CODE_TEMPORARILY_UNAVAILABLE = 3;
   */
  TEMPORARILY_UNAVAILABLE = 3,

  /**
   * The caller is no longer authenticated.
   *
   * @generated from enum value: REALTIME_CLOSE_CODE_AUTHENTICATION_REQUIRED = 4;
   */
  AUTHENTICATION_REQUIRED = 4,

  /**
   * The caller must renew its session before reconnecting.
   *
   * @generated from enum value: REALTIME_CLOSE_CODE_SESSION_RENEWAL_REQUIRED = 5;
   */
  SESSION_RENEWAL_REQUIRED = 5,

  /**
   * The client must discard its cursor and synchronize current state again.
   *
   * @generated from enum value: REALTIME_CLOSE_CODE_RESYNC_REQUIRED = 6;
   */
  RESYNC_REQUIRED = 6,

  /**
   * The user's session ended and the client must return to sign-in.
   *
   * @generated from enum value: REALTIME_CLOSE_CODE_SESSION_TERMINATED = 7;
   */
  SESSION_TERMINATED = 7,

  /**
   * Privileged mode expired. Reconnect and refresh effective viewer and room permissions.
   *
   * @generated from enum value: REALTIME_CLOSE_CODE_PRIVILEGED_MODE_EXPIRED = 8;
   */
  PRIVILEGED_MODE_EXPIRED = 8,
}
// Retrieve enum metadata with: proto3.getEnumType(RealtimeCloseCode)
proto3.util.setEnumType(RealtimeCloseCode, "chatto.realtime.v1.RealtimeCloseCode", [
  { no: 0, name: "REALTIME_CLOSE_CODE_UNSPECIFIED" },
  { no: 1, name: "REALTIME_CLOSE_CODE_INVALID_REQUEST" },
  { no: 2, name: "REALTIME_CLOSE_CODE_UNSUPPORTED_PROTOCOL" },
  { no: 3, name: "REALTIME_CLOSE_CODE_TEMPORARILY_UNAVAILABLE" },
  { no: 4, name: "REALTIME_CLOSE_CODE_AUTHENTICATION_REQUIRED" },
  { no: 5, name: "REALTIME_CLOSE_CODE_SESSION_RENEWAL_REQUIRED" },
  { no: 6, name: "REALTIME_CLOSE_CODE_RESYNC_REQUIRED" },
  { no: 7, name: "REALTIME_CLOSE_CODE_SESSION_TERMINATED" },
  { no: 8, name: "REALTIME_CLOSE_CODE_PRIVILEGED_MODE_EXPIRED" },
]);

/**
 * Starts one authorized public realtime subscription.
 *
 * The client sends this message as the first binary WebSocket message. The
 * client does not send more application messages on the socket.
 *
 * @generated from message chatto.realtime.v1.RealtimeSubscribe
 */
export class RealtimeSubscribe extends Message<RealtimeSubscribe> {
  /**
   * Behavioral protocol version requested by the client. The only supported
   * version is 4.
   *
   * @generated from field: uint32 protocol_version = 1;
   */
  protocolVersion = 0;

  /**
   * Optional bearer token. When present, it takes precedence over cookie auth.
   *
   * @generated from field: optional string bearer_token = 2;
   */
  bearerToken?: string;

  /**
   * Opaque cursor from a previously received replayable event or `caught_up`
   * frame. A usable cursor receives bounded authorized events after
   * that position. Cursors expire 15 minutes after issue.
   *
   * @generated from field: optional string resume_cursor = 3;
   */
  resumeCursor?: string;

  /**
   * Required fallback when the cursor is absent or cannot resume safely.
   *
   * @generated from field: chatto.realtime.v1.RealtimeInitialState initial_state = 4;
   */
  initialState = RealtimeInitialState.UNSPECIFIED;

  constructor(data?: PartialMessage<RealtimeSubscribe>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RealtimeSubscribe";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "protocol_version", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "bearer_token", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "resume_cursor", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "initial_state", kind: "enum", T: proto3.getEnumType(RealtimeInitialState) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RealtimeSubscribe {
    return new RealtimeSubscribe().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RealtimeSubscribe {
    return new RealtimeSubscribe().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RealtimeSubscribe {
    return new RealtimeSubscribe().fromJsonString(jsonString, options);
  }

  static equals(a: RealtimeSubscribe | PlainMessage<RealtimeSubscribe> | undefined, b: RealtimeSubscribe | PlainMessage<RealtimeSubscribe> | undefined): boolean {
    return proto3.util.equals(RealtimeSubscribe, a, b);
  }
}

/**
 * Server-to-client frame for Chatto's protobuf WebSocket realtime protocol.
 *
 * @generated from message chatto.realtime.v1.RealtimeServerFrame
 */
export class RealtimeServerFrame extends Message<RealtimeServerFrame> {
  /**
   * @generated from oneof chatto.realtime.v1.RealtimeServerFrame.frame
   */
  frame: {
    /**
     * One authorized public event copy.
     *
     * @generated from field: chatto.realtime.v1.RealtimeEvent event = 1;
     */
    value: RealtimeEvent;
    case: "event";
  } | {
    /**
     * Application-level heartbeat used for liveness checks.
     *
     * @generated from field: chatto.realtime.v1.RealtimeHeartbeat heartbeat = 2;
     */
    value: RealtimeHeartbeat;
    case: "heartbeat";
  } | {
    /**
     * Server-requested close with reconnect guidance.
     *
     * @generated from field: chatto.realtime.v1.RealtimeClose close = 3;
     */
    value: RealtimeClose;
    case: "close";
  } | {
    /**
     * Confirms that recovery reached the live-stream boundary.
     *
     * @generated from field: chatto.realtime.v1.RealtimeCaughtUp caught_up = 4;
     */
    value: RealtimeCaughtUp;
    case: "caughtUp";
  } | {
    /**
     * One exact authorized server-content snapshot.
     *
     * @generated from field: chatto.realtime.v1.RealtimeSnapshot snapshot = 5;
     */
    value: RealtimeSnapshot;
    case: "snapshot";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<RealtimeServerFrame>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RealtimeServerFrame";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event", kind: "message", T: RealtimeEvent, oneof: "frame" },
    { no: 2, name: "heartbeat", kind: "message", T: RealtimeHeartbeat, oneof: "frame" },
    { no: 3, name: "close", kind: "message", T: RealtimeClose, oneof: "frame" },
    { no: 4, name: "caught_up", kind: "message", T: RealtimeCaughtUp, oneof: "frame" },
    { no: 5, name: "snapshot", kind: "message", T: RealtimeSnapshot, oneof: "frame" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RealtimeServerFrame {
    return new RealtimeServerFrame().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RealtimeServerFrame {
    return new RealtimeServerFrame().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RealtimeServerFrame {
    return new RealtimeServerFrame().fromJsonString(jsonString, options);
  }

  static equals(a: RealtimeServerFrame | PlainMessage<RealtimeServerFrame> | undefined, b: RealtimeServerFrame | PlainMessage<RealtimeServerFrame> | undefined): boolean {
    return proto3.util.equals(RealtimeServerFrame, a, b);
  }
}

/**
 * One authorized snapshot of the current bounded server content.
 *
 * The server sends at most one snapshot before `caught_up`. The client must
 * discard the snapshot if the socket closes before `caught_up`. List values
 * replace the complete local family.
 * Large and paginated resources, such as message history, are not part of the
 * snapshot and remain available through ConnectRPC.
 *
 * @generated from message chatto.realtime.v1.RealtimeSnapshot
 */
export class RealtimeSnapshot extends Message<RealtimeSnapshot> {
  /**
   * Current public server profile.
   *
   * @generated from field: chatto.api.v1.ServerPublicProfile server = 1;
   */
  server?: ServerPublicProfile;

  /**
   * All rooms visible to the caller at the snapshot boundary.
   *
   * @generated from field: repeated chatto.api.v1.RoomWithViewerState rooms = 2;
   */
  rooms: RoomWithViewerState[] = [];

  /**
   * All room groups visible to the caller at the snapshot boundary.
   *
   * @generated from field: repeated chatto.api.v1.RoomGroup room_groups = 3;
   */
  roomGroups: RoomGroup[] = [];

  /**
   * The viewer and public users referenced by another snapshot family.
   *
   * @generated from field: repeated chatto.api.v1.DirectoryMember users = 4;
   */
  users: DirectoryMember[] = [];

  /**
   * All active calls visible to the caller at the snapshot boundary.
   *
   * @generated from field: repeated chatto.api.v1.ActiveCall active_calls = 5;
   */
  activeCalls: ActiveCall[] = [];

  constructor(data?: PartialMessage<RealtimeSnapshot>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RealtimeSnapshot";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "server", kind: "message", T: ServerPublicProfile },
    { no: 2, name: "rooms", kind: "message", T: RoomWithViewerState, repeated: true },
    { no: 3, name: "room_groups", kind: "message", T: RoomGroup, repeated: true },
    { no: 4, name: "users", kind: "message", T: DirectoryMember, repeated: true },
    { no: 5, name: "active_calls", kind: "message", T: ActiveCall, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RealtimeSnapshot {
    return new RealtimeSnapshot().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RealtimeSnapshot {
    return new RealtimeSnapshot().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RealtimeSnapshot {
    return new RealtimeSnapshot().fromJsonString(jsonString, options);
  }

  static equals(a: RealtimeSnapshot | PlainMessage<RealtimeSnapshot> | undefined, b: RealtimeSnapshot | PlainMessage<RealtimeSnapshot> | undefined): boolean {
    return proto3.util.equals(RealtimeSnapshot, a, b);
  }
}

/**
 * Confirms that recovery is complete and live delivery has begun.
 *
 * Clients can retain `cursor` after they apply every preceding event.
 *
 * @generated from message chatto.realtime.v1.RealtimeCaughtUp
 */
export class RealtimeCaughtUp extends Message<RealtimeCaughtUp> {
  /**
   * Opaque cursor at the recovery-to-live handoff boundary.
   *
   * @generated from field: string cursor = 1;
   */
  cursor = "";

  /**
   * Actual recovery result, including a successful replay with no events.
   *
   * @generated from field: chatto.realtime.v1.RealtimeRecovery recovery = 2;
   */
  recovery = RealtimeRecovery.UNSPECIFIED;

  constructor(data?: PartialMessage<RealtimeCaughtUp>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RealtimeCaughtUp";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "cursor", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "recovery", kind: "enum", T: proto3.getEnumType(RealtimeRecovery) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RealtimeCaughtUp {
    return new RealtimeCaughtUp().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RealtimeCaughtUp {
    return new RealtimeCaughtUp().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RealtimeCaughtUp {
    return new RealtimeCaughtUp().fromJsonString(jsonString, options);
  }

  static equals(a: RealtimeCaughtUp | PlainMessage<RealtimeCaughtUp> | undefined, b: RealtimeCaughtUp | PlainMessage<RealtimeCaughtUp> | undefined): boolean {
    return proto3.util.equals(RealtimeCaughtUp, a, b);
  }
}

/**
 * One authorized public event with its optional cursor.
 *
 * Each payload uses a realtime-owned public message. The union is the public
 * event catalogue. An internal event that is absent from this union is not
 * part of the realtime API. The server creates a fresh caller-specific value
 * after authorization. An event has a resume cursor when it can be replayed.
 * An event without a cursor is safe to miss, or its state can be restored from
 * a snapshot or a ConnectRPC resource.
 *
 * @generated from message chatto.realtime.v1.RealtimeEvent
 */
export class RealtimeEvent extends Message<RealtimeEvent> {
  /**
   * Universal event identifier (NanoID).
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * Time when the source event was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 2;
   */
  createdAt?: Timestamp;

  /**
   * ID of the user that caused the event. Absence means no user actor.
   *
   * @generated from field: optional string actor_id = 3;
   */
  actorId?: string;

  /**
   * Opaque cursor safe to retain after this complete event is accepted.
   *
   * @generated from field: optional string cursor = 4;
   */
  cursor?: string;

  /**
   * Authorized semantic payload.
   *
   * @generated from oneof chatto.realtime.v1.RealtimeEvent.event
   */
  event: {
    /**
     * @generated from field: chatto.realtime.v1.RoomCreatedEvent room_created = 10;
     */
    value: RoomCreatedEvent;
    case: "roomCreated";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.RoomUpdatedEvent room_updated = 11;
     */
    value: RoomUpdatedEvent;
    case: "roomUpdated";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.RoomDeletedEvent room_deleted = 12;
     */
    value: RoomDeletedEvent;
    case: "roomDeleted";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.RoomArchivedEvent room_archived = 13;
     */
    value: RoomArchivedEvent;
    case: "roomArchived";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.RoomUnarchivedEvent room_unarchived = 14;
     */
    value: RoomUnarchivedEvent;
    case: "roomUnarchived";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.RoomUniversalChangedEvent room_universal_changed = 15;
     */
    value: RoomUniversalChangedEvent;
    case: "roomUniversalChanged";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.RoomSlowModeChangedEvent room_slow_mode_changed = 16;
     */
    value: RoomSlowModeChangedEvent;
    case: "roomSlowModeChanged";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.RoomThreadingModeChangedEvent room_threading_mode_changed = 17;
     */
    value: RoomThreadingModeChangedEvent;
    case: "roomThreadingModeChanged";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.UserJoinedRoomEvent user_joined_room = 18;
     */
    value: UserJoinedRoomEvent;
    case: "userJoinedRoom";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.UserLeftRoomEvent user_left_room = 19;
     */
    value: UserLeftRoomEvent;
    case: "userLeftRoom";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.VoiceCallParticipantJoinedEvent voice_call_participant_joined = 20;
     */
    value: VoiceCallParticipantJoinedEvent;
    case: "voiceCallParticipantJoined";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.VoiceCallParticipantLeftEvent voice_call_participant_left = 21;
     */
    value: VoiceCallParticipantLeftEvent;
    case: "voiceCallParticipantLeft";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.VoiceCallStartedEvent voice_call_started = 22;
     */
    value: VoiceCallStartedEvent;
    case: "voiceCallStarted";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.VoiceCallEndedEvent voice_call_ended = 23;
     */
    value: VoiceCallEndedEvent;
    case: "voiceCallEnded";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.MessagePostedEvent message_posted = 24;
     */
    value: MessagePostedEvent;
    case: "messagePosted";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.MessageEditedEvent message_edited = 25;
     */
    value: MessageEditedEvent;
    case: "messageEdited";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.MessageRetractedEvent message_retracted = 26;
     */
    value: MessageRetractedEvent;
    case: "messageRetracted";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.MessagePinnedEvent message_pinned = 27;
     */
    value: MessagePinnedEvent;
    case: "messagePinned";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.MessageUnpinnedEvent message_unpinned = 28;
     */
    value: MessageUnpinnedEvent;
    case: "messageUnpinned";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.ThreadCreatedEvent thread_created = 29;
     */
    value: ThreadCreatedEvent;
    case: "threadCreated";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.AssetProcessingStartedEvent asset_processing_started = 30;
     */
    value: AssetProcessingStartedEvent;
    case: "assetProcessingStarted";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.AssetProcessingSucceededEvent asset_processing_succeeded = 31;
     */
    value: AssetProcessingSucceededEvent;
    case: "assetProcessingSucceeded";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.AssetProcessingFailedEvent asset_processing_failed = 32;
     */
    value: AssetProcessingFailedEvent;
    case: "assetProcessingFailed";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.AssetDeletedEvent asset_deleted = 33;
     */
    value: AssetDeletedEvent;
    case: "assetDeleted";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.ServerMotdChangedEvent server_motd_changed = 34;
     */
    value: ServerMotdChangedEvent;
    case: "serverMotdChanged";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.UserAccountCreatedEvent user_account_created = 46;
     */
    value: UserAccountCreatedEvent;
    case: "userAccountCreated";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.UserProfileChangedEvent user_profile_changed = 47;
     */
    value: UserProfileChangedEvent;
    case: "userProfileChanged";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.UserAccountDeletedEvent user_account_deleted = 48;
     */
    value: UserAccountDeletedEvent;
    case: "userAccountDeleted";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.ReactionAddedEvent reaction_added = 49;
     */
    value: ReactionAddedEvent;
    case: "reactionAdded";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.ReactionRemovedEvent reaction_removed = 50;
     */
    value: ReactionRemovedEvent;
    case: "reactionRemoved";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.ViewerPreferencesChangedEvent viewer_preferences_changed = 51;
     */
    value: ViewerPreferencesChangedEvent;
    case: "viewerPreferencesChanged";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.ThreadViewerStateChangedEvent thread_viewer_state_changed = 52;
     */
    value: ThreadViewerStateChangedEvent;
    case: "threadViewerStateChanged";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.ServerProfileChangedEvent server_profile_changed = 53;
     */
    value: ServerProfileChangedEvent;
    case: "serverProfileChanged";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.UserTypingEvent user_typing = 54;
     */
    value: UserTypingEvent;
    case: "userTyping";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.PresenceChangedEvent presence_changed = 55;
     */
    value: PresenceChangedEvent;
    case: "presenceChanged";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.NotificationOccurrencesChangedEvent notification_occurrences_changed = 56;
     */
    value: NotificationOccurrencesChangedEvent;
    case: "notificationOccurrencesChanged";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.NotificationUnreadStateChangedEvent notification_unread_state_changed = 57;
     */
    value: NotificationUnreadStateChangedEvent;
    case: "notificationUnreadStateChanged";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.RoomReadStateChangedEvent room_read_state_changed = 58;
     */
    value: RoomReadStateChangedEvent;
    case: "roomReadStateChanged";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.RoomLayoutChangedEvent room_layout_changed = 59;
     */
    value: RoomLayoutChangedEvent;
    case: "roomLayoutChanged";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.RoleCreatedEvent role_created = 60;
     */
    value: RoleCreatedEvent;
    case: "roleCreated";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.RoleUpdatedEvent role_updated = 61;
     */
    value: RoleUpdatedEvent;
    case: "roleUpdated";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.RoleDeletedEvent role_deleted = 62;
     */
    value: RoleDeletedEvent;
    case: "roleDeleted";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.RolesReorderedEvent roles_reordered = 63;
     */
    value: RolesReorderedEvent;
    case: "rolesReordered";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.RoleAssignedEvent role_assigned = 64;
     */
    value: RoleAssignedEvent;
    case: "roleAssigned";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.RoleRevokedEvent role_revoked = 65;
     */
    value: RoleRevokedEvent;
    case: "roleRevoked";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.RolePermissionsChangedEvent role_permissions_changed = 66;
     */
    value: RolePermissionsChangedEvent;
    case: "rolePermissionsChanged";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.ViewerPermissionsChangedEvent viewer_permissions_changed = 67;
     */
    value: ViewerPermissionsChangedEvent;
    case: "viewerPermissionsChanged";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.ViewerPresencePreferenceChangedEvent viewer_presence_preference_changed = 68;
     */
    value: ViewerPresencePreferenceChangedEvent;
    case: "viewerPresencePreferenceChanged";
  } | {
    /**
     * @generated from field: chatto.realtime.v1.AttachmentChangedEvent attachment_changed = 69;
     */
    value: AttachmentChangedEvent;
    case: "attachmentChanged";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<RealtimeEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RealtimeEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "created_at", kind: "message", T: Timestamp },
    { no: 3, name: "actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "cursor", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 10, name: "room_created", kind: "message", T: RoomCreatedEvent, oneof: "event" },
    { no: 11, name: "room_updated", kind: "message", T: RoomUpdatedEvent, oneof: "event" },
    { no: 12, name: "room_deleted", kind: "message", T: RoomDeletedEvent, oneof: "event" },
    { no: 13, name: "room_archived", kind: "message", T: RoomArchivedEvent, oneof: "event" },
    { no: 14, name: "room_unarchived", kind: "message", T: RoomUnarchivedEvent, oneof: "event" },
    { no: 15, name: "room_universal_changed", kind: "message", T: RoomUniversalChangedEvent, oneof: "event" },
    { no: 16, name: "room_slow_mode_changed", kind: "message", T: RoomSlowModeChangedEvent, oneof: "event" },
    { no: 17, name: "room_threading_mode_changed", kind: "message", T: RoomThreadingModeChangedEvent, oneof: "event" },
    { no: 18, name: "user_joined_room", kind: "message", T: UserJoinedRoomEvent, oneof: "event" },
    { no: 19, name: "user_left_room", kind: "message", T: UserLeftRoomEvent, oneof: "event" },
    { no: 20, name: "voice_call_participant_joined", kind: "message", T: VoiceCallParticipantJoinedEvent, oneof: "event" },
    { no: 21, name: "voice_call_participant_left", kind: "message", T: VoiceCallParticipantLeftEvent, oneof: "event" },
    { no: 22, name: "voice_call_started", kind: "message", T: VoiceCallStartedEvent, oneof: "event" },
    { no: 23, name: "voice_call_ended", kind: "message", T: VoiceCallEndedEvent, oneof: "event" },
    { no: 24, name: "message_posted", kind: "message", T: MessagePostedEvent, oneof: "event" },
    { no: 25, name: "message_edited", kind: "message", T: MessageEditedEvent, oneof: "event" },
    { no: 26, name: "message_retracted", kind: "message", T: MessageRetractedEvent, oneof: "event" },
    { no: 27, name: "message_pinned", kind: "message", T: MessagePinnedEvent, oneof: "event" },
    { no: 28, name: "message_unpinned", kind: "message", T: MessageUnpinnedEvent, oneof: "event" },
    { no: 29, name: "thread_created", kind: "message", T: ThreadCreatedEvent, oneof: "event" },
    { no: 30, name: "asset_processing_started", kind: "message", T: AssetProcessingStartedEvent, oneof: "event" },
    { no: 31, name: "asset_processing_succeeded", kind: "message", T: AssetProcessingSucceededEvent, oneof: "event" },
    { no: 32, name: "asset_processing_failed", kind: "message", T: AssetProcessingFailedEvent, oneof: "event" },
    { no: 33, name: "asset_deleted", kind: "message", T: AssetDeletedEvent, oneof: "event" },
    { no: 34, name: "server_motd_changed", kind: "message", T: ServerMotdChangedEvent, oneof: "event" },
    { no: 46, name: "user_account_created", kind: "message", T: UserAccountCreatedEvent, oneof: "event" },
    { no: 47, name: "user_profile_changed", kind: "message", T: UserProfileChangedEvent, oneof: "event" },
    { no: 48, name: "user_account_deleted", kind: "message", T: UserAccountDeletedEvent, oneof: "event" },
    { no: 49, name: "reaction_added", kind: "message", T: ReactionAddedEvent, oneof: "event" },
    { no: 50, name: "reaction_removed", kind: "message", T: ReactionRemovedEvent, oneof: "event" },
    { no: 51, name: "viewer_preferences_changed", kind: "message", T: ViewerPreferencesChangedEvent, oneof: "event" },
    { no: 52, name: "thread_viewer_state_changed", kind: "message", T: ThreadViewerStateChangedEvent, oneof: "event" },
    { no: 53, name: "server_profile_changed", kind: "message", T: ServerProfileChangedEvent, oneof: "event" },
    { no: 54, name: "user_typing", kind: "message", T: UserTypingEvent, oneof: "event" },
    { no: 55, name: "presence_changed", kind: "message", T: PresenceChangedEvent, oneof: "event" },
    { no: 56, name: "notification_occurrences_changed", kind: "message", T: NotificationOccurrencesChangedEvent, oneof: "event" },
    { no: 57, name: "notification_unread_state_changed", kind: "message", T: NotificationUnreadStateChangedEvent, oneof: "event" },
    { no: 58, name: "room_read_state_changed", kind: "message", T: RoomReadStateChangedEvent, oneof: "event" },
    { no: 59, name: "room_layout_changed", kind: "message", T: RoomLayoutChangedEvent, oneof: "event" },
    { no: 60, name: "role_created", kind: "message", T: RoleCreatedEvent, oneof: "event" },
    { no: 61, name: "role_updated", kind: "message", T: RoleUpdatedEvent, oneof: "event" },
    { no: 62, name: "role_deleted", kind: "message", T: RoleDeletedEvent, oneof: "event" },
    { no: 63, name: "roles_reordered", kind: "message", T: RolesReorderedEvent, oneof: "event" },
    { no: 64, name: "role_assigned", kind: "message", T: RoleAssignedEvent, oneof: "event" },
    { no: 65, name: "role_revoked", kind: "message", T: RoleRevokedEvent, oneof: "event" },
    { no: 66, name: "role_permissions_changed", kind: "message", T: RolePermissionsChangedEvent, oneof: "event" },
    { no: 67, name: "viewer_permissions_changed", kind: "message", T: ViewerPermissionsChangedEvent, oneof: "event" },
    { no: 68, name: "viewer_presence_preference_changed", kind: "message", T: ViewerPresencePreferenceChangedEvent, oneof: "event" },
    { no: 69, name: "attachment_changed", kind: "message", T: AttachmentChangedEvent, oneof: "event" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RealtimeEvent {
    return new RealtimeEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RealtimeEvent {
    return new RealtimeEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RealtimeEvent {
    return new RealtimeEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RealtimeEvent | PlainMessage<RealtimeEvent> | undefined, b: RealtimeEvent | PlainMessage<RealtimeEvent> | undefined): boolean {
    return proto3.util.equals(RealtimeEvent, a, b);
  }
}

/**
 * Application-level heartbeat.
 *
 * @generated from message chatto.realtime.v1.RealtimeHeartbeat
 */
export class RealtimeHeartbeat extends Message<RealtimeHeartbeat> {
  /**
   * Fresh resume cursor for the latest replay boundary delivered on this
   * socket. A client can retain it only after all earlier frames have been
   * applied.
   *
   * @generated from field: optional string cursor = 1;
   */
  cursor?: string;

  constructor(data?: PartialMessage<RealtimeHeartbeat>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RealtimeHeartbeat";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "cursor", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RealtimeHeartbeat {
    return new RealtimeHeartbeat().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RealtimeHeartbeat {
    return new RealtimeHeartbeat().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RealtimeHeartbeat {
    return new RealtimeHeartbeat().fromJsonString(jsonString, options);
  }

  static equals(a: RealtimeHeartbeat | PlainMessage<RealtimeHeartbeat> | undefined, b: RealtimeHeartbeat | PlainMessage<RealtimeHeartbeat> | undefined): boolean {
    return proto3.util.equals(RealtimeHeartbeat, a, b);
  }
}

/**
 * Close instruction sent before the socket closes when possible.
 *
 * @generated from message chatto.realtime.v1.RealtimeClose
 */
export class RealtimeClose extends Message<RealtimeClose> {
  /**
   * Stable machine-readable close code.
   *
   * @generated from field: chatto.realtime.v1.RealtimeCloseCode code = 1;
   */
  code = RealtimeCloseCode.UNSPECIFIED;

  /**
   * Safe human-readable close message.
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * Whether the client should reconnect automatically.
   *
   * @generated from field: bool reconnect = 3;
   */
  reconnect = false;

  /**
   * Suggested delay before reconnect.
   *
   * @generated from field: google.protobuf.Duration retry_after = 4;
   */
  retryAfter?: Duration;

  constructor(data?: PartialMessage<RealtimeClose>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.realtime.v1.RealtimeClose";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "code", kind: "enum", T: proto3.getEnumType(RealtimeCloseCode) },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "reconnect", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "retry_after", kind: "message", T: Duration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RealtimeClose {
    return new RealtimeClose().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RealtimeClose {
    return new RealtimeClose().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RealtimeClose {
    return new RealtimeClose().fromJsonString(jsonString, options);
  }

  static equals(a: RealtimeClose | PlainMessage<RealtimeClose> | undefined, b: RealtimeClose | PlainMessage<RealtimeClose> | undefined): boolean {
    return proto3.util.equals(RealtimeClose, a, b);
  }
}
