// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: chatto/api/v1/account.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to update or add the authenticated user's password.
type ChangePasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New password. The server applies the same password policy as registration
	// and password reset.
	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	// Current password. Required when the account already has a password; omitted
	// when adding the first password to a passwordless account.
	CurrentPassword string `protobuf:"bytes,2,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *ChangePasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ChangePasswordRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

// Result of updating or adding the authenticated account password.
type ChangePasswordResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current authenticated user profile after the password update.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *ChangePasswordResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// One email address that the authenticated user has proved they control.
type VerifiedEmail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Normalized email address.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Time at which the address was verified.
	VerifiedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	// Whether account-directed email is sent to this address.
	Primary       bool `protobuf:"varint,3,opt,name=primary,proto3" json:"primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifiedEmail) Reset() {
	*x = VerifiedEmail{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifiedEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifiedEmail) ProtoMessage() {}

func (x *VerifiedEmail) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifiedEmail.ProtoReflect.Descriptor instead.
func (*VerifiedEmail) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *VerifiedEmail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifiedEmail) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *VerifiedEmail) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

// Request the authenticated user's verified email addresses. expected_user_id
// binds the request to the account state that the client currently displays.
// The server returns FAILED_PRECONDITION if the authenticated account changed.
type ListVerifiedEmailsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID that the client expects to be authenticated.
	ExpectedUserId string `protobuf:"bytes,1,opt,name=expected_user_id,json=expectedUserId,proto3" json:"expected_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListVerifiedEmailsRequest) Reset() {
	*x = ListVerifiedEmailsRequest{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVerifiedEmailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerifiedEmailsRequest) ProtoMessage() {}

func (x *ListVerifiedEmailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerifiedEmailsRequest.ProtoReflect.Descriptor instead.
func (*ListVerifiedEmailsRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *ListVerifiedEmailsRequest) GetExpectedUserId() string {
	if x != nil {
		return x.ExpectedUserId
	}
	return ""
}

// Verified email addresses for the authenticated user.
type ListVerifiedEmailsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VerifiedEmails []*VerifiedEmail       `protobuf:"bytes,1,rep,name=verified_emails,json=verifiedEmails,proto3" json:"verified_emails,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListVerifiedEmailsResponse) Reset() {
	*x = ListVerifiedEmailsResponse{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVerifiedEmailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerifiedEmailsResponse) ProtoMessage() {}

func (x *ListVerifiedEmailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerifiedEmailsResponse.ProtoReflect.Descriptor instead.
func (*ListVerifiedEmailsResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{4}
}

func (x *ListVerifiedEmailsResponse) GetVerifiedEmails() []*VerifiedEmail {
	if x != nil {
		return x.VerifiedEmails
	}
	return nil
}

// Request a short-lived verification code for an email address.
type RequestEmailVerificationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New address to verify and add to the authenticated user's account.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// User ID that the client expects to be authenticated.
	ExpectedUserId string `protobuf:"bytes,2,opt,name=expected_user_id,json=expectedUserId,proto3" json:"expected_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestEmailVerificationRequest) Reset() {
	*x = RequestEmailVerificationRequest{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEmailVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEmailVerificationRequest) ProtoMessage() {}

func (x *RequestEmailVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEmailVerificationRequest.ProtoReflect.Descriptor instead.
func (*RequestEmailVerificationRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{5}
}

func (x *RequestEmailVerificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RequestEmailVerificationRequest) GetExpectedUserId() string {
	if x != nil {
		return x.ExpectedUserId
	}
	return ""
}

// Result of requesting an email verification code.
type RequestEmailVerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEmailVerificationResponse) Reset() {
	*x = RequestEmailVerificationResponse{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEmailVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEmailVerificationResponse) ProtoMessage() {}

func (x *RequestEmailVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEmailVerificationResponse.ProtoReflect.Descriptor instead.
func (*RequestEmailVerificationResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{6}
}

// Confirm control of an email address with a verification code.
type ConfirmEmailVerificationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Address that received the verification code.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Six-digit code that the server sent to the address.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// User ID that the client expects to be authenticated.
	ExpectedUserId string `protobuf:"bytes,3,opt,name=expected_user_id,json=expectedUserId,proto3" json:"expected_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfirmEmailVerificationRequest) Reset() {
	*x = ConfirmEmailVerificationRequest{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmEmailVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEmailVerificationRequest) ProtoMessage() {}

func (x *ConfirmEmailVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEmailVerificationRequest.ProtoReflect.Descriptor instead.
func (*ConfirmEmailVerificationRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{7}
}

func (x *ConfirmEmailVerificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ConfirmEmailVerificationRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ConfirmEmailVerificationRequest) GetExpectedUserId() string {
	if x != nil {
		return x.ExpectedUserId
	}
	return ""
}

// Verified email addresses after a successful confirmation.
type ConfirmEmailVerificationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VerifiedEmails []*VerifiedEmail       `protobuf:"bytes,1,rep,name=verified_emails,json=verifiedEmails,proto3" json:"verified_emails,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfirmEmailVerificationResponse) Reset() {
	*x = ConfirmEmailVerificationResponse{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmEmailVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEmailVerificationResponse) ProtoMessage() {}

func (x *ConfirmEmailVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEmailVerificationResponse.ProtoReflect.Descriptor instead.
func (*ConfirmEmailVerificationResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmEmailVerificationResponse) GetVerifiedEmails() []*VerifiedEmail {
	if x != nil {
		return x.VerifiedEmails
	}
	return nil
}

// Select a verified email for account-directed email.
type SetPrimaryEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Verified address to select as primary.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// User ID that the client expects to be authenticated.
	ExpectedUserId string `protobuf:"bytes,2,opt,name=expected_user_id,json=expectedUserId,proto3" json:"expected_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetPrimaryEmailRequest) Reset() {
	*x = SetPrimaryEmailRequest{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPrimaryEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPrimaryEmailRequest) ProtoMessage() {}

func (x *SetPrimaryEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPrimaryEmailRequest.ProtoReflect.Descriptor instead.
func (*SetPrimaryEmailRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{9}
}

func (x *SetPrimaryEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SetPrimaryEmailRequest) GetExpectedUserId() string {
	if x != nil {
		return x.ExpectedUserId
	}
	return ""
}

// Verified email addresses after the primary address changes.
type SetPrimaryEmailResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VerifiedEmails []*VerifiedEmail       `protobuf:"bytes,1,rep,name=verified_emails,json=verifiedEmails,proto3" json:"verified_emails,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetPrimaryEmailResponse) Reset() {
	*x = SetPrimaryEmailResponse{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPrimaryEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPrimaryEmailResponse) ProtoMessage() {}

func (x *SetPrimaryEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPrimaryEmailResponse.ProtoReflect.Descriptor instead.
func (*SetPrimaryEmailResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{10}
}

func (x *SetPrimaryEmailResponse) GetVerifiedEmails() []*VerifiedEmail {
	if x != nil {
		return x.VerifiedEmails
	}
	return nil
}

// Request the authenticated user's display preferences. Human and bot accounts
// use the same operation; no target account ID is accepted.
type GetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{11}
}

// Current display preferences, with defaults for settings not yet saved.
type GetSettingsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The same settings resource returned by UpdateSettings and GetViewer.
	Settings      *UserSettings `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsResponse) Reset() {
	*x = GetSettingsResponse{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsResponse) ProtoMessage() {}

func (x *GetSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetSettingsResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{12}
}

func (x *GetSettingsResponse) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// Request to patch the authenticated user's display preferences. update_mask
// selects fields to apply or reset. Resetting timezone clears the override.
type UpdateSettingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IANA timezone override. Empty clears the override.
	Timezone *string `protobuf:"bytes,1,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	// Preferred time format. UNSPECIFIED restores the automatic format.
	TimeFormat *TimeFormat `protobuf:"varint,2,opt,name=time_format,json=timeFormat,proto3,enum=chatto.api.v1.TimeFormat,oneof" json:"time_format,omitempty"`
	// Whether the stored time zone may appear on the user's public profile.
	ShareTimezone *bool `protobuf:"varint,3,opt,name=share_timezone,json=shareTimezone,proto3,oneof" json:"share_timezone,omitempty"`
	// Editable fields to apply or reset: timezone, time_format, share_timezone.
	// Omit to infer populated fields; * selects all editable fields. An explicit
	// empty mask is invalid. Unselected values are ignored. Selected absent values
	// reset the field to its default, subject to field validation.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingsRequest) Reset() {
	*x = UpdateSettingsRequest{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsRequest) ProtoMessage() {}

func (x *UpdateSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSettingsRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateSettingsRequest) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

func (x *UpdateSettingsRequest) GetTimeFormat() TimeFormat {
	if x != nil && x.TimeFormat != nil {
		return *x.TimeFormat
	}
	return TimeFormat_TIME_FORMAT_UNSPECIFIED
}

func (x *UpdateSettingsRequest) GetShareTimezone() bool {
	if x != nil && x.ShareTimezone != nil {
		return *x.ShareTimezone
	}
	return false
}

func (x *UpdateSettingsRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// Result of updating display preferences.
type UpdateSettingsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stored settings after merging the request.
	Settings      *UserSettings `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingsResponse) Reset() {
	*x = UpdateSettingsResponse{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsResponse) ProtoMessage() {}

func (x *UpdateSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateSettingsResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateSettingsResponse) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// Hide or restore one DM for the authenticated account on all its clients.
type SetDMVisibilityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Existing DM in which the authenticated account is a participant.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// True hides the conversation; false restores it.
	Hidden        bool `protobuf:"varint,2,opt,name=hidden,proto3" json:"hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDMVisibilityRequest) Reset() {
	*x = SetDMVisibilityRequest{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDMVisibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDMVisibilityRequest) ProtoMessage() {}

func (x *SetDMVisibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDMVisibilityRequest.ProtoReflect.Descriptor instead.
func (*SetDMVisibilityRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{15}
}

func (x *SetDMVisibilityRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SetDMVisibilityRequest) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

// Private preferences after applying the visibility choice.
type SetDMVisibilityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The same settings resource returned by GetViewer and GetSettings.
	Settings      *UserSettings `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDMVisibilityResponse) Reset() {
	*x = SetDMVisibilityResponse{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDMVisibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDMVisibilityResponse) ProtoMessage() {}

func (x *SetDMVisibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDMVisibilityResponse.ProtoReflect.Descriptor instead.
func (*SetDMVisibilityResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{16}
}

func (x *SetDMVisibilityResponse) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// Request a short-lived confirmation token for deleting the authenticated
// account.
type RequestAccountDeletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAccountDeletionRequest) Reset() {
	*x = RequestAccountDeletionRequest{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccountDeletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccountDeletionRequest) ProtoMessage() {}

func (x *RequestAccountDeletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccountDeletionRequest.ProtoReflect.Descriptor instead.
func (*RequestAccountDeletionRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{17}
}

// Result of issuing an account deletion confirmation token.
type RequestAccountDeletionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Confirmation token. Clients must pass this to DeleteMyAccount.
	ConfirmationToken string `protobuf:"bytes,1,opt,name=confirmation_token,json=confirmationToken,proto3" json:"confirmation_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RequestAccountDeletionResponse) Reset() {
	*x = RequestAccountDeletionResponse{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccountDeletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccountDeletionResponse) ProtoMessage() {}

func (x *RequestAccountDeletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccountDeletionResponse.ProtoReflect.Descriptor instead.
func (*RequestAccountDeletionResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{18}
}

func (x *RequestAccountDeletionResponse) GetConfirmationToken() string {
	if x != nil {
		return x.ConfirmationToken
	}
	return ""
}

// Request to permanently delete the authenticated account.
type DeleteMyAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Confirmation token obtained from RequestAccountDeletion.
	ConfirmationToken string `protobuf:"bytes,1,opt,name=confirmation_token,json=confirmationToken,proto3" json:"confirmation_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteMyAccountRequest) Reset() {
	*x = DeleteMyAccountRequest{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMyAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMyAccountRequest) ProtoMessage() {}

func (x *DeleteMyAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMyAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteMyAccountRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteMyAccountRequest) GetConfirmationToken() string {
	if x != nil {
		return x.ConfirmationToken
	}
	return ""
}

// Result of deleting the authenticated account.
type DeleteMyAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMyAccountResponse) Reset() {
	*x = DeleteMyAccountResponse{}
	mi := &file_chatto_api_v1_account_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMyAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMyAccountResponse) ProtoMessage() {}

func (x *DeleteMyAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_account_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMyAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteMyAccountResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_account_proto_rawDescGZIP(), []int{20}
}

var File_chatto_api_v1_account_proto protoreflect.FileDescriptor

const file_chatto_api_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x1bchatto/api/v1/account.proto\x12\rchatto.api.v1\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\x1a'chatto/api/v1/external_identities.proto\x1a\x1cchatto/api/v1/presence.proto\x1a\x1fchatto/api/v1/user_status.proto\x1a\x19chatto/api/v1/users.proto\x1a\x1achatto/api/v1/viewer.proto\"t\n" +
	"\x15ChangePasswordRequest\x12&\n" +
	"\bpassword\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\b\x18\x80\x01R\bpassword\x123\n" +
	"\x10current_password\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01R\x0fcurrentPassword\"A\n" +
	"\x16ChangePasswordResponse\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.chatto.api.v1.UserR\x04user\"|\n" +
	"\rVerifiedEmail\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12;\n" +
	"\vverified_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\x12\x18\n" +
	"\aprimary\x18\x03 \x01(\bR\aprimary\"N\n" +
	"\x19ListVerifiedEmailsRequest\x121\n" +
	"\x10expected_user_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eexpectedUserId\"c\n" +
	"\x1aListVerifiedEmailsResponse\x12E\n" +
	"\x0fverified_emails\x18\x01 \x03(\v2\x1c.chatto.api.v1.VerifiedEmailR\x0everifiedEmails\"v\n" +
	"\x1fRequestEmailVerificationRequest\x12 \n" +
	"\x05email\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x18\xfe\x01`\x01R\x05email\x121\n" +
	"\x10expected_user_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eexpectedUserId\"\"\n" +
	" RequestEmailVerificationResponse\"\x95\x01\n" +
	"\x1fConfirmEmailVerificationRequest\x12 \n" +
	"\x05email\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x18\xfe\x01`\x01R\x05email\x12\x1d\n" +
	"\x04code\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18 R\x04code\x121\n" +
	"\x10expected_user_id\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eexpectedUserId\"i\n" +
	" ConfirmEmailVerificationResponse\x12E\n" +
	"\x0fverified_emails\x18\x01 \x03(\v2\x1c.chatto.api.v1.VerifiedEmailR\x0everifiedEmails\"m\n" +
	"\x16SetPrimaryEmailRequest\x12 \n" +
	"\x05email\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x18\xfe\x01`\x01R\x05email\x121\n" +
	"\x10expected_user_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eexpectedUserId\"`\n" +
	"\x17SetPrimaryEmailResponse\x12E\n" +
	"\x0fverified_emails\x18\x01 \x03(\v2\x1c.chatto.api.v1.VerifiedEmailR\x0everifiedEmails\"\x14\n" +
	"\x12GetSettingsRequest\"N\n" +
	"\x13GetSettingsResponse\x127\n" +
	"\bsettings\x18\x01 \x01(\v2\x1b.chatto.api.v1.UserSettingsR\bsettings\"\x9c\x02\n" +
	"\x15UpdateSettingsRequest\x12\x1f\n" +
	"\btimezone\x18\x01 \x01(\tH\x00R\btimezone\x88\x01\x01\x12I\n" +
	"\vtime_format\x18\x02 \x01(\x0e2\x19.chatto.api.v1.TimeFormatB\b\xbaH\x05\x82\x01\x02\x10\x01H\x01R\n" +
	"timeFormat\x88\x01\x01\x12*\n" +
	"\x0eshare_timezone\x18\x03 \x01(\bH\x02R\rshareTimezone\x88\x01\x01\x12;\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMaskB\v\n" +
	"\t_timezoneB\x0e\n" +
	"\f_time_formatB\x11\n" +
	"\x0f_share_timezone\"Q\n" +
	"\x16UpdateSettingsResponse\x127\n" +
	"\bsettings\x18\x01 \x01(\v2\x1b.chatto.api.v1.UserSettingsR\bsettings\"R\n" +
	"\x16SetDMVisibilityRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x12\x16\n" +
	"\x06hidden\x18\x02 \x01(\bR\x06hidden\"R\n" +
	"\x17SetDMVisibilityResponse\x127\n" +
	"\bsettings\x18\x01 \x01(\v2\x1b.chatto.api.v1.UserSettingsR\bsettings\"\x1f\n" +
	"\x1dRequestAccountDeletionRequest\"O\n" +
	"\x1eRequestAccountDeletionResponse\x12-\n" +
	"\x12confirmation_token\x18\x01 \x01(\tR\x11confirmationToken\"G\n" +
	"\x16DeleteMyAccountRequest\x12-\n" +
	"\x12confirmation_token\x18\x01 \x01(\tR\x11confirmationToken\"(\n" +
	"\x17DeleteMyAccountResponseJ\x04\b\x01\x10\x02R\adeleted2\x9f\x10\n" +
	"\x10MyAccountService\x12]\n" +
	"\x0eChangePassword\x12$.chatto.api.v1.ChangePasswordRequest\x1a%.chatto.api.v1.ChangePasswordResponse\x12n\n" +
	"\x12ListVerifiedEmails\x12(.chatto.api.v1.ListVerifiedEmailsRequest\x1a).chatto.api.v1.ListVerifiedEmailsResponse\"\x03\x90\x02\x01\x12{\n" +
	"\x18RequestEmailVerification\x12..chatto.api.v1.RequestEmailVerificationRequest\x1a/.chatto.api.v1.RequestEmailVerificationResponse\x12{\n" +
	"\x18ConfirmEmailVerification\x12..chatto.api.v1.ConfirmEmailVerificationRequest\x1a/.chatto.api.v1.ConfirmEmailVerificationResponse\x12`\n" +
	"\x0fSetPrimaryEmail\x12%.chatto.api.v1.SetPrimaryEmailRequest\x1a&.chatto.api.v1.SetPrimaryEmailResponse\x12T\n" +
	"\vGetSettings\x12!.chatto.api.v1.GetSettingsRequest\x1a\".chatto.api.v1.GetSettingsResponse\x12]\n" +
	"\x0eUpdateSettings\x12$.chatto.api.v1.UpdateSettingsRequest\x1a%.chatto.api.v1.UpdateSettingsResponse\x12e\n" +
	"\x0fSetDMVisibility\x12%.chatto.api.v1.SetDMVisibilityRequest\x1a&.chatto.api.v1.SetDMVisibilityResponse\"\x03\x90\x02\x02\x12u\n" +
	"\x16ListExternalIdentities\x12,.chatto.api.v1.ListExternalIdentitiesRequest\x1a-.chatto.api.v1.ListExternalIdentitiesResponse\x12~\n" +
	"\x19StartExternalIdentityLink\x12/.chatto.api.v1.StartExternalIdentityLinkRequest\x1a0.chatto.api.v1.StartExternalIdentityLinkResponse\x12\x81\x01\n" +
	"\x1aDisconnectExternalIdentity\x120.chatto.api.v1.DisconnectExternalIdentityRequest\x1a1.chatto.api.v1.DisconnectExternalIdentityResponse\x12T\n" +
	"\vSetPresence\x12!.chatto.api.v1.SetPresenceRequest\x1a\".chatto.api.v1.SetPresenceResponse\x12r\n" +
	"\x15GetPresencePreference\x12+.chatto.api.v1.GetPresencePreferenceRequest\x1a,.chatto.api.v1.GetPresencePreferenceResponse\x12r\n" +
	"\x15SetPresencePreference\x12+.chatto.api.v1.SetPresencePreferenceRequest\x1a,.chatto.api.v1.SetPresencePreferenceResponse\x12`\n" +
	"\x0fRefreshPresence\x12%.chatto.api.v1.RefreshPresenceRequest\x1a&.chatto.api.v1.RefreshPresenceResponse\x12`\n" +
	"\x0fSetCustomStatus\x12%.chatto.api.v1.SetCustomStatusRequest\x1a&.chatto.api.v1.SetCustomStatusResponse\x12n\n" +
	"\x12DeleteCustomStatus\x12(.chatto.api.v1.DeleteCustomStatusRequest\x1a).chatto.api.v1.DeleteCustomStatusResponse\"\x03\x90\x02\x02\x12u\n" +
	"\x16RequestAccountDeletion\x12,.chatto.api.v1.RequestAccountDeletionRequest\x1a-.chatto.api.v1.RequestAccountDeletionResponse\x12`\n" +
	"\x0fDeleteMyAccount\x12%.chatto.api.v1.DeleteMyAccountRequest\x1a&.chatto.api.v1.DeleteMyAccountResponseB\xa8\x01\n" +
	"\x11com.chatto.api.v1B\fAccountProtoP\x01Z/hmans.de/chatto/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_account_proto_rawDescOnce sync.Once
	file_chatto_api_v1_account_proto_rawDescData []byte
)

func file_chatto_api_v1_account_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_account_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_account_proto_rawDesc), len(file_chatto_api_v1_account_proto_rawDesc)))
	})
	return file_chatto_api_v1_account_proto_rawDescData
}

var file_chatto_api_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_chatto_api_v1_account_proto_goTypes = []any{
	(*ChangePasswordRequest)(nil),              // 0: chatto.api.v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil),             // 1: chatto.api.v1.ChangePasswordResponse
	(*VerifiedEmail)(nil),                      // 2: chatto.api.v1.VerifiedEmail
	(*ListVerifiedEmailsRequest)(nil),          // 3: chatto.api.v1.ListVerifiedEmailsRequest
	(*ListVerifiedEmailsResponse)(nil),         // 4: chatto.api.v1.ListVerifiedEmailsResponse
	(*RequestEmailVerificationRequest)(nil),    // 5: chatto.api.v1.RequestEmailVerificationRequest
	(*RequestEmailVerificationResponse)(nil),   // 6: chatto.api.v1.RequestEmailVerificationResponse
	(*ConfirmEmailVerificationRequest)(nil),    // 7: chatto.api.v1.ConfirmEmailVerificationRequest
	(*ConfirmEmailVerificationResponse)(nil),   // 8: chatto.api.v1.ConfirmEmailVerificationResponse
	(*SetPrimaryEmailRequest)(nil),             // 9: chatto.api.v1.SetPrimaryEmailRequest
	(*SetPrimaryEmailResponse)(nil),            // 10: chatto.api.v1.SetPrimaryEmailResponse
	(*GetSettingsRequest)(nil),                 // 11: chatto.api.v1.GetSettingsRequest
	(*GetSettingsResponse)(nil),                // 12: chatto.api.v1.GetSettingsResponse
	(*UpdateSettingsRequest)(nil),              // 13: chatto.api.v1.UpdateSettingsRequest
	(*UpdateSettingsResponse)(nil),             // 14: chatto.api.v1.UpdateSettingsResponse
	(*SetDMVisibilityRequest)(nil),             // 15: chatto.api.v1.SetDMVisibilityRequest
	(*SetDMVisibilityResponse)(nil),            // 16: chatto.api.v1.SetDMVisibilityResponse
	(*RequestAccountDeletionRequest)(nil),      // 17: chatto.api.v1.RequestAccountDeletionRequest
	(*RequestAccountDeletionResponse)(nil),     // 18: chatto.api.v1.RequestAccountDeletionResponse
	(*DeleteMyAccountRequest)(nil),             // 19: chatto.api.v1.DeleteMyAccountRequest
	(*DeleteMyAccountResponse)(nil),            // 20: chatto.api.v1.DeleteMyAccountResponse
	(*User)(nil),                               // 21: chatto.api.v1.User
	(*timestamppb.Timestamp)(nil),              // 22: google.protobuf.Timestamp
	(*UserSettings)(nil),                       // 23: chatto.api.v1.UserSettings
	(TimeFormat)(0),                            // 24: chatto.api.v1.TimeFormat
	(*fieldmaskpb.FieldMask)(nil),              // 25: google.protobuf.FieldMask
	(*ListExternalIdentitiesRequest)(nil),      // 26: chatto.api.v1.ListExternalIdentitiesRequest
	(*StartExternalIdentityLinkRequest)(nil),   // 27: chatto.api.v1.StartExternalIdentityLinkRequest
	(*DisconnectExternalIdentityRequest)(nil),  // 28: chatto.api.v1.DisconnectExternalIdentityRequest
	(*SetPresenceRequest)(nil),                 // 29: chatto.api.v1.SetPresenceRequest
	(*GetPresencePreferenceRequest)(nil),       // 30: chatto.api.v1.GetPresencePreferenceRequest
	(*SetPresencePreferenceRequest)(nil),       // 31: chatto.api.v1.SetPresencePreferenceRequest
	(*RefreshPresenceRequest)(nil),             // 32: chatto.api.v1.RefreshPresenceRequest
	(*SetCustomStatusRequest)(nil),             // 33: chatto.api.v1.SetCustomStatusRequest
	(*DeleteCustomStatusRequest)(nil),          // 34: chatto.api.v1.DeleteCustomStatusRequest
	(*ListExternalIdentitiesResponse)(nil),     // 35: chatto.api.v1.ListExternalIdentitiesResponse
	(*StartExternalIdentityLinkResponse)(nil),  // 36: chatto.api.v1.StartExternalIdentityLinkResponse
	(*DisconnectExternalIdentityResponse)(nil), // 37: chatto.api.v1.DisconnectExternalIdentityResponse
	(*SetPresenceResponse)(nil),                // 38: chatto.api.v1.SetPresenceResponse
	(*GetPresencePreferenceResponse)(nil),      // 39: chatto.api.v1.GetPresencePreferenceResponse
	(*SetPresencePreferenceResponse)(nil),      // 40: chatto.api.v1.SetPresencePreferenceResponse
	(*RefreshPresenceResponse)(nil),            // 41: chatto.api.v1.RefreshPresenceResponse
	(*SetCustomStatusResponse)(nil),            // 42: chatto.api.v1.SetCustomStatusResponse
	(*DeleteCustomStatusResponse)(nil),         // 43: chatto.api.v1.DeleteCustomStatusResponse
}
var file_chatto_api_v1_account_proto_depIdxs = []int32{
	21, // 0: chatto.api.v1.ChangePasswordResponse.user:type_name -> chatto.api.v1.User
	22, // 1: chatto.api.v1.VerifiedEmail.verified_at:type_name -> google.protobuf.Timestamp
	2,  // 2: chatto.api.v1.ListVerifiedEmailsResponse.verified_emails:type_name -> chatto.api.v1.VerifiedEmail
	2,  // 3: chatto.api.v1.ConfirmEmailVerificationResponse.verified_emails:type_name -> chatto.api.v1.VerifiedEmail
	2,  // 4: chatto.api.v1.SetPrimaryEmailResponse.verified_emails:type_name -> chatto.api.v1.VerifiedEmail
	23, // 5: chatto.api.v1.GetSettingsResponse.settings:type_name -> chatto.api.v1.UserSettings
	24, // 6: chatto.api.v1.UpdateSettingsRequest.time_format:type_name -> chatto.api.v1.TimeFormat
	25, // 7: chatto.api.v1.UpdateSettingsRequest.update_mask:type_name -> google.protobuf.FieldMask
	23, // 8: chatto.api.v1.UpdateSettingsResponse.settings:type_name -> chatto.api.v1.UserSettings
	23, // 9: chatto.api.v1.SetDMVisibilityResponse.settings:type_name -> chatto.api.v1.UserSettings
	0,  // 10: chatto.api.v1.MyAccountService.ChangePassword:input_type -> chatto.api.v1.ChangePasswordRequest
	3,  // 11: chatto.api.v1.MyAccountService.ListVerifiedEmails:input_type -> chatto.api.v1.ListVerifiedEmailsRequest
	5,  // 12: chatto.api.v1.MyAccountService.RequestEmailVerification:input_type -> chatto.api.v1.RequestEmailVerificationRequest
	7,  // 13: chatto.api.v1.MyAccountService.ConfirmEmailVerification:input_type -> chatto.api.v1.ConfirmEmailVerificationRequest
	9,  // 14: chatto.api.v1.MyAccountService.SetPrimaryEmail:input_type -> chatto.api.v1.SetPrimaryEmailRequest
	11, // 15: chatto.api.v1.MyAccountService.GetSettings:input_type -> chatto.api.v1.GetSettingsRequest
	13, // 16: chatto.api.v1.MyAccountService.UpdateSettings:input_type -> chatto.api.v1.UpdateSettingsRequest
	15, // 17: chatto.api.v1.MyAccountService.SetDMVisibility:input_type -> chatto.api.v1.SetDMVisibilityRequest
	26, // 18: chatto.api.v1.MyAccountService.ListExternalIdentities:input_type -> chatto.api.v1.ListExternalIdentitiesRequest
	27, // 19: chatto.api.v1.MyAccountService.StartExternalIdentityLink:input_type -> chatto.api.v1.StartExternalIdentityLinkRequest
	28, // 20: chatto.api.v1.MyAccountService.DisconnectExternalIdentity:input_type -> chatto.api.v1.DisconnectExternalIdentityRequest
	29, // 21: chatto.api.v1.MyAccountService.SetPresence:input_type -> chatto.api.v1.SetPresenceRequest
	30, // 22: chatto.api.v1.MyAccountService.GetPresencePreference:input_type -> chatto.api.v1.GetPresencePreferenceRequest
	31, // 23: chatto.api.v1.MyAccountService.SetPresencePreference:input_type -> chatto.api.v1.SetPresencePreferenceRequest
	32, // 24: chatto.api.v1.MyAccountService.RefreshPresence:input_type -> chatto.api.v1.RefreshPresenceRequest
	33, // 25: chatto.api.v1.MyAccountService.SetCustomStatus:input_type -> chatto.api.v1.SetCustomStatusRequest
	34, // 26: chatto.api.v1.MyAccountService.DeleteCustomStatus:input_type -> chatto.api.v1.DeleteCustomStatusRequest
	17, // 27: chatto.api.v1.MyAccountService.RequestAccountDeletion:input_type -> chatto.api.v1.RequestAccountDeletionRequest
	19, // 28: chatto.api.v1.MyAccountService.DeleteMyAccount:input_type -> chatto.api.v1.DeleteMyAccountRequest
	1,  // 29: chatto.api.v1.MyAccountService.ChangePassword:output_type -> chatto.api.v1.ChangePasswordResponse
	4,  // 30: chatto.api.v1.MyAccountService.ListVerifiedEmails:output_type -> chatto.api.v1.ListVerifiedEmailsResponse
	6,  // 31: chatto.api.v1.MyAccountService.RequestEmailVerification:output_type -> chatto.api.v1.RequestEmailVerificationResponse
	8,  // 32: chatto.api.v1.MyAccountService.ConfirmEmailVerification:output_type -> chatto.api.v1.ConfirmEmailVerificationResponse
	10, // 33: chatto.api.v1.MyAccountService.SetPrimaryEmail:output_type -> chatto.api.v1.SetPrimaryEmailResponse
	12, // 34: chatto.api.v1.MyAccountService.GetSettings:output_type -> chatto.api.v1.GetSettingsResponse
	14, // 35: chatto.api.v1.MyAccountService.UpdateSettings:output_type -> chatto.api.v1.UpdateSettingsResponse
	16, // 36: chatto.api.v1.MyAccountService.SetDMVisibility:output_type -> chatto.api.v1.SetDMVisibilityResponse
	35, // 37: chatto.api.v1.MyAccountService.ListExternalIdentities:output_type -> chatto.api.v1.ListExternalIdentitiesResponse
	36, // 38: chatto.api.v1.MyAccountService.StartExternalIdentityLink:output_type -> chatto.api.v1.StartExternalIdentityLinkResponse
	37, // 39: chatto.api.v1.MyAccountService.DisconnectExternalIdentity:output_type -> chatto.api.v1.DisconnectExternalIdentityResponse
	38, // 40: chatto.api.v1.MyAccountService.SetPresence:output_type -> chatto.api.v1.SetPresenceResponse
	39, // 41: chatto.api.v1.MyAccountService.GetPresencePreference:output_type -> chatto.api.v1.GetPresencePreferenceResponse
	40, // 42: chatto.api.v1.MyAccountService.SetPresencePreference:output_type -> chatto.api.v1.SetPresencePreferenceResponse
	41, // 43: chatto.api.v1.MyAccountService.RefreshPresence:output_type -> chatto.api.v1.RefreshPresenceResponse
	42, // 44: chatto.api.v1.MyAccountService.SetCustomStatus:output_type -> chatto.api.v1.SetCustomStatusResponse
	43, // 45: chatto.api.v1.MyAccountService.DeleteCustomStatus:output_type -> chatto.api.v1.DeleteCustomStatusResponse
	18, // 46: chatto.api.v1.MyAccountService.RequestAccountDeletion:output_type -> chatto.api.v1.RequestAccountDeletionResponse
	20, // 47: chatto.api.v1.MyAccountService.DeleteMyAccount:output_type -> chatto.api.v1.DeleteMyAccountResponse
	29, // [29:48] is the sub-list for method output_type
	10, // [10:29] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_account_proto_init() }
func file_chatto_api_v1_account_proto_init() {
	if File_chatto_api_v1_account_proto != nil {
		return
	}
	file_chatto_api_v1_external_identities_proto_init()
	file_chatto_api_v1_presence_proto_init()
	file_chatto_api_v1_user_status_proto_init()
	file_chatto_api_v1_users_proto_init()
	file_chatto_api_v1_viewer_proto_init()
	file_chatto_api_v1_account_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_account_proto_rawDesc), len(file_chatto_api_v1_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_api_v1_account_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_account_proto_depIdxs,
		MessageInfos:      file_chatto_api_v1_account_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_account_proto = out.File
	file_chatto_api_v1_account_proto_goTypes = nil
	file_chatto_api_v1_account_proto_depIdxs = nil
}
