// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: chatto/api/v1/viewer.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User preference for rendering times in clients.
type TimeFormat int32

const (
	// No explicit preference was stored.
	TimeFormat_TIME_FORMAT_UNSPECIFIED TimeFormat = 0
	// Let the client choose based on locale and browser settings.
	TimeFormat_TIME_FORMAT_AUTO TimeFormat = 1
	// Render times using a 12-hour clock.
	TimeFormat_TIME_FORMAT_12_HOUR TimeFormat = 2
	// Render times using a 24-hour clock.
	TimeFormat_TIME_FORMAT_24_HOUR TimeFormat = 3
)

// Enum value maps for TimeFormat.
var (
	TimeFormat_name = map[int32]string{
		0: "TIME_FORMAT_UNSPECIFIED",
		1: "TIME_FORMAT_AUTO",
		2: "TIME_FORMAT_12_HOUR",
		3: "TIME_FORMAT_24_HOUR",
	}
	TimeFormat_value = map[string]int32{
		"TIME_FORMAT_UNSPECIFIED": 0,
		"TIME_FORMAT_AUTO":        1,
		"TIME_FORMAT_12_HOUR":     2,
		"TIME_FORMAT_24_HOUR":     3,
	}
)

func (x TimeFormat) Enum() *TimeFormat {
	p := new(TimeFormat)
	*p = x
	return p
}

func (x TimeFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_api_v1_viewer_proto_enumTypes[0].Descriptor()
}

func (TimeFormat) Type() protoreflect.EnumType {
	return &file_chatto_api_v1_viewer_proto_enumTypes[0]
}

func (x TimeFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeFormat.Descriptor instead.
func (TimeFormat) EnumDescriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{0}
}

// Server-level display settings for the authenticated user.
type UserSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional IANA timezone override. Absent means no choice has been recorded.
	// Empty means the user explicitly chose the browser's local timezone.
	// Both use browser-local time; only absence permits automatic device reporting.
	Timezone *string `protobuf:"bytes,1,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	// Preferred time format.
	TimeFormat TimeFormat `protobuf:"varint,2,opt,name=time_format,json=timeFormat,proto3,enum=chatto.api.v1.TimeFormat" json:"time_format,omitempty"`
	// Whether the stored time zone may appear on the user's public profile.
	// New servers always set this field. Its absence means the server does not
	// support private time zones and may publish any stored time zone.
	ShareTimezone *bool `protobuf:"varint,3,opt,name=share_timezone,json=shareTimezone,proto3,oneof" json:"share_timezone,omitempty"`
	// Private DM room IDs hidden from this account's normal conversation list.
	// Saved on this server and shared across clients. Membership, history, and
	// notification preferences are unchanged. New messages do not restore a DM.
	HiddenDmRoomIds []string `protobuf:"bytes,4,rep,name=hidden_dm_room_ids,json=hiddenDmRoomIds,proto3" json:"hidden_dm_room_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserSettings) Reset() {
	*x = UserSettings{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettings) ProtoMessage() {}

func (x *UserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettings.ProtoReflect.Descriptor instead.
func (*UserSettings) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{0}
}

func (x *UserSettings) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

func (x *UserSettings) GetTimeFormat() TimeFormat {
	if x != nil {
		return x.TimeFormat
	}
	return TimeFormat_TIME_FORMAT_UNSPECIFIED
}

func (x *UserSettings) GetShareTimezone() bool {
	if x != nil && x.ShareTimezone != nil {
		return *x.ShareTimezone
	}
	return false
}

func (x *UserSettings) GetHiddenDmRoomIds() []string {
	if x != nil {
		return x.HiddenDmRoomIds
	}
	return nil
}

// Current authenticated user's public profile plus self-only settings.
type ViewerUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the account has at least one verified email address.
	HasVerifiedEmail bool `protobuf:"varint,7,opt,name=has_verified_email,json=hasVerifiedEmail,proto3" json:"has_verified_email,omitempty"`
	// Current user's display settings.
	Settings *UserSettings `protobuf:"bytes,8,opt,name=settings,proto3" json:"settings,omitempty"`
	// Whether the authenticated user may delete this account.
	ViewerCanDeleteAccount bool `protobuf:"varint,9,opt,name=viewer_can_delete_account,json=viewerCanDeleteAccount,proto3" json:"viewer_can_delete_account,omitempty"`
	// Last time a login credential changed, when known.
	LastLoginChange *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_login_change,json=lastLoginChange,proto3" json:"last_login_change,omitempty"`
	// Public user fields for the authenticated user.
	Profile *User `protobuf:"bytes,11,opt,name=profile,proto3" json:"profile,omitempty"`
	// Whether this account currently has a password sign-in credential.
	HasPassword   bool `protobuf:"varint,12,opt,name=has_password,json=hasPassword,proto3" json:"has_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewerUser) Reset() {
	*x = ViewerUser{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewerUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewerUser) ProtoMessage() {}

func (x *ViewerUser) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewerUser.ProtoReflect.Descriptor instead.
func (*ViewerUser) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{1}
}

func (x *ViewerUser) GetHasVerifiedEmail() bool {
	if x != nil {
		return x.HasVerifiedEmail
	}
	return false
}

func (x *ViewerUser) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *ViewerUser) GetViewerCanDeleteAccount() bool {
	if x != nil {
		return x.ViewerCanDeleteAccount
	}
	return false
}

func (x *ViewerUser) GetLastLoginChange() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginChange
	}
	return nil
}

func (x *ViewerUser) GetProfile() *User {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *ViewerUser) GetHasPassword() bool {
	if x != nil {
		return x.HasPassword
	}
	return false
}

// Permission-derived capabilities for the authenticated user.
type ViewerCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Keyed capability decisions for the authenticated user.
	Grants []*CapabilityGrant `protobuf:"bytes,1,rep,name=grants,proto3" json:"grants,omitempty"`
	// Whether the user has unread followed threads.
	HasUnreadFollowedThreads bool `protobuf:"varint,2,opt,name=has_unread_followed_threads,json=hasUnreadFollowedThreads,proto3" json:"has_unread_followed_threads,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ViewerCapabilities) Reset() {
	*x = ViewerCapabilities{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewerCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewerCapabilities) ProtoMessage() {}

func (x *ViewerCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewerCapabilities.ProtoReflect.Descriptor instead.
func (*ViewerCapabilities) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{2}
}

func (x *ViewerCapabilities) GetGrants() []*CapabilityGrant {
	if x != nil {
		return x.Grants
	}
	return nil
}

func (x *ViewerCapabilities) GetHasUnreadFollowedThreads() bool {
	if x != nil {
		return x.HasUnreadFollowedThreads
	}
	return false
}

// Effective server/channel permission decisions for the authenticated user.
type ServerViewerPermissions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One row per permission known to the server.
	Permissions   []*PermissionGrant `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerViewerPermissions) Reset() {
	*x = ServerViewerPermissions{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerViewerPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerViewerPermissions) ProtoMessage() {}

func (x *ServerViewerPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerViewerPermissions.ProtoReflect.Descriptor instead.
func (*ServerViewerPermissions) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{3}
}

func (x *ServerViewerPermissions) GetPermissions() []*PermissionGrant {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// Non-permission server state for the authenticated user.
type ServerViewerState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether any joined channel room has neutral Badge attention.
	HasUnreadRooms bool `protobuf:"varint,1,opt,name=has_unread_rooms,json=hasUnreadRooms,proto3" json:"has_unread_rooms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerViewerState) Reset() {
	*x = ServerViewerState{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerViewerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerViewerState) ProtoMessage() {}

func (x *ServerViewerState) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerViewerState.ProtoReflect.Descriptor instead.
func (*ServerViewerState) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{4}
}

func (x *ServerViewerState) GetHasUnreadRooms() bool {
	if x != nil {
		return x.HasUnreadRooms
	}
	return false
}

// State of explicit privileged-mode activation for this authenticated session.
type PrivilegedModeState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the user has an elevation-required permission entitlement. This
	// includes owner entitlement and explicit allows at any supported scope.
	Available bool `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	// Whether elevated permissions are effective for this session now.
	Active bool `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	// Absolute activation deadline. Present only while privileged mode is active.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivilegedModeState) Reset() {
	*x = PrivilegedModeState{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivilegedModeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivilegedModeState) ProtoMessage() {}

func (x *PrivilegedModeState) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivilegedModeState.ProtoReflect.Descriptor instead.
func (*PrivilegedModeState) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{5}
}

func (x *PrivilegedModeState) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *PrivilegedModeState) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *PrivilegedModeState) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// Request for the authenticated viewer snapshot.
type GetViewerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetViewerRequest) Reset() {
	*x = GetViewerRequest{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetViewerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewerRequest) ProtoMessage() {}

func (x *GetViewerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewerRequest.ProtoReflect.Descriptor instead.
func (*GetViewerRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{6}
}

// Authenticated viewer snapshot needed by application shells.
type GetViewerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current authenticated user.
	User *ViewerUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// Permission-derived capabilities.
	Capabilities *ViewerCapabilities `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Effective server/channel permission decisions for the authenticated user.
	ViewerPermissions *ServerViewerPermissions `protobuf:"bytes,5,opt,name=viewer_permissions,json=viewerPermissions,proto3" json:"viewer_permissions,omitempty"`
	// Non-permission server state for the authenticated user.
	ViewerState *ServerViewerState `protobuf:"bytes,6,opt,name=viewer_state,json=viewerState,proto3" json:"viewer_state,omitempty"`
	// Explicit privilege activation state for this authenticated session.
	PrivilegedMode *PrivilegedModeState `protobuf:"bytes,7,opt,name=privileged_mode,json=privilegedMode,proto3" json:"privileged_mode,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetViewerResponse) Reset() {
	*x = GetViewerResponse{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetViewerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewerResponse) ProtoMessage() {}

func (x *GetViewerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewerResponse.ProtoReflect.Descriptor instead.
func (*GetViewerResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{7}
}

func (x *GetViewerResponse) GetUser() *ViewerUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetViewerResponse) GetCapabilities() *ViewerCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *GetViewerResponse) GetViewerPermissions() *ServerViewerPermissions {
	if x != nil {
		return x.ViewerPermissions
	}
	return nil
}

func (x *GetViewerResponse) GetViewerState() *ServerViewerState {
	if x != nil {
		return x.ViewerState
	}
	return nil
}

func (x *GetViewerResponse) GetPrivilegedMode() *PrivilegedModeState {
	if x != nil {
		return x.PrivilegedMode
	}
	return nil
}

// Request to activate all currently entitled elevation-required permissions.
type ActivatePrivilegedModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivatePrivilegedModeRequest) Reset() {
	*x = ActivatePrivilegedModeRequest{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivatePrivilegedModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivatePrivilegedModeRequest) ProtoMessage() {}

func (x *ActivatePrivilegedModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivatePrivilegedModeRequest.ProtoReflect.Descriptor instead.
func (*ActivatePrivilegedModeRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{8}
}

// Result of activating privileged mode for the current session.
type ActivatePrivilegedModeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current privileged-mode state after activation.
	PrivilegedMode *PrivilegedModeState `protobuf:"bytes,1,opt,name=privileged_mode,json=privilegedMode,proto3" json:"privileged_mode,omitempty"`
	// Permission-derived capabilities that are effective after activation.
	Capabilities *ViewerCapabilities `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Effective server permission decisions after activation.
	ViewerPermissions *ServerViewerPermissions `protobuf:"bytes,3,opt,name=viewer_permissions,json=viewerPermissions,proto3" json:"viewer_permissions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ActivatePrivilegedModeResponse) Reset() {
	*x = ActivatePrivilegedModeResponse{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivatePrivilegedModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivatePrivilegedModeResponse) ProtoMessage() {}

func (x *ActivatePrivilegedModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivatePrivilegedModeResponse.ProtoReflect.Descriptor instead.
func (*ActivatePrivilegedModeResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{9}
}

func (x *ActivatePrivilegedModeResponse) GetPrivilegedMode() *PrivilegedModeState {
	if x != nil {
		return x.PrivilegedMode
	}
	return nil
}

func (x *ActivatePrivilegedModeResponse) GetCapabilities() *ViewerCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ActivatePrivilegedModeResponse) GetViewerPermissions() *ServerViewerPermissions {
	if x != nil {
		return x.ViewerPermissions
	}
	return nil
}

// Request to deactivate all elevation-required permissions for this session.
type DeactivatePrivilegedModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivatePrivilegedModeRequest) Reset() {
	*x = DeactivatePrivilegedModeRequest{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivatePrivilegedModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivatePrivilegedModeRequest) ProtoMessage() {}

func (x *DeactivatePrivilegedModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivatePrivilegedModeRequest.ProtoReflect.Descriptor instead.
func (*DeactivatePrivilegedModeRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{10}
}

// Result of deactivating privileged mode for the current session.
type DeactivatePrivilegedModeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current privileged-mode state after deactivation.
	PrivilegedMode *PrivilegedModeState `protobuf:"bytes,1,opt,name=privileged_mode,json=privilegedMode,proto3" json:"privileged_mode,omitempty"`
	// Permission-derived capabilities that are effective after deactivation.
	Capabilities *ViewerCapabilities `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Effective server permission decisions after deactivation.
	ViewerPermissions *ServerViewerPermissions `protobuf:"bytes,3,opt,name=viewer_permissions,json=viewerPermissions,proto3" json:"viewer_permissions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeactivatePrivilegedModeResponse) Reset() {
	*x = DeactivatePrivilegedModeResponse{}
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivatePrivilegedModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivatePrivilegedModeResponse) ProtoMessage() {}

func (x *DeactivatePrivilegedModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_viewer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivatePrivilegedModeResponse.ProtoReflect.Descriptor instead.
func (*DeactivatePrivilegedModeResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_viewer_proto_rawDescGZIP(), []int{11}
}

func (x *DeactivatePrivilegedModeResponse) GetPrivilegedMode() *PrivilegedModeState {
	if x != nil {
		return x.PrivilegedMode
	}
	return nil
}

func (x *DeactivatePrivilegedModeResponse) GetCapabilities() *ViewerCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *DeactivatePrivilegedModeResponse) GetViewerPermissions() *ServerViewerPermissions {
	if x != nil {
		return x.ViewerPermissions
	}
	return nil
}

var File_chatto_api_v1_viewer_proto protoreflect.FileDescriptor

const file_chatto_api_v1_viewer_proto_rawDesc = "" +
	"\n" +
	"\x1achatto/api/v1/viewer.proto\x12\rchatto.api.v1\x1a\x1fchatto/api/v1/permissions.proto\x1a\x19chatto/api/v1/users.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe4\x01\n" +
	"\fUserSettings\x12\x1f\n" +
	"\btimezone\x18\x01 \x01(\tH\x00R\btimezone\x88\x01\x01\x12:\n" +
	"\vtime_format\x18\x02 \x01(\x0e2\x19.chatto.api.v1.TimeFormatR\n" +
	"timeFormat\x12*\n" +
	"\x0eshare_timezone\x18\x03 \x01(\bH\x01R\rshareTimezone\x88\x01\x01\x12+\n" +
	"\x12hidden_dm_room_ids\x18\x04 \x03(\tR\x0fhiddenDmRoomIdsB\v\n" +
	"\t_timezoneB\x11\n" +
	"\x0f_share_timezone\"\x93\x03\n" +
	"\n" +
	"ViewerUser\x12,\n" +
	"\x12has_verified_email\x18\a \x01(\bR\x10hasVerifiedEmail\x127\n" +
	"\bsettings\x18\b \x01(\v2\x1b.chatto.api.v1.UserSettingsR\bsettings\x129\n" +
	"\x19viewer_can_delete_account\x18\t \x01(\bR\x16viewerCanDeleteAccount\x12F\n" +
	"\x11last_login_change\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0flastLoginChange\x12-\n" +
	"\aprofile\x18\v \x01(\v2\x13.chatto.api.v1.UserR\aprofile\x12!\n" +
	"\fhas_password\x18\f \x01(\bR\vhasPasswordJ\x04\b\x01\x10\aR\x02idR\x05loginR\fdisplay_nameR\n" +
	"avatar_urlR\rcustom_statusR\x0fpresence_status\"\x8b\x01\n" +
	"\x12ViewerCapabilities\x126\n" +
	"\x06grants\x18\x01 \x03(\v2\x1e.chatto.api.v1.CapabilityGrantR\x06grants\x12=\n" +
	"\x1bhas_unread_followed_threads\x18\x02 \x01(\bR\x18hasUnreadFollowedThreads\"[\n" +
	"\x17ServerViewerPermissions\x12@\n" +
	"\vpermissions\x18\x01 \x03(\v2\x1e.chatto.api.v1.PermissionGrantR\vpermissions\"=\n" +
	"\x11ServerViewerState\x12(\n" +
	"\x10has_unread_rooms\x18\x01 \x01(\bR\x0ehasUnreadRooms\"\x86\x01\n" +
	"\x13PrivilegedModeState\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x12\n" +
	"\x10GetViewerRequest\"\xbd\x03\n" +
	"\x11GetViewerResponse\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.chatto.api.v1.ViewerUserR\x04user\x12E\n" +
	"\fcapabilities\x18\x02 \x01(\v2!.chatto.api.v1.ViewerCapabilitiesR\fcapabilities\x12U\n" +
	"\x12viewer_permissions\x18\x05 \x01(\v2&.chatto.api.v1.ServerViewerPermissionsR\x11viewerPermissions\x12C\n" +
	"\fviewer_state\x18\x06 \x01(\v2 .chatto.api.v1.ServerViewerStateR\vviewerState\x12K\n" +
	"\x0fprivileged_mode\x18\a \x01(\v2\".chatto.api.v1.PrivilegedModeStateR\x0eprivilegedModeJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05R\x1eserver_notification_preferenceR\x1droom_notification_preferences\"\x1f\n" +
	"\x1dActivatePrivilegedModeRequest\"\x8b\x02\n" +
	"\x1eActivatePrivilegedModeResponse\x12K\n" +
	"\x0fprivileged_mode\x18\x01 \x01(\v2\".chatto.api.v1.PrivilegedModeStateR\x0eprivilegedMode\x12E\n" +
	"\fcapabilities\x18\x02 \x01(\v2!.chatto.api.v1.ViewerCapabilitiesR\fcapabilities\x12U\n" +
	"\x12viewer_permissions\x18\x03 \x01(\v2&.chatto.api.v1.ServerViewerPermissionsR\x11viewerPermissions\"!\n" +
	"\x1fDeactivatePrivilegedModeRequest\"\x8d\x02\n" +
	" DeactivatePrivilegedModeResponse\x12K\n" +
	"\x0fprivileged_mode\x18\x01 \x01(\v2\".chatto.api.v1.PrivilegedModeStateR\x0eprivilegedMode\x12E\n" +
	"\fcapabilities\x18\x02 \x01(\v2!.chatto.api.v1.ViewerCapabilitiesR\fcapabilities\x12U\n" +
	"\x12viewer_permissions\x18\x03 \x01(\v2&.chatto.api.v1.ServerViewerPermissionsR\x11viewerPermissions*q\n" +
	"\n" +
	"TimeFormat\x12\x1b\n" +
	"\x17TIME_FORMAT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TIME_FORMAT_AUTO\x10\x01\x12\x17\n" +
	"\x13TIME_FORMAT_12_HOUR\x10\x02\x12\x17\n" +
	"\x13TIME_FORMAT_24_HOUR\x10\x032\xd3\x02\n" +
	"\rViewerService\x12N\n" +
	"\tGetViewer\x12\x1f.chatto.api.v1.GetViewerRequest\x1a .chatto.api.v1.GetViewerResponse\x12u\n" +
	"\x16ActivatePrivilegedMode\x12,.chatto.api.v1.ActivatePrivilegedModeRequest\x1a-.chatto.api.v1.ActivatePrivilegedModeResponse\x12{\n" +
	"\x18DeactivatePrivilegedMode\x12..chatto.api.v1.DeactivatePrivilegedModeRequest\x1a/.chatto.api.v1.DeactivatePrivilegedModeResponseB\xa7\x01\n" +
	"\x11com.chatto.api.v1B\vViewerProtoP\x01Z/hmans.de/chatto/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_viewer_proto_rawDescOnce sync.Once
	file_chatto_api_v1_viewer_proto_rawDescData []byte
)

func file_chatto_api_v1_viewer_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_viewer_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_viewer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_viewer_proto_rawDesc), len(file_chatto_api_v1_viewer_proto_rawDesc)))
	})
	return file_chatto_api_v1_viewer_proto_rawDescData
}

var file_chatto_api_v1_viewer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chatto_api_v1_viewer_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_chatto_api_v1_viewer_proto_goTypes = []any{
	(TimeFormat)(0),                          // 0: chatto.api.v1.TimeFormat
	(*UserSettings)(nil),                     // 1: chatto.api.v1.UserSettings
	(*ViewerUser)(nil),                       // 2: chatto.api.v1.ViewerUser
	(*ViewerCapabilities)(nil),               // 3: chatto.api.v1.ViewerCapabilities
	(*ServerViewerPermissions)(nil),          // 4: chatto.api.v1.ServerViewerPermissions
	(*ServerViewerState)(nil),                // 5: chatto.api.v1.ServerViewerState
	(*PrivilegedModeState)(nil),              // 6: chatto.api.v1.PrivilegedModeState
	(*GetViewerRequest)(nil),                 // 7: chatto.api.v1.GetViewerRequest
	(*GetViewerResponse)(nil),                // 8: chatto.api.v1.GetViewerResponse
	(*ActivatePrivilegedModeRequest)(nil),    // 9: chatto.api.v1.ActivatePrivilegedModeRequest
	(*ActivatePrivilegedModeResponse)(nil),   // 10: chatto.api.v1.ActivatePrivilegedModeResponse
	(*DeactivatePrivilegedModeRequest)(nil),  // 11: chatto.api.v1.DeactivatePrivilegedModeRequest
	(*DeactivatePrivilegedModeResponse)(nil), // 12: chatto.api.v1.DeactivatePrivilegedModeResponse
	(*timestamppb.Timestamp)(nil),            // 13: google.protobuf.Timestamp
	(*User)(nil),                             // 14: chatto.api.v1.User
	(*CapabilityGrant)(nil),                  // 15: chatto.api.v1.CapabilityGrant
	(*PermissionGrant)(nil),                  // 16: chatto.api.v1.PermissionGrant
}
var file_chatto_api_v1_viewer_proto_depIdxs = []int32{
	0,  // 0: chatto.api.v1.UserSettings.time_format:type_name -> chatto.api.v1.TimeFormat
	1,  // 1: chatto.api.v1.ViewerUser.settings:type_name -> chatto.api.v1.UserSettings
	13, // 2: chatto.api.v1.ViewerUser.last_login_change:type_name -> google.protobuf.Timestamp
	14, // 3: chatto.api.v1.ViewerUser.profile:type_name -> chatto.api.v1.User
	15, // 4: chatto.api.v1.ViewerCapabilities.grants:type_name -> chatto.api.v1.CapabilityGrant
	16, // 5: chatto.api.v1.ServerViewerPermissions.permissions:type_name -> chatto.api.v1.PermissionGrant
	13, // 6: chatto.api.v1.PrivilegedModeState.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 7: chatto.api.v1.GetViewerResponse.user:type_name -> chatto.api.v1.ViewerUser
	3,  // 8: chatto.api.v1.GetViewerResponse.capabilities:type_name -> chatto.api.v1.ViewerCapabilities
	4,  // 9: chatto.api.v1.GetViewerResponse.viewer_permissions:type_name -> chatto.api.v1.ServerViewerPermissions
	5,  // 10: chatto.api.v1.GetViewerResponse.viewer_state:type_name -> chatto.api.v1.ServerViewerState
	6,  // 11: chatto.api.v1.GetViewerResponse.privileged_mode:type_name -> chatto.api.v1.PrivilegedModeState
	6,  // 12: chatto.api.v1.ActivatePrivilegedModeResponse.privileged_mode:type_name -> chatto.api.v1.PrivilegedModeState
	3,  // 13: chatto.api.v1.ActivatePrivilegedModeResponse.capabilities:type_name -> chatto.api.v1.ViewerCapabilities
	4,  // 14: chatto.api.v1.ActivatePrivilegedModeResponse.viewer_permissions:type_name -> chatto.api.v1.ServerViewerPermissions
	6,  // 15: chatto.api.v1.DeactivatePrivilegedModeResponse.privileged_mode:type_name -> chatto.api.v1.PrivilegedModeState
	3,  // 16: chatto.api.v1.DeactivatePrivilegedModeResponse.capabilities:type_name -> chatto.api.v1.ViewerCapabilities
	4,  // 17: chatto.api.v1.DeactivatePrivilegedModeResponse.viewer_permissions:type_name -> chatto.api.v1.ServerViewerPermissions
	7,  // 18: chatto.api.v1.ViewerService.GetViewer:input_type -> chatto.api.v1.GetViewerRequest
	9,  // 19: chatto.api.v1.ViewerService.ActivatePrivilegedMode:input_type -> chatto.api.v1.ActivatePrivilegedModeRequest
	11, // 20: chatto.api.v1.ViewerService.DeactivatePrivilegedMode:input_type -> chatto.api.v1.DeactivatePrivilegedModeRequest
	8,  // 21: chatto.api.v1.ViewerService.GetViewer:output_type -> chatto.api.v1.GetViewerResponse
	10, // 22: chatto.api.v1.ViewerService.ActivatePrivilegedMode:output_type -> chatto.api.v1.ActivatePrivilegedModeResponse
	12, // 23: chatto.api.v1.ViewerService.DeactivatePrivilegedMode:output_type -> chatto.api.v1.DeactivatePrivilegedModeResponse
	21, // [21:24] is the sub-list for method output_type
	18, // [18:21] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_viewer_proto_init() }
func file_chatto_api_v1_viewer_proto_init() {
	if File_chatto_api_v1_viewer_proto != nil {
		return
	}
	file_chatto_api_v1_permissions_proto_init()
	file_chatto_api_v1_users_proto_init()
	file_chatto_api_v1_viewer_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_viewer_proto_rawDesc), len(file_chatto_api_v1_viewer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_api_v1_viewer_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_viewer_proto_depIdxs,
		EnumInfos:         file_chatto_api_v1_viewer_proto_enumTypes,
		MessageInfos:      file_chatto_api_v1_viewer_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_viewer_proto = out.File
	file_chatto_api_v1_viewer_proto_goTypes = nil
	file_chatto_api_v1_viewer_proto_depIdxs = nil
}
